// §7.2 Payout detail — order-level composition.
import { router, useLocalSearchParams } from 'expo-router'; import { View } from 'react-native';
import { usePayoutDetail } from '@bugsha/api'; import { AppBar, Badge, Card, Caption, Line, ListRow, Num, PayoutCard, Pp, Screen } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useStore } from '../../src/lib/store'; import { major, money, useL, CUR } from '../../src/lib/ui';
export default function Payout() { const { id } = useLocalSearchParams<{ id: string }>(); const s = useStore(); const { L } = useL(); const q = usePayoutDetail(db, id!) as any; const d = q.data; if (!d) return <Screen><Pp>…</Pp></Screen>; const p = d.payout ?? d; const cur = CUR[s.market];
  return <View style={{ flex: 1 }}><AppBar title={L('Payout', 'الدفعة')} onBack={() => router.back()} /><Screen top={false} gap={12}>
    <PayoutCard amount={major(p.net_minor ?? 0, s.market)} currency={cur.code} decimals={cur.dp} period={`${p.period_start} → ${p.period_end}`} note={`${p.status}${p.reference ? ' · ' + p.reference : ''}`} />
    <Card><View style={{ gap: 6 }}><Line k={L('Gross sales', 'إجمالي المبيعات')} v={<Num role="label">{money(p.gross_minor ?? 0, s.market)}</Num>} /><Line k={L('Commission', 'العمولة')} v={<Num role="label">{`−${money(p.commission_minor ?? 0, s.market)}`}</Num>} />{p.adjustments_minor ? <Line k={L('Adjustments', 'تسويات')} v={<Num role="label">{money(p.adjustments_minor, s.market)}</Num>} /> : null}{p.carry_in_minor ? <Line k={L('Carried in', 'مرحّل')} v={<Num role="label">{money(p.carry_in_minor, s.market)}</Num>} /> : null}<Line k={L('Net', 'الصافي')} v={<Num weight={700}>{money(p.net_minor ?? 0, s.market)}</Num>} strong /></View></Card>
    {p.hold_reason ? <Badge tone="time">{p.hold_reason}</Badge> : null}
    {(d.orders ?? d.lines ?? []).length ? <View>{((d.orders ?? d.lines) as any[]).map((o, i) => <ListRow key={i} label={<Num role="label" weight={600}>{o.code ?? o.reference_id?.slice(0, 8)}</Num>} sub={o.title_snapshot ?? o.entry_type} value={<Num role="label">{money(o.amount_minor ?? o.total_minor ?? 0, s.market)}</Num>} />)}</View> : <Caption>{L('Order-level lines appear once the run is executed.', 'تظهر البنود بعد تنفيذ الدفعة.')}</Caption>}</Screen></View>; }
