// §7.3 Cash — end of day: what the app says vs what the till says, variance tracked per store per day.
import { useState } from 'react'; import { router } from 'expo-router'; import { View } from 'react-native';
import { useCashLiability, useEndOfDay, useSubmitCashRecon, RpcError } from '@bugsha/api'; import { errorMessage } from '@bugsha/i18n';
import { AppBar, Banner, Button, Card, Foot, Input, Line, Num, Pp, Screen } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useSession } from '../../src/lib/session'; import { useStore } from '../../src/lib/store'; import { money, useL, CUR } from '../../src/lib/ui';
export default function Cash() { const s = useStore(); const { locale } = useSession(); const { L } = useL(); const today = new Date().toISOString().slice(0, 10); const eod = useEndOfDay(db, s.storeId, today) as any; const liab = useCashLiability(db, s.partnerId) as any; const m = useSubmitCashRecon(db); const [rep, setRep] = useState(''); const [err, setErr] = useState<string | null>(null); const [ok, setOk] = useState(false); const d = eod.data ?? {}; const cur = CUR[s.market];
  return <View style={{ flex: 1 }}><AppBar title={L('Cash — end of day', 'النقد — نهاية اليوم')} sub={today} onBack={() => router.back()} /><Screen top={false} gap={12}>
    <Card><View style={{ gap: 6 }}><Line k={L('Cash orders collected', 'طلبات نقدية مستلمة')} v={<Num role="label">{String(d.cash_orders ?? d.redeemed ?? 0)}</Num>} /><Line k={L('Cash the app expects', 'النقد المتوقع')} v={<Num weight={700}>{money(d.cash_expected_minor ?? 0, s.market)}</Num>} strong /><Line k={L('Commission on it', 'العمولة عليه')} v={<Num role="label">{money(d.cash_commission_minor ?? 0, s.market)}</Num>} /></View></Card>
    <Input label={L('Cash in the till from Bugsha orders', 'النقد في الصندوق من طلبات بقشة')} value={rep} onChangeText={setRep} keyboardType="decimal-pad" suffix={cur.code} hint={L('Count it before close. A variance is not a penalty — it is flagged for review.', 'عدّه قبل الإغلاق. الفرق ليس عقوبة — يُعلَّم للمراجعة.')} />
    {liab.data?.receivable_minor > 0 ? <Banner tone="time" title={L(`Commission owed on cash: ${money(liab.data.receivable_minor, s.market)}`, `العمولة المستحقة على النقد: ${money(liab.data.receivable_minor, s.market)}`)}>{L('Invoiced monthly. This never comes out of your card payouts.', 'تُفوتر شهرياً. لا تُخصم من مدفوعات البطاقة.')}</Banner> : null}
    {err ? <Banner tone="error" title={err} /> : null}{ok ? <Banner tone="fresh" title={L('Recorded', 'سُجّل')} /> : null}</Screen>
    <Foot><Button size="lg" fullWidth disabled={!rep || ok} loading={m.isPending} onPress={() => m.mutateAsync({ storeId: s.storeId, date: today, reportedMinor: Math.round(Number(rep) * Math.pow(10, cur.dp)) }).then(() => setOk(true)).catch((e: RpcError) => setErr(errorMessage(e.code, locale)))}>{L('Submit count', 'إرسال العدّ')}</Button></Foot></View>; }
