// §3.4.2 Listing management — active, scheduled, past. Publish is the primary action.
import { useState } from 'react'; import { router } from 'expo-router'; import { View } from 'react-native';
import { useListings } from '@bugsha/api';
import { AppBar, Badge, Button, Caption, Card, EmptyState, Foot, IconButton, Num, Screen, SegmentedControl, T, color } from '@bugsha/ui';
import { db } from '../../src/lib/supabase'; import { useStore } from '../../src/lib/store'; import { hhmm, minutesLeft, useL } from '../../src/lib/ui';
export default function Listings() { const s = useStore(); const { L, ar } = useL(); const ls = useListings(db, s.storeId) as any; const [f, setF] = useState<'active' | 'scheduled' | 'past'>('active');
  const rows = ((ls.data ?? []) as any[]).filter((l) => f === 'active' ? ['active', 'sold_out'].includes(l.status) && new Date(l.window_end_utc) > new Date() : f === 'scheduled' ? l.status === 'scheduled' || new Date(l.window_start_utc) > new Date(Date.now() + 864e5) : ['expired', 'cancelled'].includes(l.status) || new Date(l.window_end_utc) <= new Date());
  return <View style={{ flex: 1 }}><AppBar title={L('Listings', 'العروض')} sub={s.storeName} back={false} action={<IconButton icon="package" label={L('Templates', 'القوالب')} onPress={() => router.push('/templates')} />} />
    <View style={{ paddingHorizontal: 14, paddingTop: 10 }}><SegmentedControl value={f} onChange={setF} options={[{ value: 'active', label: L('Active', 'نشطة') }, { value: 'scheduled', label: L('Scheduled', 'مجدولة') }, { value: 'past', label: L('Past', 'سابقة') }]} /></View>
    <Screen top={false} gap={10}>{rows.length === 0 ? <EmptyState icon="package" title={f === 'active' ? L('Nothing live right now', 'لا شيء نشط الآن') : L('Nothing here', 'لا شيء هنا')} body={f === 'active' ? L('List a bag and it appears to customers within seconds.', 'أضف بقشة وستظهر للعملاء خلال ثوانٍ.') : undefined} /> : rows.map((l) => { const sold = l.quantity_total - l.quantity_remaining; const ml = minutesLeft(l.window_end_utc); const pct = l.quantity_total ? sold / l.quantity_total : 0; return <Card key={l.listing_id}><View style={{ gap: 8 }}>
      <View style={{ flexDirection: 'row', gap: 8, alignItems: 'center' }}><T weight={700} style={{ flex: 1 }}>{l.title_snapshot}</T>{l.quantity_remaining === 0 ? <Badge tone="fresh">{L('Sold out', 'نفدت')}</Badge> : l.status === 'cancelled' ? <Badge tone="error">{L('Cancelled', 'ملغي')}</Badge> : ml > 0 && ml <= 30 ? <Badge tone="urgent">{L(`Closes in ${ml} min`, `تنتهي خلال ${ml} د`)}</Badge> : ml <= 0 ? <Badge tone="neutral">{L('Closed', 'مغلق')}</Badge> : <Badge tone="time">{L('Selling', 'قيد البيع')}</Badge>}</View>
      <View style={{ flexDirection: 'row', gap: 12 }}><Num role="caption" color={color.textSecondary}>{`${l.local_date} · ${hhmm(l.local_start)}–${hhmm(l.local_end)}`}</Num><Num role="caption" color={color.textSecondary}>{`${sold}/${l.quantity_total} ${ar ? 'مباعة' : 'sold'}`}</Num></View>
      <View style={{ height: 5, borderRadius: 99, backgroundColor: color.sunken, overflow: 'hidden' }}><View style={{ width: `${Math.round(pct * 100)}%`, height: '100%', backgroundColor: color.brand }} /></View>
      {f === 'active' ? <View style={{ flexDirection: 'row', gap: 6 }}><Button variant="secondary" size="sm" iconStart="plus" onPress={() => router.push(`/listing/${l.listing_id}`)}>{L('Add stock', 'زيادة')}</Button><Button variant="ghost" size="sm" onPress={() => router.push(`/listing/${l.listing_id}`)}>{L('Edit', 'تعديل')}</Button></View> : null}</View></Card>; })}</Screen>
    <Foot><Button size="lg" fullWidth iconStart="plus" onPress={() => router.push('/listing/publish')}>{L('List a bag', 'أضف بقشة')}</Button></Foot></View>; }
