// S-O-021 Partner detail: readiness, documents verify/reject, contracts + commission, branches, staff, history;
// approve, activate, suspend (four-eyes), reinstate, reject, reliability override. Every action carries a reason.
import { useState } from 'react'; import { router, useLocalSearchParams } from 'expo-router'; import { View } from 'react-native';
import { useOps, useOpsMutation } from '@bugsha/api';
import { Badge, Banner, Button, Caption, Chip, Chips, Eyebrow, Input, ListRow, Num, Switch, T, color } from '@bugsha/ui'; import { db } from '../../../src/lib/supabase';
import { Choice, Field, FormBox, Panel, Empty, Row, day, isoDate, useAct, when } from '../../../src/lib/console';
const DOC_REJECT: Array<[string, string]> = [['doc_illegible', 'Illegible'], ['doc_expired', 'Expired'], ['doc_mismatch', 'Does not match the legal name']];
const SUSPEND: Array<[string, string]> = [['safety_incident', 'Safety incident'], ['licence_expired', 'Licence expired']];
export default function PartnerDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const q = useOps<any>(db, 'ops_partner_detail', { p_partner: id });
  const verify = useOpsMutation(db, 'ops_verify_document'); const approve = useOpsMutation(db, 'ops_approve_partner'); const activate = useOpsMutation(db, 'ops_activate_partner'); const reject = useOpsMutation(db, 'ops_reject_partner');
  const suspend = useOpsMutation(db, 'ops_suspend_partner'); const reinstate = useOpsMutation(db, 'ops_reinstate_partner'); const commission = useOpsMutation(db, 'ops_set_commission'); const override = useOpsMutation(db, 'ops_override_reliability');
  const { msg, tone, act } = useAct(); const [reason, setReason] = useState(''); const [modal, setModal] = useState<'reject_doc' | 'suspend' | 'commission' | 'reliability' | 'reject' | null>(null); const [docId, setDocId] = useState<string | null>(null);
  const [docReason, setDocReason] = useState(DOC_REJECT[0]![0]); const [susReason, setSusReason] = useState(SUSPEND[0]![0]); const [susDays, setSusDays] = useState('7'); const [honour, setHonour] = useState(true); const [bp, setBp] = useState(''); const [from, setFrom] = useState(isoDate(new Date())); const [score, setScore] = useState('');
  const d = q.data; if (!d) return <Caption>{q.isLoading ? 'Loading…' : 'Partner not found or outside your markets.'}</Caption>; const p = d.partner ?? {}; const docs: any[] = d.documents ?? []; const contracts: any[] = d.contracts ?? []; const stores: any[] = d.stores ?? [];
  const refetch = () => { q.refetch(); setModal(null); setReason(''); }; const suspended = p.suspended_until && new Date(p.suspended_until) > new Date();
  const ready = [['All required documents approved', docs.length > 0 && docs.every((x) => x.status === 'approved')], ['Contract accepted by the partner', contracts.some((c) => c.accepted_at)], ['A branch with opening hours', stores.some((s) => s.has_hours ?? s.hours_set ?? s.opening_hours ?? true)], ['Payout details on file', !!(p.payout_details_set ?? p.iban_last4 ?? p.payout_method ?? false)]] as Array<[string, boolean]>;
  const current = contracts.find((c) => c.accepted_at) ?? contracts[0];
  return <>
    <Button variant="ghost" size="sm" iconStart="arrow-left" style={{ alignSelf: 'flex-start' }} onPress={() => router.back()}>Partners</Button>
    <Row><T role="titleLg" weight={700}>{p.trading_name}</T><Badge tone={p.onboarding_status === 'active' ? 'fresh' : p.onboarding_status === 'rejected' ? 'error' : 'time'}>{String(p.onboarding_status ?? '').replace(/_/g, ' ')}</Badge>{suspended ? <Badge tone="urgent">suspended until {day(p.suspended_until)}</Badge> : null}<Caption>{p.market} · reliability {p.reliability_override ?? p.reliability_score ?? '—'}{p.reliability_override != null ? ' (overridden)' : ''}</Caption></Row>
    {msg ? <Banner tone={tone} title={msg} /> : null}
    <View style={{ flexDirection: 'row', gap: 14, alignItems: 'flex-start', flexWrap: 'wrap' }}>
      <Panel style={{ flex: 1, minWidth: 320, padding: 14, gap: 6 }}><Eyebrow>Overview</Eyebrow>
        <Field k="Legal name" v={p.legal_name ?? '—'} /><Field k="Registration" v={p.registration_number ?? p.licence_number ?? '—'} /><Field k="Contact" v={`${p.contact_name ?? ''} ${p.contact_phone ?? ''} ${p.contact_email ?? ''}`.trim() || '—'} /><Field k="Applied" v={when(p.created_at)} /><Field k="Commission" v={current ? `${current.commission_bp / 100}% · v${current.version}` : 'market default'} /></Panel>
      <Panel style={{ flex: 1, minWidth: 320, padding: 14, gap: 6 }}><Eyebrow>Readiness</Eyebrow>{ready.map(([label, ok]) => <Row key={label}><Badge tone={ok ? 'fresh' : 'time'}>{ok ? 'done' : 'open'}</Badge><T role="label">{label}</T></Row>)}<Caption>Activation runs automatically once all four are done.</Caption></Panel></View>
    <Eyebrow>Documents</Eyebrow>
    <Panel>{docs.map((x: any) => <View key={x.id}><ListRow icon="file-text" label={String(x.doc_type).replace(/_/g, ' ')} sub={`${x.storage_path ?? ''}${x.expires_on ? ' · expires ' + x.expires_on : ''}${x.rejection_text ? ' · ' + x.rejection_text : ''}`} value={<Row><Badge tone={x.status === 'approved' ? 'fresh' : x.status === 'rejected' ? 'error' : 'time'}>{x.status}</Badge>{x.status !== 'approved' ? <><Button size="sm" variant="secondary" onPress={() => act(verify, { p_doc: x.id, p_approve: true }, 'Document approved', refetch)}>Approve</Button><Button size="sm" variant="ghost" onPress={() => { setDocId(x.id); setModal(modal === 'reject_doc' && docId === x.id ? null : 'reject_doc'); }}>Reject</Button></> : null}</Row>} />
      {modal === 'reject_doc' && docId === x.id ? <View style={{ margin: 12 }}><FormBox title="Reject this document"><Choice options={DOC_REJECT} value={docReason} onChange={setDocReason} /><Input label="Tell the partner what to upload" value={reason} onChangeText={setReason} /><Row><Button variant="danger" disabled={!reason.trim()} onPress={() => act(verify, { p_doc: x.id, p_approve: false, p_reason_code: docReason, p_text: reason.trim() }, 'Document rejected — partner asked to re-upload', refetch)}>Reject</Button><Button variant="ghost" onPress={() => setModal(null)}>Cancel</Button></Row></FormBox></View> : null}</View>)}
      {docs.length === 0 ? <Empty>No documents uploaded yet.</Empty> : null}</Panel>
    <Row style={{ justifyContent: 'space-between' }}><Eyebrow>Contracts</Eyebrow><Button size="sm" variant="secondary" onPress={() => { setBp(current ? String(current.commission_bp / 100) : ''); setModal(modal === 'commission' ? null : 'commission'); }}>Set commission</Button></Row>
    {modal === 'commission' ? <FormBox title="New commission (four-eyes: a second admin approves)"><Row><View style={{ width: 160 }}><Input label="Commission %" value={bp} onChangeText={setBp} keyboardType="decimal-pad" /></View><View style={{ width: 180 }}><Input label="Effective from" value={from} onChangeText={setFrom} placeholder="YYYY-MM-DD" /></View></Row><Input label="Reason (audited)" value={reason} onChangeText={setReason} /><Row><Button disabled={!bp || !reason.trim()} onPress={() => act(commission, { p_partner: id, p_bp: Math.round(Number(bp) * 100), p_effective_from: from, p_reason: reason.trim() }, `Contract v${(current?.version ?? 0) + 1} issued at ${bp}% — the partner accepts it in the app`, refetch)}>Propose</Button><Button variant="ghost" onPress={() => setModal(null)}>Cancel</Button></Row></FormBox> : null}
    <Panel>{contracts.map((c: any) => <ListRow key={c.id} icon="file-text" label={<Num role="label" weight={600}>{`v${c.version} · ${c.commission_bp / 100}%`}</Num>} sub={`${c.payout_cadence} · from ${c.effective_from}${c.no_show_policy ? ' · no-show ' + c.no_show_policy : ''}`} value={<Badge tone={c.accepted_at ? 'fresh' : 'time'}>{c.accepted_at ? `accepted ${day(c.accepted_at)}` : 'awaiting partner'}</Badge>} />)}{contracts.length === 0 ? <Empty>No contract issued — approving issues v1 at the market rate.</Empty> : null}</Panel>
    <Eyebrow>Branches</Eyebrow>
    <Panel>{stores.map((s: any) => <ListRow key={s.store_id} icon="store" label={s.name ?? s.display_name} sub={[s.address_line ?? s.area, s.paused_until && new Date(s.paused_until) > new Date() ? `paused until ${when(s.paused_until)} (${s.pause_reason_code ?? ''})` : 'open'].filter(Boolean).join(' · ')} value={s.pause_reason_code === 'safety_incident' ? <Badge tone="error">quality hold</Badge> : undefined} />)}{stores.length === 0 ? <Empty>No branches yet.</Empty> : null}</Panel>
    <Eyebrow>Staff</Eyebrow>
    <Panel>{(d.staff ?? []).map((s: any, i: number) => <ListRow key={i} icon="user" label={s.name ?? s.display_name ?? s.user_id ?? s.email ?? '—'} sub={s.email ?? s.phone ?? (s.claimed === false ? 'invite not claimed' : '')} value={<Badge>{s.role}</Badge>} />)}{(d.staff ?? []).length === 0 ? <Empty>No staff.</Empty> : null}</Panel>
    <Eyebrow>Decision</Eyebrow>
    <Panel style={{ padding: 14, gap: 10 }}>
      <View style={{ width: 460 }}><Input label="Reason (audited, shown to the partner where relevant)" value={reason} onChangeText={setReason} placeholder="e.g. licence verified against MOCI portal" /></View>
      <Row>
        <Button onPress={() => act(approve, { p_partner: id, p_reason: reason || 'documents verified' }, 'Approved — contract v1 issued, partner must accept', refetch)} disabled={!['applied', 'under_review', 'documents_pending'].includes(p.onboarding_status)}>Approve &amp; issue contract</Button>
        <Button variant="secondary" onPress={() => act(activate, { p_partner: id, p_reason: reason || 'onboarding complete' }, 'Activated', refetch)} disabled={p.onboarding_status === 'active'}>Activate</Button>
        {suspended ? <Button variant="secondary" onPress={() => act(reinstate, { p_partner: id, p_reason: reason || 'issue resolved' }, 'Reinstated — listings can publish again', refetch)}>Reinstate</Button> : <Button variant="secondary" onPress={() => setModal(modal === 'suspend' ? null : 'suspend')} disabled={p.onboarding_status !== 'active'}>Suspend…</Button>}
        <Button variant="ghost" onPress={() => setModal(modal === 'reliability' ? null : 'reliability')}>Override reliability…</Button>
        <Button variant="danger" onPress={() => setModal(modal === 'reject' ? null : 'reject')} disabled={p.onboarding_status === 'rejected'}>Reject…</Button></Row>
      {modal === 'suspend' ? <FormBox title="Suspend this partner (four-eyes)"><Choice label="Reason" options={SUSPEND} value={susReason} onChange={setSusReason} /><Choice label="For" options={[['1', '1 day'], ['7', '7 days'], ['30', '30 days'], ['365', 'Indefinite (1 year)']]} value={susDays} onChange={setSusDays} /><Switch label="Honour existing reservations (customers still collect today's bags)" checked={honour} onChange={setHonour} /><Row><Button variant="danger" onPress={() => act(suspend, { p_partner: id, p_reason_code: susReason, p_until: new Date(Date.now() + Number(susDays) * 864e5).toISOString(), p_honour_existing: honour }, `Suspended for ${susDays} days`, refetch)}>Suspend</Button><Button variant="ghost" onPress={() => setModal(null)}>Cancel</Button></Row></FormBox> : null}
      {modal === 'reliability' ? <FormBox title="Override the reliability score"><Caption>Current computed score {p.reliability_score ?? '—'}. The override stays until cleared and shows in the partner list.</Caption><Row><View style={{ width: 140 }}><Input label="Score (0–100)" value={score} onChangeText={setScore} keyboardType="decimal-pad" /></View><View style={{ flex: 1 }}><Input label="Justification (at least 10 characters)" value={reason} onChangeText={setReason} /></View></Row><Row><Button disabled={!score || reason.trim().length < 10} onPress={() => act(override, { p_partner: id, p_score: Number(score), p_justification: reason.trim() }, `Reliability set to ${score}`, refetch)}>Override</Button><Button variant="ghost" onPress={() => setModal(null)}>Cancel</Button></Row></FormBox> : null}
      {modal === 'reject' ? <FormBox title="Reject the application"><Caption>The partner sees the reason in the app and can reapply after fixing it.</Caption><Chips>{[['ineligible', 'Not eligible'], ['documents', 'Documents not acceptable'], ['duplicate', 'Duplicate account']].map(([k, l]) => <Chip key={k} selected={docReason === k} onPress={() => setDocReason(k!)}>{l}</Chip>)}</Chips><Row><Button variant="danger" disabled={!reason.trim()} onPress={() => act(reject, { p_partner: id, p_reason_code: ['ineligible', 'documents', 'duplicate'].includes(docReason) ? docReason : 'ineligible', p_text: reason.trim() }, 'Rejected', refetch)}>Reject</Button><Button variant="ghost" onPress={() => setModal(null)}>Cancel</Button></Row></FormBox> : null}</Panel>
    <Eyebrow>History</Eyebrow>
    <Panel>{(d.history ?? []).slice(0, 20).map((h: any, i: number) => <ListRow key={i} label={`${h.from_status ?? '—'} → ${h.to_status}`} sub={h.reason_text ?? h.reason_code ?? ''} value={<Num role="caption" color={color.textSecondary}>{when(h.at ?? h.created_at)}</Num>} />)}{(d.history ?? []).length === 0 ? <Empty>No status changes yet.</Empty> : null}</Panel>
  </>;
}
