// §3.3 Template editor — price must sit at or below half the stated minimum value; alcohol refused outright.
import { useEffect, useState } from 'react'; import { router, useLocalSearchParams } from 'expo-router'; import { View } from 'react-native';
import { useTemplates, useUpsertTemplate, RpcError } from '@bugsha/api'; import { errorMessage } from '@bugsha/i18n';
import { AppBar, Banner, Button, Chip, Chips, Eyebrow, Foot, Input, Screen } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useSession } from '../../src/lib/session'; import { useStore } from '../../src/lib/store'; import { hhmm, useL, CUR } from '../../src/lib/ui';
const CATS: Array<[string, string, string]> = [['bakery', 'Bakery', 'مخبوزات'], ['meals', 'Meals', 'وجبات'], ['cafe', 'Café', 'كافيه'], ['grocery', 'Grocery', 'بقالة'], ['sweets', 'Desserts', 'حلويات']]; const DIET: Array<[string, string, string]> = [['vegetarian', 'Vegetarian', 'نباتي'], ['contains_gluten', 'Contains gluten', 'يحتوي غلوتين'], ['contains_nuts', 'May contain nuts', 'قد يحتوي مكسرات'], ['contains_dairy', 'Contains dairy', 'يحتوي ألبان'], ['halal', 'Halal', 'حلال']];
export default function Edit() { const { id, dup } = useLocalSearchParams<{ id?: string; dup?: string }>(); const s = useStore(); const { locale } = useSession(); const { L } = useL(); const q = useTemplates(db, s.partnerId) as any; const m = useUpsertTemplate(db); const cur = CUR[s.market]; const mul = Math.pow(10, cur.dp);
  const [f, setF] = useState({ en: '', ar: '', den: '', dar: '', cat: 'bakery', vmin: '', vmax: '', price: '', qty: '6', start: '21:00', end: '22:00', diet: [] as string[] }); const [err, setErr] = useState<string | null>(null);
  useEffect(() => { const src = ((q.data ?? []) as any[]).find((t) => t.id === (id ?? dup)); if (src) setF({ en: src.title_en, ar: src.title_ar, den: src.description_en ?? '', dar: src.description_ar ?? '', cat: src.category, vmin: (src.value_min_minor / mul).toFixed(cur.dp), vmax: (src.value_max_minor / mul).toFixed(cur.dp), price: (src.price_minor / mul).toFixed(cur.dp), qty: String(src.default_quantity), start: hhmm(src.default_window_start), end: hhmm(src.default_window_end), diet: src.dietary_flags ?? [] }); }, [q.data]);
  const vmin = Number(f.vmin) || 0, price = Number(f.price) || 0; const priceErr = price > vmin / 2 && vmin > 0 ? L(`Maximum is ${cur.code} ${(vmin / 2).toFixed(cur.dp)} — half the stated value`, `الحد الأقصى ${cur.code} ${(vmin / 2).toFixed(cur.dp)} — نصف القيمة المعلنة`) : undefined;
  const valid = f.en && f.ar && vmin > 0 && price > 0 && !priceErr && Number(f.qty) > 0;
  return <View style={{ flex: 1 }}><AppBar title={id ? f.en : L('New template', 'قالب جديد')} onBack={() => router.back()} /><Screen top={false} gap={12}>
    <Input label={L('Title — English', 'العنوان — إنجليزي')} value={f.en} onChangeText={(v) => setF({ ...f, en: v })} /><Input label={L('Title — Arabic', 'العنوان — عربي')} value={f.ar} onChangeText={(v) => setF({ ...f, ar: v })} />
    <Input label={L('Typical contents — English', 'المحتوى المعتاد — إنجليزي')} value={f.den} onChangeText={(v) => setF({ ...f, den: v })} multiline /><Input label={L('Typical contents — Arabic', 'المحتوى المعتاد — عربي')} value={f.dar} onChangeText={(v) => setF({ ...f, dar: v })} multiline />
    <Eyebrow>{L('Category', 'الفئة')}</Eyebrow><Chips>{CATS.map(([k, en, a]) => <Chip key={k} selected={f.cat === k} onPress={() => setF({ ...f, cat: k })}>{L(en, a)}</Chip>)}</Chips>
    <View style={{ flexDirection: 'row', gap: 8 }}><Input containerStyle={{ flex: 1 }} label={L('Value from', 'القيمة من')} value={f.vmin} onChangeText={(v) => setF({ ...f, vmin: v })} keyboardType="decimal-pad" suffix={cur.code} /><Input containerStyle={{ flex: 1 }} label={L('Value to', 'القيمة إلى')} value={f.vmax} onChangeText={(v) => setF({ ...f, vmax: v })} keyboardType="decimal-pad" suffix={cur.code} /></View>
    <Input label={L('Price', 'السعر')} value={f.price} onChangeText={(v) => setF({ ...f, price: v })} keyboardType="decimal-pad" suffix={cur.code} error={priceErr} hint={L('At most half the minimum value.', 'نصف القيمة الدنيا على الأكثر.')} />
    <View style={{ flexDirection: 'row', gap: 8 }}><Input containerStyle={{ flex: 1 }} label={L('Default quantity', 'الكمية الافتراضية')} value={f.qty} onChangeText={(v) => setF({ ...f, qty: v })} keyboardType="number-pad" /><Input containerStyle={{ flex: 1 }} label={L('From', 'من')} value={f.start} onChangeText={(v) => setF({ ...f, start: v })} placeholder="21:00" /><Input containerStyle={{ flex: 1 }} label={L('To', 'إلى')} value={f.end} onChangeText={(v) => setF({ ...f, end: v })} placeholder="22:00" /></View>
    <Eyebrow>{L('Dietary', 'غذائية')}</Eyebrow><Chips>{DIET.map(([k, en, a]) => <Chip key={k} selected={f.diet.includes(k)} onPress={() => setF({ ...f, diet: f.diet.includes(k) ? f.diet.filter((x) => x !== k) : [...f.diet, k] })}>{L(en, a)}</Chip>)}</Chips>
    {err ? <Banner tone="error" title={err} /> : null}</Screen>
    <Foot><Button size="lg" fullWidth disabled={!valid} loading={m.isPending} onPress={() => m.mutateAsync({ p_partner: s.partnerId, p_store: s.storeId, p_title_en: f.en, p_title_ar: f.ar, p_description_en: f.den || null, p_description_ar: f.dar || null, p_category: f.cat, p_value_min_minor: Math.round(vmin * mul), p_value_max_minor: Math.round((Number(f.vmax) || vmin * 1.6) * mul), p_price_minor: Math.round(price * mul), p_default_quantity: Number(f.qty), p_default_window_start: f.start, p_default_window_end: f.end, p_dietary_flags: f.diet, p_template_id: id ?? null }).then(() => router.back()).catch((e: RpcError) => setErr(errorMessage(e.code, locale)))}>{L('Save template', 'حفظ القالب')}</Button></Foot></View>; }
