// §3.3 Templates — per-store list. Archived, never deleted.
import { router } from 'expo-router'; import { View } from 'react-native';
import { useArchiveTemplate, useTemplates } from '@bugsha/api';
import { AppBar, Button, Caption, Card, IconButton, Num, Pp, Screen, T, color } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useStore } from '../../src/lib/store'; import { hhmm, money, useL } from '../../src/lib/ui';
export default function Templates() { const s = useStore(); const { L, ar } = useL(); const q = useTemplates(db, s.partnerId) as any; const archive = useArchiveTemplate(db);
  return <View style={{ flex: 1 }}><AppBar title={L('Bag templates', 'قوالب البقش')} onBack={() => router.back()} action={<IconButton icon="plus" label={L('New', 'جديد')} onPress={() => router.push('/templates/edit')} />} /><Screen top={false} gap={10}>
    {((q.data ?? []) as any[]).map((t) => <Card key={t.id}><View style={{ gap: 8 }}><T weight={700}>{ar ? t.title_ar : t.title_en}</T><View style={{ flexDirection: 'row', gap: 12, flexWrap: 'wrap' }}><Num role="caption" color={color.textSecondary}>{money(t.price_minor, s.market)}</Num><Num role="caption" color={color.textSecondary}>{`${hhmm(t.default_window_start)}–${hhmm(t.default_window_end)}`}</Num><Num role="caption" color={color.textSecondary}>{`${t.default_quantity} ${L('bags', 'بقش')}`}</Num></View>
      <View style={{ flexDirection: 'row', gap: 6 }}><Button variant="secondary" size="sm" onPress={() => router.push({ pathname: '/templates/edit', params: { id: t.id } })}>{L('Edit', 'تعديل')}</Button><Button variant="ghost" size="sm" onPress={() => router.push({ pathname: '/templates/edit', params: { dup: t.id } })}>{L('Duplicate', 'نسخ')}</Button><Button variant="ghost" size="sm" onPress={() => archive.mutateAsync(t.id).then(() => q.refetch())}>{L('Archive', 'أرشفة')}</Button></View></View></Card>)}
    <Pp style={{ fontSize: 12 }}>{L('Templates are archived, never deleted — past listings reference them.', 'تُؤرشف القوالب ولا تُحذف — العروض السابقة ترتبط بها.')}</Pp></Screen></View>; }
