// GENERATED from the Bugsha design system styles.css closure — do not hand-edit.
// Source: /Users/ahmedelshazly/Desktop/Bugsha app/Bugsha
export const cssVars = {
  '--font-space-grotesk': "\"Space Grotesk\",system-ui,sans-serif",
  '--font-readex': "\"Readex Pro\",system-ui,sans-serif",
  '--font-instrument-serif': "\"Instrument Serif\",Georgia,serif",
  '--font-amiri': "\"Amiri\",\"Noto Naskh Arabic\",serif",
  '--font-tajawal': "\"Tajawal\",system-ui,sans-serif",
  '--font-plex-sans': "\"IBM Plex Sans\",system-ui,sans-serif",
  '--font-plex-arabic': "\"IBM Plex Sans Arabic\",system-ui,sans-serif",
  '--font-plex-mono': "\"IBM Plex Mono\",ui-monospace,monospace",
  '--font-archivo': "\"Archivo\",system-ui,sans-serif",
  '--font-jetbrains': "\"JetBrains Mono\",ui-monospace,monospace",
  '--font-alexandria': "\"Alexandria\",system-ui,sans-serif",
  '--nm-ink-950': "#08090D",
  '--nm-ink-600': "#2A303E",
  '--nm-paper-50': "#FBF9F5",
  '--nm-amber-500': "#FFC12B",
  '--nm-ember-500': "#FF5C39",
  '--nm-mint-500': "#3DDC97",
  '--nm-violet-500': "#8E7BFF",
  '--dw-sand-50': "#FDF9F2",
  '--dw-cocoa-900': "#241811",
  '--dw-cocoa-400': "#9C8776",
  '--dw-terracotta-500': "#B5502F",
  '--cc-slate-950': "#080D14",
  '--cc-slate-500': "#5A6B7E",
  '--cc-slate-200': "#D7DEE6",
  '--cc-blue-500': "#1257E0",
  '--cc-green-500': "#00A878",
  '--cc-amber-500': "#E08A00",
  '--cc-red-500': "#D62F3D",
  '--cc-orange-500': "#FF7A45",
  '--tk-paper-50': "#F6F4EC",
  '--tk-ink-900': "#111110",
  '--tk-red-500': "#E4322B",
  '--tk-blue-500': "#1B4AE0",
  '--tk-green-600': "#1E7A4C",
  '--text-display-xl-size': "40px",
  '--text-display-size': "32px",
  '--text-title-lg-size': "24px",
  '--text-title-size': "20px",
  '--text-headline-size': "17px",
  '--text-body-lg-size': "17px",
  '--text-body-size': "15px",
  '--text-label-size': "13px",
  '--text-caption-size': "12px",
  '--text-micro-size': "11px",
  '--text-numeric-xl-size': "34px",
  '--text-code-size': "36px",
  '--weight-regular': "400",
  '--tracking-tight': "-0.02em",
  '--arabic-line-scale': "1.18",
  '--arabic-size-scale': "0.96",
  '--space-0': "0px",
  '--space-100': "8px",
  '--space-300': "24px",
  '--space-800': "64px",
  '--size-touch-min': "44px",
  '--size-touch-comfort': "52px",
  '--size-icon-sm': "16px",
  '--size-control-sm': "32px",
  '--size-avatar-sm': "32px",
  '--layout-gutter': "16px",
  '--layout-max-content': "420px",
  '--layout-max-partner': "1120px",
  '--layout-safe-bottom': "34px",
  '--border-hairline': "1px",
  '--radius-0': "0px",
  '--radius-lg': "16px",
  '--shadow-color-soft': "220 30% 12%",
  '--elevation-0': "none",
  '--elevation-1': "0 1px 2px hsl(var(--shadow-color-soft)/.08)",
  '--elevation-2': "0 2px 8px hsl(var(--shadow-color-soft)/.10)",
  '--elevation-3': "0 8px 24px hsl(var(--shadow-color-soft)/.14)",
  '--elevation-4': "0 16px 48px hsl(var(--shadow-color-soft)/.20)",
  '--elevation-sheet': "0 -8px 32px hsl(var(--shadow-color-soft)/.18)",
  '--elevation-inset': "inset 0 1px 0 hsl(0 0% 100%/.06)",
  '--elevation-print': "3px 3px 0 var(--tk-paper-50)",
  '--focus-ring-width': "3px",
  '--focus-ring-offset': "2px",
  '--motion-duration-instant': "0ms",
  '--motion-duration-fast': "0ms",
  '--motion-duration-base': "0ms",
  '--motion-duration-slow': "0ms",
  '--motion-duration-celebrate': "0ms",
  '--motion-ease-standard': "cubic-bezier(.2,0,0,1)",
  '--motion-ease-out': "cubic-bezier(0,0,.2,1)",
  '--motion-ease-in': "cubic-bezier(.4,0,1,1)",
  '--motion-ease-spring': "cubic-bezier(.2,.9,.25,1.2)",
  '--motion-ease-precise': "cubic-bezier(.4,0,.2,1)",
  '--motion-press-scale': "1",
  '--motion-countdown-pulse-period': "2000ms",
  '--violet-900': "#2E1065",
  '--violet-300': "#C4B5FD",
  '--ink-900': "#17141F",
  '--ink-200': "#E7E4EE",
  '--color-surface-canvas': "#14140F",
  '--color-surface-raised': "#1C1C17",
  '--color-surface-sunken': "#0D0D0A",
  '--color-surface-inverse': "var(--tk-paper-50)",
  '--color-surface-brand': "var(--violet-600)",
  '--color-surface-overlay': "hsl(60 6% 7% / .6)",
  '--color-surface-scrim': "linear-gradient(to top,hsl(60 6% 7% / .8),transparent)",
  '--color-text-primary': "var(--tk-paper-50)",
  '--color-text-secondary': "#A5A29A",
  '--color-text-tertiary': "#7A7770",
  '--color-text-inverse': "var(--tk-ink-900)",
  '--color-text-on-brand': "var(--tk-ink-900)",
  '--color-text-link': "var(--tk-red-500)",
  '--color-border-subtle': "#33322B",
  '--color-border-default': "var(--tk-paper-50)",
  '--color-border-strong': "var(--tk-paper-50)",
  '--color-border-focus': "var(--tk-red-500)",
  '--color-brand-primary': "var(--tk-paper-50)",
  '--color-brand-hover': "var(--tk-ink-700)",
  '--color-brand-press': "var(--tk-ink-700)",
  '--color-brand-tint': "#2A2922",
  '--color-brand-secondary': "var(--tk-red-500)",
  '--color-fresh': "#4FBF86",
  '--color-time': "var(--tk-ink-900)",
  '--color-time-urgent': "#FF5E56",
  '--color-error': "var(--tk-red-600)",
  '--color-info': "var(--tk-blue-500)",
  '--color-deal': "#FF5E56",
  '--color-rating': "var(--tk-paper-50)",
  '--color-partner-accent': "var(--tk-ink-900)",
  '--color-partner-surface': "var(--tk-paper-50)",
  '--color-skeleton': "#2A2922",
  '--font-display': "var(--font-archivo)",
  '--font-body': "var(--font-archivo)",
  '--font-numeric': "var(--font-jetbrains)",
  '--font-arabic-display': "var(--font-alexandria)",
  '--font-arabic-body': "var(--font-alexandria)",
  '--radius-card': "0px",
  '--border-card': "1.5px",
  '--elevation-card': "none",
  '--elevation-raised': "3px 3px 0 var(--tk-paper-50)",
  '--motion-ease-brand': "var(--motion-ease-standard)",
  '--motion-duration-brand': "var(--motion-duration-instant)",
  '--texture-canvas': "repeating-linear-gradient(180deg,hsl(60 6% 7% / .035) 0 1px,transparent 1px 4px)",
  '--cover-treatment': "none",
  '--icon-stroke': "2.25",
} as const;

export const tokens = {
  fontSpaceGrotesk: cssVars['--font-space-grotesk'],
  fontReadex: cssVars['--font-readex'],
  fontInstrumentSerif: cssVars['--font-instrument-serif'],
  fontAmiri: cssVars['--font-amiri'],
  fontTajawal: cssVars['--font-tajawal'],
  fontPlexSans: cssVars['--font-plex-sans'],
  fontPlexArabic: cssVars['--font-plex-arabic'],
  fontPlexMono: cssVars['--font-plex-mono'],
  fontArchivo: cssVars['--font-archivo'],
  fontJetbrains: cssVars['--font-jetbrains'],
  fontAlexandria: cssVars['--font-alexandria'],
  nmInk950: cssVars['--nm-ink-950'],
  nmInk600: cssVars['--nm-ink-600'],
  nmPaper50: cssVars['--nm-paper-50'],
  nmAmber500: cssVars['--nm-amber-500'],
  nmEmber500: cssVars['--nm-ember-500'],
  nmMint500: cssVars['--nm-mint-500'],
  nmViolet500: cssVars['--nm-violet-500'],
  dwSand50: cssVars['--dw-sand-50'],
  dwCocoa900: cssVars['--dw-cocoa-900'],
  dwCocoa400: cssVars['--dw-cocoa-400'],
  dwTerracotta500: cssVars['--dw-terracotta-500'],
  ccSlate950: cssVars['--cc-slate-950'],
  ccSlate500: cssVars['--cc-slate-500'],
  ccSlate200: cssVars['--cc-slate-200'],
  ccBlue500: cssVars['--cc-blue-500'],
  ccGreen500: cssVars['--cc-green-500'],
  ccAmber500: cssVars['--cc-amber-500'],
  ccRed500: cssVars['--cc-red-500'],
  ccOrange500: cssVars['--cc-orange-500'],
  tkPaper50: cssVars['--tk-paper-50'],
  tkInk900: cssVars['--tk-ink-900'],
  tkRed500: cssVars['--tk-red-500'],
  tkBlue500: cssVars['--tk-blue-500'],
  tkGreen600: cssVars['--tk-green-600'],
  textDisplayXlSize: cssVars['--text-display-xl-size'],
  textDisplaySize: cssVars['--text-display-size'],
  textTitleLgSize: cssVars['--text-title-lg-size'],
  textTitleSize: cssVars['--text-title-size'],
  textHeadlineSize: cssVars['--text-headline-size'],
  textBodyLgSize: cssVars['--text-body-lg-size'],
  textBodySize: cssVars['--text-body-size'],
  textLabelSize: cssVars['--text-label-size'],
  textCaptionSize: cssVars['--text-caption-size'],
  textMicroSize: cssVars['--text-micro-size'],
  textNumericXlSize: cssVars['--text-numeric-xl-size'],
  textCodeSize: cssVars['--text-code-size'],
  weightRegular: cssVars['--weight-regular'],
  trackingTight: cssVars['--tracking-tight'],
  arabicLineScale: cssVars['--arabic-line-scale'],
  arabicSizeScale: cssVars['--arabic-size-scale'],
  space0: cssVars['--space-0'],
  space100: cssVars['--space-100'],
  space300: cssVars['--space-300'],
  space800: cssVars['--space-800'],
  sizeTouchMin: cssVars['--size-touch-min'],
  sizeTouchComfort: cssVars['--size-touch-comfort'],
  sizeIconSm: cssVars['--size-icon-sm'],
  sizeControlSm: cssVars['--size-control-sm'],
  sizeAvatarSm: cssVars['--size-avatar-sm'],
  layoutGutter: cssVars['--layout-gutter'],
  layoutMaxContent: cssVars['--layout-max-content'],
  layoutMaxPartner: cssVars['--layout-max-partner'],
  layoutSafeBottom: cssVars['--layout-safe-bottom'],
  borderHairline: cssVars['--border-hairline'],
  radius0: cssVars['--radius-0'],
  radiusLg: cssVars['--radius-lg'],
  shadowColorSoft: cssVars['--shadow-color-soft'],
  elevation0: cssVars['--elevation-0'],
  elevation1: cssVars['--elevation-1'],
  elevation2: cssVars['--elevation-2'],
  elevation3: cssVars['--elevation-3'],
  elevation4: cssVars['--elevation-4'],
  elevationSheet: cssVars['--elevation-sheet'],
  elevationInset: cssVars['--elevation-inset'],
  elevationPrint: cssVars['--elevation-print'],
  focusRingWidth: cssVars['--focus-ring-width'],
  focusRingOffset: cssVars['--focus-ring-offset'],
  motionDurationInstant: cssVars['--motion-duration-instant'],
  motionDurationFast: cssVars['--motion-duration-fast'],
  motionDurationBase: cssVars['--motion-duration-base'],
  motionDurationSlow: cssVars['--motion-duration-slow'],
  motionDurationCelebrate: cssVars['--motion-duration-celebrate'],
  motionEaseStandard: cssVars['--motion-ease-standard'],
  motionEaseOut: cssVars['--motion-ease-out'],
  motionEaseIn: cssVars['--motion-ease-in'],
  motionEaseSpring: cssVars['--motion-ease-spring'],
  motionEasePrecise: cssVars['--motion-ease-precise'],
  motionPressScale: cssVars['--motion-press-scale'],
  motionCountdownPulsePeriod: cssVars['--motion-countdown-pulse-period'],
  violet900: cssVars['--violet-900'],
  violet300: cssVars['--violet-300'],
  ink900: cssVars['--ink-900'],
  ink200: cssVars['--ink-200'],
  colorSurfaceCanvas: cssVars['--color-surface-canvas'],
  colorSurfaceRaised: cssVars['--color-surface-raised'],
  colorSurfaceSunken: cssVars['--color-surface-sunken'],
  colorSurfaceInverse: cssVars['--color-surface-inverse'],
  colorSurfaceBrand: cssVars['--color-surface-brand'],
  colorSurfaceOverlay: cssVars['--color-surface-overlay'],
  colorSurfaceScrim: cssVars['--color-surface-scrim'],
  colorTextPrimary: cssVars['--color-text-primary'],
  colorTextSecondary: cssVars['--color-text-secondary'],
  colorTextTertiary: cssVars['--color-text-tertiary'],
  colorTextInverse: cssVars['--color-text-inverse'],
  colorTextOnBrand: cssVars['--color-text-on-brand'],
  colorTextLink: cssVars['--color-text-link'],
  colorBorderSubtle: cssVars['--color-border-subtle'],
  colorBorderDefault: cssVars['--color-border-default'],
  colorBorderStrong: cssVars['--color-border-strong'],
  colorBorderFocus: cssVars['--color-border-focus'],
  colorBrandPrimary: cssVars['--color-brand-primary'],
  colorBrandHover: cssVars['--color-brand-hover'],
  colorBrandPress: cssVars['--color-brand-press'],
  colorBrandTint: cssVars['--color-brand-tint'],
  colorBrandSecondary: cssVars['--color-brand-secondary'],
  colorFresh: cssVars['--color-fresh'],
  colorTime: cssVars['--color-time'],
  colorTimeUrgent: cssVars['--color-time-urgent'],
  colorError: cssVars['--color-error'],
  colorInfo: cssVars['--color-info'],
  colorDeal: cssVars['--color-deal'],
  colorRating: cssVars['--color-rating'],
  colorPartnerAccent: cssVars['--color-partner-accent'],
  colorPartnerSurface: cssVars['--color-partner-surface'],
  colorSkeleton: cssVars['--color-skeleton'],
  fontDisplay: cssVars['--font-display'],
  fontBody: cssVars['--font-body'],
  fontNumeric: cssVars['--font-numeric'],
  fontArabicDisplay: cssVars['--font-arabic-display'],
  fontArabicBody: cssVars['--font-arabic-body'],
  radiusCard: cssVars['--radius-card'],
  borderCard: cssVars['--border-card'],
  elevationCard: cssVars['--elevation-card'],
  elevationRaised: cssVars['--elevation-raised'],
  motionEaseBrand: cssVars['--motion-ease-brand'],
  motionDurationBrand: cssVars['--motion-duration-brand'],
  textureCanvas: cssVars['--texture-canvas'],
  coverTreatment: cssVars['--cover-treatment'],
  iconStroke: cssVars['--icon-stroke'],
} as const;

export type TokenName = keyof typeof tokens;

/** Resolve var(--x) references to their literal value for React Native. */
export function resolve(value: string, depth = 0): string {
  if (depth > 8) return value;
  return value.replace(/var\((--[a-z0-9-]+)\)/gi, (_, name) => resolve((cssVars as Record<string, string>)[name] ?? '', depth + 1));
}
