// §6 Analytics with insights and reliability.
import { router } from 'expo-router'; import { View } from 'react-native';
import { useAnalytics, useInsights, useReliability } from '@bugsha/api';
import { AppBar, Banner, Caption, Card, Eyebrow, PartnerStat, Screen, T } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useStore } from '../../src/lib/store'; import { money, useL } from '../../src/lib/ui';
export default function Analytics() { const s = useStore(); const { L } = useL(); const from = new Date(Date.now() - 30 * 864e5).toISOString().slice(0, 10), to = new Date().toISOString().slice(0, 10); const an = useAnalytics(db, s.partnerId, from, to) as any; const ins = useInsights(db, s.partnerId) as any; const rel = useReliability(db, s.partnerId) as any; const d = an.data ?? {};
  return <View style={{ flex: 1 }}><AppBar title={L('Analytics', 'التحليلات')} sub={L('Last 30 days', 'آخر 30 يوماً')} onBack={() => router.back()} /><Screen top={false} gap={12}>
    <View style={{ flexDirection: 'row', gap: 10 }}><PartnerStat label={L('Gross', 'الإجمالي')} value={money(d.gross_minor ?? 0, s.market)} icon="banknote" /><PartnerStat label={L('Net after commission', 'الصافي بعد العمولة')} value={money(d.net_minor ?? (d.gross_minor ?? 0) - (d.commission_minor ?? 0), s.market)} icon="wallet" /></View>
    <View style={{ flexDirection: 'row', gap: 10 }}><PartnerStat label={L('Bags sold', 'البقش المباعة')} value={String(d.bags_sold ?? d.orders ?? 0)} icon="package" /><PartnerStat label={L('Sell-through', 'نسبة البيع')} value={d.sell_through != null ? `${Math.round(d.sell_through * 100)}%` : '—'} icon="chart-column" /></View>
    <View style={{ flexDirection: 'row', gap: 10 }}><PartnerStat label={L('No-shows', 'عدم الحضور')} value={String(d.no_shows ?? 0)} icon="triangle-alert" tone={(d.no_shows ?? 0) > 3 ? 'urgent' : 'neutral'} /><PartnerStat label={L('Reliability', 'الموثوقية')} value={String(rel.data?.score ?? rel.data?.reliability_score ?? '—')} icon="circle-check" tone="fresh" /></View>
    {((Array.isArray(ins.data) ? ins.data : ins.data?.insights ?? []) as any[]).length ? <><Eyebrow>{L('Insights', 'ملاحظات')}</Eyebrow>{((Array.isArray(ins.data) ? ins.data : ins.data.insights ?? []) as any[]).map((i, k) => <Banner key={k} tone="info" title={i.title ?? i.key}>{i.body ?? i.detail}</Banner>)}</> : null}
    <Caption>{L('Figures are per partner across branches. Statements are on the desktop console.', 'الأرقام لكل شريك عبر الفروع. كشوف الحساب على لوحة سطح المكتب.')}</Caption></Screen></View>; }
