// Console · Branches — every branch, the one you act on, pause reservations with a reason, resume, hours, add a branch.
// app.my_stores_detail / pause_store_reservations / resume_store_reservations / pause_store.
import { useState } from 'react'; import { router } from 'expo-router'; import { View } from 'react-native';
import { useMyStores, usePartner, usePauseReservations, usePauseStore, useResumeReservations, RpcError } from '@bugsha/api'; import { errorMessage } from '@bugsha/i18n'; import { can } from '@bugsha/core';
import { AppBar, Badge, Banner, Button, Caption, Card, Chip, Chips, Eyebrow, Input, ListRow, Screen, T } from '@bugsha/ui';
import { db } from '../../src/lib/supabase'; import { useSession } from '../../src/lib/session'; import { useStore } from '../../src/lib/store'; import { useL } from '../../src/lib/ui';
const REASONS: Array<[string, string, string]> = [['staffing', 'Short-staffed', 'نقص موظفين'], ['unexpected_closure', 'Closed unexpectedly', 'إغلاق مفاجئ'], ['sold_through_trade', 'Sold through at the counter', 'نفد عند الكاشير'], ['other', 'Other', 'أخرى']];
export default function Branch() {
  const s = useStore(); const { locale } = useSession(); const { L } = useL(); const stores = useMyStores(db); const partner = usePartner(db, s.partnerId) as any; const pauseRes = usePauseReservations(db); const resume = useResumeReservations(db); const pauseStore = usePauseStore(db);
  const [mode, setMode] = useState<null | 'reservations' | 'store'>(null); const [reason, setReason] = useState('staffing'); const [text, setText] = useState(''); const [hours, setHours] = useState(2); const [err, setErr] = useState<string | null>(null); const [ok, setOk] = useState<string | null>(null);
  const mine = ((partner.data?.stores ?? []) as any[]).find((x) => x.store_id === s.storeId); const paused = mine?.paused_until && new Date(mine.paused_until) > new Date(); const manager = can(s.role, 'pauseStore') || s.role === 'owner' || s.role === 'manager';
  const act = (fn: () => Promise<unknown>, msg: string) => fn().then(() => { setOk(msg); setErr(null); setMode(null); partner.refetch(); stores.refetch(); }).catch((e: RpcError) => setErr(errorMessage(e.code, locale)));
  return <View style={{ flex: 1 }}><AppBar title={L('Branches', 'الفروع')} sub={s.tradingName} onBack={() => router.back()} /><Screen top={false} gap={12}>
    <Eyebrow>{L('This branch', 'هذا الفرع')}</Eyebrow>
    <Card><View style={{ gap: 8 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><T weight={700} style={{ flex: 1 }}>{s.storeName}</T>{paused ? <Badge tone="urgent">{L('Paused', 'متوقف')}</Badge> : <Badge tone="fresh">{L('Taking reservations', 'يستقبل حجوزات')}</Badge>}</View>
      {paused ? <Caption>{L(`Until ${String(mine.paused_until).slice(0, 16).replace('T', ' ')}${mine.pause_reason_code ? ' · ' + String(mine.pause_reason_code).replace(/_/g, ' ') : ''}. Existing orders are honoured.`, `حتى ${String(mine.paused_until).slice(0, 16).replace('T', ' ')}. الطلبات الحالية تُنفّذ.`)}</Caption> : <Caption>{L('Pausing blocks new listings and reservations. It never cancels existing orders — customers are still coming.', 'الإيقاف يمنع العروض والحجوزات الجديدة. لا يلغي الطلبات الحالية أبداً — العملاء قادمون.')}</Caption>}
      {manager ? <View style={{ flexDirection: 'row', gap: 6, flexWrap: 'wrap' }}>{paused ? <Button size="sm" onPress={() => act(() => resume.mutateAsync(s.storeId), L('Reservations resumed', 'استُؤنفت الحجوزات'))}>{L('Resume now', 'استئناف الآن')}</Button> : <><Button size="sm" variant="secondary" onPress={() => setMode('reservations')}>{L('Pause reservations', 'إيقاف الحجوزات')}</Button><Button size="sm" variant="ghost" onPress={() => setMode('store')}>{L('Close for a while', 'إغلاق لفترة')}</Button></>}</View> : <Caption>{L('Owners and managers pause a branch.', 'المالك والمدير يوقفان الفرع.')}</Caption>}</View></Card>
    {mode ? <Card><View style={{ gap: 10 }}><T weight={600}>{mode === 'reservations' ? L('Pause reservations', 'إيقاف الحجوزات') : L('Close the branch for a while', 'إغلاق الفرع لفترة')}</T>
      <Chips>{REASONS.map(([k, en, a]) => <Chip key={k} selected={reason === k} onPress={() => setReason(k)}>{L(en, a)}</Chip>)}</Chips>
      {mode === 'store' ? <Chips>{[2, 6, 24, 72].map((h) => <Chip key={h} selected={hours === h} onPress={() => setHours(h)}>{h < 24 ? L(`${h} hours`, `${h} ساعات`) : L(`${h / 24} days`, `${h / 24} أيام`)}</Chip>)}</Chips> : null}
      <Input label={L('Note for the team (optional)', 'ملاحظة للفريق (اختياري)')} value={text} onChangeText={setText} />
      <View style={{ flexDirection: 'row', gap: 8 }}><Button loading={pauseRes.isPending || pauseStore.isPending} onPress={() => mode === 'reservations' ? act(() => pauseRes.mutateAsync({ storeId: s.storeId, reason: `${reason}${text ? ': ' + text : ''}` }), L('Reservations paused', 'أُوقفت الحجوزات')) : act(() => pauseStore.mutateAsync({ storeId: s.storeId, reason, until: new Date(Date.now() + hours * 3600e3).toISOString() }), L('Branch paused', 'أُوقف الفرع'))}>{L('Confirm', 'تأكيد')}</Button><Button variant="ghost" onPress={() => setMode(null)}>{L('Cancel', 'إلغاء')}</Button></View></View></Card> : null}
    {ok ? <Banner tone="fresh" title={ok} /> : null}{err ? <Banner tone="error" title={err} /> : null}
    <ListRow icon="clock" label={L('Opening hours', 'ساعات العمل')} chevron onPress={() => router.push('/onboarding/hours')} />
    <ListRow icon="map-pin" label={L('Pickup point & pin', 'نقطة الاستلام والدبوس')} sub={L('Edit from a new branch form for now', 'عدّل من نموذج فرع جديد حالياً')} chevron onPress={() => router.push('/onboarding/store')} />
    <Eyebrow>{L('All branches', 'كل الفروع')}</Eyebrow>
    <View>{((stores.data ?? []) as any[]).map((r) => <ListRow key={r.store_id} icon="store" label={<T role="label" weight={r.store_id === s.storeId ? 700 : 500}>{r.display_name}</T>} sub={r.role} value={r.store_id === s.storeId ? <Badge tone="brand">{L('Current', 'الحالي')}</Badge> : undefined} chevron={r.store_id !== s.storeId} onPress={r.store_id !== s.storeId ? () => { s.set({ storeId: r.store_id, partnerId: r.partner_id, role: r.role as any, storeName: r.display_name, tradingName: r.trading_name, market: r.market as any, timezone: r.timezone }); router.replace('/(tabs)'); } : undefined} />)}</View>
    {s.role === 'owner' ? <Button variant="secondary" fullWidth iconStart="plus" onPress={() => router.push('/onboarding/store')}>{L('Add a branch', 'أضف فرعاً')}</Button> : null}</Screen></View>;
}
