// Console · Quality — open flags with a deadline, acknowledged with a finding and an action; customer reports on your
// orders with the statement ops asks for; the quality-hold banner. app.my_quality_flags / acknowledge_flag / my_disputes / respond_dispute.
import { useState } from 'react'; import { router } from 'expo-router'; import { View } from 'react-native';
import { useAcknowledgeFlag, useMyDisputes, usePartner, useQualityFlags, useRespondDispute, RpcError } from '@bugsha/api'; import { errorMessage } from '@bugsha/i18n';
import { AppBar, Badge, Banner, Button, Caption, Card, EmptyState, Eyebrow, Input, Num, Pp, Screen, SegmentedControl, T, color } from '@bugsha/ui';
import { db } from '../../src/lib/supabase'; import { useSession } from '../../src/lib/session'; import { useStore } from '../../src/lib/store'; import { useL } from '../../src/lib/ui';
const when = (iso?: string | null) => (iso ? String(iso).slice(0, 16).replace('T', ' ') : '—');
export default function Quality() {
  const s = useStore(); const { locale } = useSession(); const { L } = useL(); const flags = useQualityFlags(db, s.partnerId); const disputes = useMyDisputes(db, s.partnerId); const partner = usePartner(db, s.partnerId) as any; const ack = useAcknowledgeFlag(db); const respond = useRespondDispute(db);
  const [tab, setTab] = useState<'flags' | 'reports'>('flags'); const [open, setOpen] = useState<string | null>(null); const [finding, setFinding] = useState(''); const [action, setAction] = useState(''); const [err, setErr] = useState<string | null>(null);
  const hold = ((partner.data?.stores ?? []) as any[]).find((x) => x.pause_reason_code === 'safety_incident' && x.paused_until && new Date(x.paused_until) > new Date());
  const fl = (flags.data ?? []) as any[]; const dl = (disputes.data ?? []) as any[]; const openFlags = fl.filter((f) => !f.acknowledged_at).length; const openReports = dl.filter((d) => !d.partner_statement && !d.resolved_at).length;
  const tone = (sev: string) => (sev === 'critical' ? 'error' : sev === 'high' ? 'urgent' : 'time');
  return <View style={{ flex: 1 }}><AppBar title={L('Quality', 'الجودة')} sub={s.tradingName} onBack={() => router.back()} />
    <View style={{ paddingHorizontal: 14, paddingTop: 10 }}><SegmentedControl value={tab} onChange={setTab} options={[{ value: 'flags', label: L(`Flags${openFlags ? ' · ' + openFlags : ''}`, `تنبيهات${openFlags ? ' · ' + openFlags : ''}`) }, { value: 'reports', label: L(`Customer reports${openReports ? ' · ' + openReports : ''}`, `بلاغات العملاء${openReports ? ' · ' + openReports : ''}`) }]} /></View>
    <Screen top={false} gap={10}>
      {hold ? <Banner tone="error" title={L(`Quality hold on ${hold.display_name}`, `إيقاف جودة على ${hold.display_name}`)}>{L(`No new listings until ${String(hold.paused_until).slice(0, 10)}. Compliance lifts it after the follow-up; existing orders are honoured or refunded by Bugsha.`, `لا عروض جديدة حتى ${String(hold.paused_until).slice(0, 10)}. يرفعه فريق الامتثال بعد المتابعة؛ الطلبات الحالية تُنفّذ أو تستردها بقشة.`)}</Banner> : null}
      {tab === 'flags' ? (fl.length === 0 ? <EmptyState icon="circle-check" title={L('No quality flags', 'لا تنبيهات جودة')} body={L('Flags come from customer reviews and cancellations for quality concern. Acknowledging one on time keeps your reliability score whole.', 'تأتي التنبيهات من تقييمات العملاء وإلغاءات الجودة. الإقرار بها في وقتها يحفظ درجة موثوقيتك.')} /> : fl.map((f) => <Card key={f.id}><View style={{ gap: 8 }}>
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><T weight={700} style={{ flex: 1 }}>{String(f.category).replace(/_/g, ' ')}</T><Badge tone={f.acknowledged_at ? 'fresh' : (tone(f.severity) as any)}>{f.acknowledged_at ? L('Acknowledged', 'تم الإقرار') : f.escalated_at ? L('Escalated', 'مُصعَّد') : f.severity}</Badge></View>
        <Caption>{`${f.store_name}${f.order_code ? ' · ' + f.order_code : ''} · ${String(f.source).replace(/_/g, ' ')} · ${when(f.created_at)}`}</Caption>
        {f.body ? <Pp>“{f.body}”</Pp> : null}
        {!f.acknowledged_at ? <Caption style={{ color: color.time }}>{L(`Acknowledge by ${when(f.ack_deadline)} — after that it escalates to ops.`, `أقرّ قبل ${when(f.ack_deadline)} — بعدها يُصعَّد للفريق.`)}</Caption> : <View style={{ padding: 10, backgroundColor: color.sunken, borderRadius: 8 }}><Caption>{L('Your finding and action', 'ما وجدته وما فعلته')}</Caption><T role="label">{f.acknowledgement_text}</T></View>}
        {!f.acknowledged_at ? (open === f.id ? <View style={{ gap: 8 }}><Input label={L('What you found', 'ما وجدته')} value={finding} onChangeText={setFinding} multiline /><Input label={L('What you changed', 'ما غيّرته')} value={action} onChangeText={setAction} multiline />
          <View style={{ flexDirection: 'row', gap: 8 }}><Button size="sm" disabled={finding.trim().length < 5 || action.trim().length < 5} loading={ack.isPending} onPress={() => ack.mutateAsync({ flagId: f.id, finding: finding.trim(), action: action.trim() }).then(() => { setOpen(null); setFinding(''); setAction(''); flags.refetch(); }).catch((e: RpcError) => setErr(errorMessage(e.code, locale)))}>{L('Acknowledge', 'إقرار')}</Button><Button size="sm" variant="ghost" onPress={() => setOpen(null)}>{L('Cancel', 'إلغاء')}</Button></View></View>
          : <Button size="sm" variant="secondary" onPress={() => setOpen(f.id)}>{L('Acknowledge with a finding', 'إقرار مع ما وجدته')}</Button>) : null}</View></Card>))
      : (dl.length === 0 ? <EmptyState icon="shield-check" title={L('No customer reports', 'لا بلاغات من العملاء')} body={L('Reports on your orders appear here. Ops decides the outcome; your statement is read first.', 'تظهر البلاغات على طلباتك هنا. الفريق يقرر النتيجة؛ ويُقرأ بيانك أولاً.')} /> : dl.map((d) => <Card key={d.id}><View style={{ gap: 8 }}>
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><Num weight={700}>{d.case_ref}</Num><T weight={600} style={{ flex: 1 }}>{String(d.category).replace(/_/g, ' ')}</T><Badge tone={d.resolved_at ? 'neutral' : (tone(d.severity) as any)}>{d.resolved_at ? L('Resolved', 'مُغلق') : d.severity}</Badge></View>
        <Caption>{`${d.store_name} · ${d.order_code ?? ''} · ${when(d.opened_at)}`}</Caption>
        {d.category === 'suspected_foodborne_illness' ? <Banner tone="error" title={L('Illness report — Compliance is handling it', 'بلاغ توعّك — فريق الامتثال يتولاه')}>{L('You are informed, never asked to triage. Keep the batch records for the date.', 'تُبلَّغ فقط، ولا يُطلب منك الفرز. احتفظ بسجلات الدفعة لذلك التاريخ.')}</Banner> : null}
        <Pp>“{d.consumer_statement}”</Pp>
        {d.partner_statement ? <View style={{ padding: 10, backgroundColor: color.sunken, borderRadius: 8 }}><Caption>{L('Your statement', 'بيانك')}</Caption><T role="label">{d.partner_statement}</T></View>
          : d.resolved_at ? null : open === d.id ? <View style={{ gap: 8 }}><Input value={finding} onChangeText={setFinding} multiline placeholder={L('What happened from your side — facts, not blame.', 'ما حدث من جهتك — وقائع لا لوم.')} style={{ minHeight: 70 }} />
            <View style={{ flexDirection: 'row', gap: 8 }}><Button size="sm" disabled={finding.trim().length < 10} loading={respond.isPending} onPress={() => respond.mutateAsync({ disputeId: d.id, statement: finding.trim() }).then(() => { setOpen(null); setFinding(''); disputes.refetch(); }).catch((e: RpcError) => setErr(errorMessage(e.code, locale)))}>{L('Send statement', 'إرسال البيان')}</Button><Button size="sm" variant="ghost" onPress={() => setOpen(null)}>{L('Cancel', 'إلغاء')}</Button></View></View>
          : <View style={{ gap: 4 }}>{d.partner_deadline ? <Caption style={{ color: color.time }}>{L(`Statement due by ${when(d.partner_deadline)}`, `البيان مطلوب قبل ${when(d.partner_deadline)}`)}</Caption> : null}<Button size="sm" variant="secondary" onPress={() => { setOpen(d.id); setFinding(''); }}>{L('Add your statement', 'أضف بيانك')}</Button></View>}
        {d.resolution ? <View style={{ padding: 10, backgroundColor: color.freshTint, borderRadius: 8 }}><Caption>{L('Outcome', 'النتيجة')}</Caption><T role="label">{d.resolution}</T></View> : null}</View></Card>))}
      {err ? <Banner tone="error" title={err} /> : null}
      <Eyebrow>{L('Reliability', 'الموثوقية')}</Eyebrow><Caption>{L(`Score ${partner.data?.reliability_score ?? '—'}. Cancellations after a sale, late hand-overs and unacknowledged flags lower it; it recovers over 90 days.`, `الدرجة ${partner.data?.reliability_score ?? '—'}. الإلغاء بعد البيع والتسليم المتأخر والتنبيهات غير المُقرّة تخفضها؛ وتتعافى خلال 90 يوماً.`)}</Caption>
    </Screen></View>;
}
