// Console · Schedules — weekly auto-publish per template with a publish lead; Ramadan-affected schedules pause
// during the suspension; pause/resume. app.upsert_schedule / schedules / pause_schedule.
import { useState } from 'react'; import { router } from 'expo-router'; import { View } from 'react-native';
import { usePauseSchedule, useSchedules, useTemplates, useUpsertSchedule, RpcError } from '@bugsha/api'; import { errorMessage } from '@bugsha/i18n';
import { AppBar, Badge, Banner, Button, Caption, Card, Chip, Chips, EmptyState, Eyebrow, Foot, Input, Num, Screen, Stepper, Switch, T, color } from '@bugsha/ui';
import { db } from '../../src/lib/supabase'; import { useSession } from '../../src/lib/session'; import { useStore } from '../../src/lib/store'; import { hhmm, useL } from '../../src/lib/ui';
const DAYS: Array<[string, string]> = [['Sun', 'أحد'], ['Mon', 'إثنين'], ['Tue', 'ثلاثاء'], ['Wed', 'أربعاء'], ['Thu', 'خميس'], ['Fri', 'جمعة'], ['Sat', 'سبت']];
export default function Schedules() {
  const s = useStore(); const { locale } = useSession(); const { L, ar } = useL(); const q = useSchedules(db, s.storeId); const tpl = useTemplates(db, s.partnerId) as any; const up = useUpsertSchedule(db); const pause = usePauseSchedule(db);
  const templates = ((tpl.data ?? []) as any[]).filter((t) => !t.store_id || t.store_id === s.storeId);
  const [editing, setEditing] = useState(false); const [f, setF] = useState({ template: '', days: [0, 1, 2, 3, 4] as number[], start: '21:00', end: '22:00', qty: 6, lead: '150', ramadan: false }); const [err, setErr] = useState<string | null>(null);
  const rows = (q.data ?? []) as any[]; const tname = (id: string) => { const t = templates.find((x) => x.id === id); return t ? (ar ? t.title_ar : t.title_en) : '—'; };
  const start = (t: any) => { setF({ template: t?.id ?? templates[0]?.id ?? '', days: [0, 1, 2, 3, 4], start: t ? hhmm(t.default_window_start) : '21:00', end: t ? hhmm(t.default_window_end) : '22:00', qty: t?.default_quantity ?? 6, lead: '150', ramadan: false }); setEditing(true); };
  const save = () => up.mutateAsync({ p_store: s.storeId, p_template: f.template, p_weekdays: f.days, p_local_start: f.start, p_local_end: f.end, p_quantity: f.qty, p_publish_lead_minutes: Number(f.lead) || 150, p_ramadan_affected: f.ramadan }).then(() => { setEditing(false); setErr(null); q.refetch(); }).catch((e: RpcError) => setErr(errorMessage(e.code, locale)));
  return <View style={{ flex: 1 }}><AppBar title={L('Schedules', 'الجداول')} sub={s.storeName} onBack={() => router.back()} /><Screen top={false} gap={12}>
    <Caption>{L(`Each schedule publishes its bag automatically, ${f.lead} minutes before the window, on the days you pick. Cancel a night from Listings.`, `كل جدول ينشر بقشته تلقائياً قبل الوقت بـ ${f.lead} دقيقة في الأيام التي تختارها. ألغِ ليلة من العروض.`)}</Caption>
    {!editing && rows.length === 0 ? <EmptyState icon="calendar" title={L('No schedules yet', 'لا جداول بعد')} body={L('Set one up and tonight publishes itself.', 'أنشئ واحداً وستُنشر الليلة تلقائياً.')} /> : null}
    {!editing ? rows.map((r) => { const paused = !!(r.paused_at ?? r.paused); return <Card key={r.id ?? r.schedule_id}><View style={{ gap: 8 }}>
      <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><T weight={700} style={{ flex: 1 }}>{tname(r.template_id)}</T>{paused ? <Badge tone="neutral">{L('Paused', 'متوقف')}</Badge> : <Badge tone="fresh">{L('On', 'يعمل')}</Badge>}</View>
      <View style={{ flexDirection: 'row', gap: 4, flexWrap: 'wrap' }}>{DAYS.map(([en, a], i) => <View key={i} style={{ paddingVertical: 2, paddingHorizontal: 7, borderRadius: 6, backgroundColor: (r.weekdays ?? []).includes(i) ? color.brandTint : color.sunken }}><T role="micro" color={(r.weekdays ?? []).includes(i) ? color.brand : color.textTertiary}>{ar ? a : en}</T></View>)}</View>
      <View style={{ flexDirection: 'row', gap: 12 }}><Num role="caption" color={color.textSecondary}>{`${hhmm(r.local_start)}–${hhmm(r.local_end)}`}</Num><Num role="caption" color={color.textSecondary}>{`${r.quantity} ${L('bags', 'بقش')}`}</Num>{r.ramadan_affected ? <Caption>{L('Pauses in Ramadan', 'يتوقف في رمضان')}</Caption> : null}</View>
      <View style={{ flexDirection: 'row', gap: 6 }}><Button size="sm" variant="secondary" onPress={() => { setF({ template: r.template_id, days: r.weekdays ?? [], start: hhmm(r.local_start), end: hhmm(r.local_end), qty: r.quantity, lead: String(r.publish_lead_minutes ?? 150), ramadan: !!r.ramadan_affected }); setEditing(true); }}>{L('Edit', 'تعديل')}</Button>{!paused ? <Button size="sm" variant="ghost" onPress={() => pause.mutateAsync(r.id ?? r.schedule_id).then(() => q.refetch())}>{L('Pause', 'إيقاف')}</Button> : null}</View></View></Card>; }) : null}
    {editing ? <Card><View style={{ gap: 12 }}>
      <Eyebrow>{L('Bag', 'البقشة')}</Eyebrow><Chips>{templates.map((t) => <Chip key={t.id} selected={f.template === t.id} onPress={() => setF({ ...f, template: t.id, start: hhmm(t.default_window_start), end: hhmm(t.default_window_end), qty: t.default_quantity ?? f.qty })}>{ar ? t.title_ar : t.title_en}</Chip>)}</Chips>
      {templates.length === 0 ? <Banner tone="info" title={L('Create a template first', 'أنشئ قالباً أولاً')} action={L('Templates', 'القوالب')} onAction={() => router.push('/templates/edit')} /> : null}
      <Eyebrow>{L('Days', 'الأيام')}</Eyebrow><Chips>{DAYS.map(([en, a], i) => <Chip key={i} selected={f.days.includes(i)} onPress={() => setF({ ...f, days: f.days.includes(i) ? f.days.filter((d) => d !== i) : [...f.days, i].sort() })}>{ar ? a : en}</Chip>)}</Chips>
      <View style={{ flexDirection: 'row', gap: 8 }}><Input containerStyle={{ flex: 1 }} label={L('Window from', 'من')} value={f.start} onChangeText={(v) => setF({ ...f, start: v })} placeholder="21:00" /><Input containerStyle={{ flex: 1 }} label={L('To', 'إلى')} value={f.end} onChangeText={(v) => setF({ ...f, end: v })} placeholder="22:00" /></View>
      <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><T role="label" weight={600}>{L('Bags each night', 'بقش كل ليلة')}</T><Stepper value={f.qty} min={1} max={40} onChange={(v) => setF({ ...f, qty: v })} /></View>
      <Input label={L('Publish this many minutes before the window', 'انشر قبل الوقت بهذه الدقائق')} value={f.lead} onChangeText={(v) => setF({ ...f, lead: v.replace(/\D/g, '') })} keyboardType="number-pad" hint={L('150 gives customers time to plan; the bag still counts as tonight.', '150 تمنح العملاء وقتاً للتخطيط؛ وتبقى البقشة لليلة.')} />
      <Switch checked={f.ramadan} onChange={(v) => setF({ ...f, ramadan: v })} label={L('Pause during Ramadan — suggest an iftar/suhoor pair instead', 'إيقاف في رمضان — اقترح زوج إفطار/سحور بدلاً منه')} />
      {err ? <Banner tone="error" title={err} /> : null}</View></Card> : null}</Screen>
    <Foot>{editing ? <View style={{ flexDirection: 'row', gap: 8 }}><Button variant="ghost" style={{ flex: 1 }} onPress={() => setEditing(false)}>{L('Cancel', 'إلغاء')}</Button><Button style={{ flex: 2 }} size="lg" loading={up.isPending} disabled={!f.template || f.days.length === 0} onPress={save}>{L('Save schedule', 'حفظ الجدول')}</Button></View> : <Button size="lg" fullWidth iconStart="plus" disabled={templates.length === 0} onPress={() => start(templates[0])}>{L('New schedule', 'جدول جديد')}</Button>}</Foot></View>;
}
