// §5 Staff — roles, invite by email, revoke (immediate; queued offline redemptions stay attributed).
import { useState } from 'react'; import { router } from 'expo-router'; import { View } from 'react-native';
import { useInviteStaff, useRevokeStaff, useSetActiveShift, useStaff, RpcError } from '@bugsha/api'; import { errorMessage } from '@bugsha/i18n';
import { AppBar, Badge, Banner, Button, Caption, Chip, Chips, Eyebrow, Input, ListRow, Screen, T } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useSession } from '../../src/lib/session'; import { useStore } from '../../src/lib/store'; import { useL } from '../../src/lib/ui';
export default function Staff() { const s = useStore(); const { locale } = useSession(); const { L } = useL(); const q = useStaff(db, s.partnerId); const inv = useInviteStaff(db); const rev = useRevokeStaff(db); const shift = useSetActiveShift(db); const [onShift, setOnShift] = useState<string | null>(null); const [email, setEmail] = useState(''); const [role, setRole] = useState('staff'); const [err, setErr] = useState<string | null>(null);
  return <View style={{ flex: 1 }}><AppBar title={L('Staff', 'الفريق')} sub={s.tradingName} onBack={() => router.back()} /><Screen top={false} gap={12}>
    <Eyebrow>{L('Invite', 'دعوة')}</Eyebrow><Input label={L('Email', 'البريد الإلكتروني')} value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" hint={L('They must have signed in to Bugsha Partner once with this email.', 'يجب أن يكونوا قد دخلوا إلى تطبيق الشريك مرة بهذا البريد.')} />
    <Chips>{[['staff', 'Staff', 'موظف'], ['manager', 'Manager', 'مدير'], ['accountant', 'Accountant', 'محاسب']].map(([k, en, a]) => <Chip key={k} selected={role === k} onPress={() => setRole(k!)}>{L(en!, a!)}</Chip>)}</Chips>
    <Button fullWidth iconStart="plus" loading={inv.isPending} disabled={!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)} onPress={() => inv.mutateAsync({ email, partnerId: s.partnerId, storeId: role === 'accountant' ? null : s.storeId, role }).then(() => { setEmail(''); setErr(null); q.refetch(); }).catch((e: RpcError) => setErr(errorMessage(e.code, locale)))}>{L('Invite', 'دعوة')}</Button>
    {err ? <Banner tone="error" title={err} /> : null}
    <Eyebrow>{L('Team', 'الفريق')}</Eyebrow><View>{((q.data ?? []) as any[]).map((m) => <ListRow key={m.assignment_id} icon="user" label={<T role="label" weight={600}>{m.full_name || m.email}</T>} sub={`${m.store_name ?? L('All branches', 'كل الفروع')}${m.claimed ? '' : ' · ' + L('invited', 'مدعو')}`} value={<View style={{ flexDirection: 'row', gap: 8, alignItems: 'center' }}><Badge tone={m.role === 'owner' ? 'brand' : 'neutral'}>{m.role}</Badge>{m.claimed && (m.store_id === s.storeId || m.partner_wide) ? <Button size="sm" variant={onShift === m.user_id ? 'primary' : 'secondary'} loading={shift.isPending && onShift !== m.user_id} onPress={() => shift.mutateAsync({ storeId: s.storeId, staffUserId: m.user_id }).then(() => setOnShift(m.user_id)).catch((e: RpcError) => setErr(errorMessage(e.code, locale)))}>{onShift === m.user_id ? L('On shift', 'في الوردية') : L('Set on shift', 'بدء الوردية')}</Button> : null}{m.role !== 'owner' ? <Button size="sm" variant="ghost" onPress={() => rev.mutateAsync(m.assignment_id).then(() => q.refetch())}>{L('Revoke', 'إلغاء')}</Button> : null}</View>} />)}</View>
    <Caption>{L('The person on shift is who redemptions are attributed to when the counter tablet is shared.', 'الشخص في الوردية هو من تُنسب إليه الاستلامات عند مشاركة جهاز الكاشير.')}</Caption>
    <Caption>{L('Revoking is immediate. Redemptions they recorded stay attributed to them.', 'الإلغاء فوري. تبقى الاستلامات التي سجّلوها باسمهم.')}</Caption></Screen></View>; }
