// S-C-042 — never a single tap; a pending pickup blocks it outright. Scheduled deletion shows its date and can be undone.
import { useState } from 'react'; import { router } from 'expo-router'; import { View } from 'react-native';
import { useCancelDeletion, useMyOrders, useProfile, useRequestDeletion, useWallet } from '@bugsha/api';
import { AppBar, Banner, Button, Card, Dialog, Line, Num, Pp, Screen, T } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useSession } from '../../src/lib/session'; import { money, useL } from '../../src/lib/ui';
export default function Del() { const { market } = useSession(); const { L } = useL(); const orders = useMyOrders(db); const wallet = useWallet(db) as any; const profile = useProfile(db) as any; const del = useRequestDeletion(db); const undo = useCancelDeletion(db); const [confirm, setConfirm] = useState(false); const [done, setDone] = useState<any>(null);
  const active = ((orders.data ?? []) as any[]).filter((o) => ['held', 'reserved'].includes(o.status)).length;
  const scheduled = done?.scheduled_for ?? profile.data?.deletion_scheduled_for ?? null;
  return <View style={{ flex: 1 }}><AppBar title={L('Delete account', 'حذف الحساب')} onBack={() => router.back()} /><Screen top={false} pad={16} gap={12}>
    {active > 0 && !scheduled ? <Banner tone="error" title={L(active === 1 ? 'You have an order to collect' : `You have ${active} orders to collect`, active === 1 ? 'لديك طلب للاستلام' : `لديك ${active} طلبات للاستلام`)}>{L('Collect or cancel it before deleting. The store is holding food for you.', 'استلمه أو ألغِه قبل الحذف. المتجر يحتفظ لك بطعام.')}</Banner> : null}
    {scheduled ? <Banner tone="info" title={L('Deletion scheduled', 'تمت جدولة الحذف')} action={L('Undo', 'تراجع')} onAction={() => undo.mutateAsync().then(() => { setDone(null); profile.refetch(); })}>{L(`Your identity details are erased on ${String(scheduled).slice(0, 10)}. Order records are kept for the legal retention period. Sign in before then, or tap Undo, to keep the account.`, `تُحذف بياناتك في ${String(scheduled).slice(0, 10)}. تُحفظ سجلات الطلبات للمدة القانونية. سجّل الدخول قبلها أو اضغط تراجع للإبقاء على الحساب.`)}</Banner> : null}
    <Card><View style={{ gap: 8 }}><T weight={600}>{L('What deletion does', 'ماذا يحدث عند الحذف')}</T><Pp>{L('Your profile, saved stores and payment methods are removed within 30 days. Order and payment records are kept for the period tax and consumer law require, then deleted. Wallet credit is forfeited.', 'يُحذف ملفك ومتاجرك المحفوظة وطرق الدفع خلال 30 يوماً. تُحفظ سجلات الطلبات والدفع للمدة التي يفرضها القانون ثم تُحذف. يسقط رصيد المحفظة.')}</Pp><Line k={L('Wallet credit lost', 'الرصيد المفقود')} v={<Num weight={700}>{money(wallet.data?.balance_minor ?? 0, market)}</Num>} strong /></View></Card>
    <Button variant="secondary" fullWidth iconStart="bell" onPress={() => router.push('/account/notifications')}>{L('Just pause notifications instead', 'إيقاف الإشعارات فقط بدلاً من ذلك')}</Button>
    <Button variant="danger" fullWidth disabled={active > 0 || !!scheduled} onPress={() => setConfirm(true)}>{L('Delete my account', 'حذف حسابي')}</Button></Screen>
    <Dialog open={confirm} title={L('Delete your account?', 'حذف حسابك؟')} body={L('This starts a 30-day clock. You can sign back in before then to cancel.', 'يبدأ هذا عدّاً لمدة 30 يوماً. يمكنك الدخول قبلها للإلغاء.')} confirmLabel={L('Delete', 'حذف')} cancelLabel={L('Keep my account', 'إبقاء حسابي')} tone="danger" onCancel={() => setConfirm(false)} onConfirm={() => { setConfirm(false); del.mutateAsync().then((r) => { setDone(r); profile.refetch(); }).catch(() => {}); }} /></View>; }
