// S-C-015 — preferences filter the feed but never promise anything. The allergen acknowledgement is a hard gate.
import { useEffect, useState } from 'react'; import { router } from 'expo-router'; import { Pressable, View } from 'react-native';
import { useProfile, useSetDietary } from '@bugsha/api';
import { AppBar, Banner, Button, Chip, Chips, Eyebrow, Foot, Icon, Screen, T, color } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useL } from '../../src/lib/ui';
const FLAGS: Array<[string, string, string]> = [['vegetarian', 'Vegetarian', 'نباتي'], ['vegan', 'Vegan', 'نباتي صرف'], ['no_pork', 'No pork', 'بدون لحم خنزير'], ['no_alcohol', 'No alcohol', 'بدون كحول'], ['gluten_free', 'Gluten-free', 'خالٍ من الغلوتين'], ['nut_allergy', 'Nut allergy', 'حساسية المكسرات'], ['dairy_free', 'Dairy-free', 'خالٍ من الألبان'], ['halal', 'Halal only', 'حلال فقط']];
export default function Dietary() { const { L } = useL(); const q = useProfile(db); const m = useSetDietary(db); const [sel, setSel] = useState<string[]>([]); const [ack, setAck] = useState(false);
  useEffect(() => { if (q.data) { setSel(q.data.dietary_flags ?? []); setAck(!!q.data.allergen_ack); } }, [q.data]);
  const allergy = sel.some((f) => f.endsWith('_allergy') || f === 'gluten_free' || f === 'dairy_free');
  return <View style={{ flex: 1 }}><AppBar title={L('Preferences', 'التفضيلات')} onBack={() => router.back()} /><Screen top={false} pad={16} gap={12}>
    <Eyebrow>{L('Dietary', 'غذائية')}</Eyebrow><Chips>{FLAGS.map(([k, en, a]) => <Chip key={k} selected={sel.includes(k)} onPress={() => setSel(sel.includes(k) ? sel.filter((x) => x !== k) : [...sel, k])}>{L(en, a)}</Chip>)}</Chips>
    <Banner tone="error" title={L('Read before continuing', 'اقرأ قبل المتابعة')}>{L('Bag contents are chosen by the store and can change without notice. Allergen information comes from the store, not from Bugsha. We cannot guarantee any bag is free of an allergen.', 'محتويات البقشة يختارها المتجر وقد تتغير دون إشعار. معلومات مسببات الحساسية من المتجر وليست من بقشة. لا يمكننا ضمان خلو أي بقشة من مسبب حساسية.')}</Banner>
    <Pressable onPress={() => setAck(!ack)} accessibilityRole="checkbox" accessibilityState={{ checked: ack }} style={{ flexDirection: 'row', gap: 10, alignItems: 'flex-start' }}><View style={{ width: 22, height: 22, borderRadius: 6, backgroundColor: ack ? color.brand : color.raised, borderWidth: ack ? 0 : 1.5, borderColor: color.border, alignItems: 'center', justifyContent: 'center' }}>{ack ? <Icon name="check" size={14} color="#fff" /> : null}</View><T role="label" style={{ flex: 1 }}>{L('I understand and will check with the store at pickup.', 'أفهم ذلك وسأتحقق من المتجر عند الاستلام.')}</T></Pressable></Screen>
    <Foot><Button size="lg" fullWidth disabled={allergy && !ack} loading={m.isPending} onPress={() => m.mutateAsync({ flags: sel, ack }).then(() => router.back())}>{L('Save preferences', 'حفظ التفضيلات')}</Button></Foot></View>; }
