// S-C-064 — Restricted: the reason, the count, the end date and the appeal route on one screen.
import { router } from 'expo-router'; import { Linking, View } from 'react-native';
import { useProfile } from '@bugsha/api'; import { AppBar, Banner, Button, Card, Caption, Icon, Line, Num, Pp, Screen, T, color } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useL } from '../../src/lib/ui';
export default function Restricted() { const { L } = useL(); const q = useProfile(db) as any; const p = q.data ?? {}; const until = p.restricted_until ? new Date(p.restricted_until) : null;
  const reason = p.restriction_reason_code === 'suspected_abuse' ? [L('Unusual activity on the account', 'نشاط غير معتاد على الحساب'), L('Our team flagged patterns that look like abuse of reservations. If that is wrong, tell us — a person reads every appeal.', 'رصد فريقنا أنماطاً تشبه إساءة استخدام الحجز. إن كان ذلك خطأ أخبرنا — يقرأ شخص كل استئناف.')] : [L('Missed pickups', 'حجوزات فائتة'), L('Three bags reserved and not collected in 90 days pause reservations for 30 days. Stores prepare and hold each bag, so a missed one is food thrown away.', 'ثلاث بقش محجوزة وغير مستلمة خلال 90 يوماً توقف الحجز 30 يوماً. المتاجر تجهّز كل بقشة وتحتفظ بها، فالفائتة طعام يُرمى.')];
  return <View style={{ flex: 1 }}><AppBar title={L('Reservations paused', 'الحجز متوقف')} onBack={() => router.back()} /><Screen top={false} pad={16} gap={14}>
    {!until ? <Banner tone="fresh" title={L('Your account is not restricted', 'حسابك غير مقيّد')}>{L('You can reserve as usual.', 'يمكنك الحجز كالمعتاد.')}</Banner> : <>
      <View style={{ flexDirection: 'row', gap: 12, alignItems: 'center' }}><View style={{ width: 52, height: 52, borderRadius: 16, backgroundColor: color.errorTint, alignItems: 'center', justifyContent: 'center' }}><Icon name="triangle-alert" size={26} color={color.error} /></View><View style={{ flex: 1 }}><T role="titleLg" weight={700}>{reason[0]}</T></View></View>
      <Pp>{reason[1]}</Pp>
      <Card><View style={{ gap: 6 }}><Line k={L('Missed in 90 days', 'فائتة خلال 90 يوماً')} v={<Num weight={700}>{String(p.no_show_count_90d ?? 0)}</Num>} /><Line k={L('Reservations resume', 'يعود الحجز')} v={<Num weight={700}>{until.toLocaleDateString('en-GB', { day: 'numeric', month: 'long' })}</Num>} strong /></View></Card>
      <Caption>{L('Browsing, saved stores and your wallet keep working. Existing reservations are honoured.', 'التصفّح والمتاجر المحفوظة ومحفظتك تعمل. الحجوزات الحالية تُنفّذ.')}</Caption>
      <Button fullWidth iconStart="mail" onPress={() => Linking.openURL(`mailto:hello@bugsha.app?subject=${encodeURIComponent('Appeal a reservation pause')}`)}>{L('Appeal by email', 'استئناف عبر البريد')}</Button></>}</Screen></View>; }
