// S-C-057 — food safety: named regulator, named holding rule, named reporting route.
import { router } from 'expo-router'; import { View } from 'react-native';
import { AppBar, Button, Card, Icon, Pp, Screen, T, color } from '@bugsha/ui'; import { useSession } from '../../src/lib/session'; import { regulator, useL } from '../../src/lib/ui';
export default function Safety() { const { market } = useSession(); const { L, ar } = useL(); const reg = regulator(market, ar);
  const rows: Array<[string, string, string]> = [['store', L('Licensed businesses only', 'منشآت مرخّصة فقط'), L(`Partners hold a valid food licence and are inspected by ${reg}.`, `الشركاء يحملون رخصة غذائية سارية ويخضعون لتفتيش ${reg}.`)], ['clock', L('Windows respect holding times', 'الأوقات تحترم مدد الحفظ'), L('Pickup windows are set so hot food is collected within safe holding limits, not left out to the end of shift.', 'تُحدد أوقات الاستلام بحيث يُستلم الطعام الساخن ضمن المدد الآمنة، لا أن يُترك حتى نهاية الوردية.')], ['package', L('Take it home cold or eat it soon', 'برّده أو تناوله قريباً'), L('Refrigerate within two hours of collection. Bakery keeps a day and freezes well.', 'برّده خلال ساعتين من الاستلام. المخبوزات تبقى يوماً وتتحمل التجميد.')], ['triangle-alert', L("Tell us fast if something's wrong", 'أخبرنا فوراً إن حدث خطأ'), L('Safety reports are answered within the hour and logged for the regulator.', 'بلاغات السلامة يُرد عليها خلال ساعة وتُسجّل للجهة الرقابية.')]];
  return <View style={{ flex: 1 }}><AppBar title={L('Food safety', 'سلامة الغذاء')} onBack={() => router.back()} /><Screen top={false} pad={16} gap={14}>
    <View style={{ gap: 6 }}><T role="titleLg" weight={700}>{L('Surplus. Not expired.', 'فائض. وليس منتهي الصلاحية.')}</T><Pp>{L('Every bag holds food the store could have sold at full price the same day, and simply didn\'t. Nothing past its date may be listed — that is a condition of being on Bugsha.', 'كل بقشة تحتوي طعاماً كان بإمكان المتجر بيعه بسعره الكامل في اليوم نفسه ولم يُبع. لا يجوز عرض أي منتج تجاوز تاريخه — هذا شرط للانضمام إلى بقشة.')}</Pp></View>
    <Card><View style={{ gap: 10 }}>{rows.map(([i, t, b]) => <View key={t} style={{ flexDirection: 'row', gap: 10 }}><Icon name={i} size={17} color={color.brand} /><View style={{ flex: 1 }}><T role="label" weight={600}>{t}</T><Pp style={{ fontSize: 12.5, lineHeight: 18 }}>{b}</Pp></View></View>)}</View></Card>
    <Button variant="secondary" fullWidth iconStart="triangle-alert" onPress={() => router.navigate('/(tabs)/orders')}>{L('Report a safety concern from an order', 'الإبلاغ عن مخاوف سلامة من طلب')}</Button></Screen></View>; }
