// §2.5 Contract — commission and terms; acceptance records timestamp, IP, device and document hash.
import { router } from 'expo-router'; import { View } from 'react-native';
import { useAcceptContract, usePartner } from '@bugsha/api'; import { AppBar, Banner, Button, Card, Caption, Foot, Line, Num, Pp, Screen, T } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useStore } from '../../src/lib/store'; import { money, useL } from '../../src/lib/ui';
export default function Contract() { const s = useStore(); const { L } = useL(); const p = usePartner(db, s.partnerId) as any; const acc = useAcceptContract(db); const c = p.data?.contract;
  return <View style={{ flex: 1 }}><AppBar title={L('Contract', 'العقد')} onBack={() => router.back()} /><Screen top={false} gap={12}>{!c ? <Banner tone="info" title={L('No contract issued yet', 'لم يُصدر عقد بعد')}>{L('Ops issues it after your documents are reviewed.', 'يصدره فريق العمليات بعد مراجعة وثائقك.')}</Banner> : <>
    <Card><View style={{ gap: 6 }}><Line k={L('Commission', 'العمولة')} v={<Num weight={700}>{`${c.commission_bp / 100}%`}</Num>} strong /><Line k={L('Payout', 'الدفعات')} v={`${c.payout_cadence}`} /><Line k={L('Minimum payout', 'الحد الأدنى للدفعة')} v={<Num role="label">{money(c.payout_min_minor, s.market)}</Num>} /><Line k={L('Cash commission', 'عمولة النقد')} v={c.cash_settlement_mode === 'invoice' ? L('Invoiced monthly', 'تُفوتر شهرياً') : L('Netted', 'تُخصم')} /><Line k={L('Version', 'الإصدار')} v={<Num role="label">{String(c.version)}</Num>} /></View></Card>
    <Pp>{L('Commission is charged on each bag sold and deducted at payout. No-shows: you keep the revenue. Refunds for a cancelled listing are charged to you. Card fees and chargebacks are borne by Bugsha. Nothing past its date may be listed.', 'تُحسب العمولة على كل بقشة تُباع وتُخصم عند الدفع. عدم الحضور: تحتفظ بالمبلغ. استردادات العرض الملغى تُحمّل عليك. رسوم البطاقات والمنازعات تتحملها بقشة. لا يجوز عرض أي منتج تجاوز تاريخه.')}</Pp>
    {c.accepted_at ? <Banner tone="fresh" title={L(`Accepted ${String(c.accepted_at).slice(0, 10)}`, `مقبول ${String(c.accepted_at).slice(0, 10)}`)} /> : null}</>}</Screen>
    {c && !c.accepted_at ? <Foot><Button size="lg" fullWidth loading={acc.isPending} onPress={() => acc.mutateAsync({ contractId: c.id, hash: `v${c.version}-${c.commission_bp}` }).then(() => p.refetch())}>{L('Accept the contract', 'قبول العقد')}</Button><Caption align="center">{L('Recorded with time, device and document version.', 'يُسجّل مع الوقت والجهاز وإصدار الوثيقة.')}</Caption></Foot> : null}</View>; }
