// §2.4 Verification — the market's document set, status per document, reason on rejection, re-upload.
import { useState } from 'react'; import { router } from 'expo-router'; import { View } from 'react-native'; import * as DocumentPicker from 'expo-document-picker';
import { useDocuments, useUploadDocument, RpcError } from '@bugsha/api'; import { errorMessage } from '@bugsha/i18n';
import { AppBar, Badge, Banner, Button, Caption, Card, Screen, T } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useSession } from '../../src/lib/session'; import { useStore } from '../../src/lib/store'; import { useL } from '../../src/lib/ui';
const LABEL: Record<string, [string, string]> = { moci_licence: ['MOCI licence', 'رخصة وزارة التجارة'], food_permit: ['Food permit (per branch)', 'تصريح غذائي (لكل فرع)'], civil_id: ['Civil ID of signatory', 'البطاقة المدنية للمفوّض'], signatory_authorisation: ['Signatory authorisation', 'تفويض التوقيع'], bank_iban: ['Bank IBAN letter', 'شهادة الآيبان'], commercial_register: ['Commercial register', 'السجل التجاري'], tax_card: ['Tax card', 'البطاقة الضريبية'], health_licence: ['Health licence (per branch)', 'رخصة صحية (لكل فرع)'], national_id: ['National ID of signatory', 'بطاقة الرقم القومي'] };
export default function Docs() { const s = useStore(); const { locale } = useSession(); const { L } = useL(); const q = useDocuments(db, s.partnerId); const up = useUploadDocument(db); const [err, setErr] = useState<string | null>(null);
  async function pick(docType: string, perStore: boolean) { const r = await DocumentPicker.getDocumentAsync({ type: ['application/pdf', 'image/*'] }); if (r.canceled || !r.assets?.[0]) return; const a = r.assets[0]; const path = `${s.partnerId}/${docType}/${Date.now()}-${a.name}`; const blob = await (await fetch(a.uri)).blob(); const { error } = await db.storage.from('documents').upload(path, blob, { contentType: a.mimeType ?? 'application/octet-stream' }); if (error) return setErr(error.message); up.mutateAsync({ partnerId: s.partnerId, docType, storagePath: path, storeId: perStore ? s.storeId : null }).then(() => q.refetch()).catch((e: RpcError) => setErr(errorMessage(e.code, locale))); }
  return <View style={{ flex: 1 }}><AppBar title={L('Documents', 'الوثائق')} onBack={() => router.back()} /><Screen top={false} gap={10}>
    {((q.data ?? []) as any[]).map((d) => { const lab: [string, string] = [d.label_en ?? LABEL[d.doc_type]?.[0] ?? d.doc_type, d.label_ar ?? LABEL[d.doc_type]?.[1] ?? d.doc_type]; const tone = d.status === 'approved' ? 'fresh' : d.status === 'rejected' ? 'error' : d.status === 'pending' ? 'time' : 'neutral'; return <Card key={d.doc_type}><View style={{ gap: 8 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><T weight={600} style={{ flex: 1 }}>{L(lab[0], lab[1])}</T><Badge tone={tone as any}>{d.status ?? L('Missing', 'مفقود')}</Badge></View>
      {d.expires_on ? <Caption>{L(`Expires ${d.expires_on}`, `تنتهي ${d.expires_on}`)}</Caption> : null}{d.status === 'rejected' ? <Banner tone="error" title={L('Rejected', 'مرفوض')}>{d.rejection_reason}</Banner> : null}
      {d.status !== 'approved' ? <Button variant="secondary" size="sm" iconStart="camera" loading={up.isPending} onPress={() => pick(d.doc_type, d.per_store)}>{d.status ? L('Re-upload', 'إعادة الرفع') : L('Upload', 'رفع')}</Button> : null}</View></Card>; })}
    {err ? <Banner tone="error" title={err} /> : null}<Caption>{L('PDF or photo. Reviewed within one working day.', 'PDF أو صورة. تُراجع خلال يوم عمل.')}</Caption></Screen></View>; }
