// §2.6 Hours — split shifts and a separate Ramadan schedule.
import { useState } from 'react'; import { router } from 'expo-router'; import { View } from 'react-native';
import { useSetHours } from '@bugsha/api'; import { AppBar, Banner, Button, Card, Foot, Input, Screen, SegmentedControl, Switch, T } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useStore } from '../../src/lib/store'; import { useL } from '../../src/lib/ui';
const DAYS: Array<[string, string]> = [['Sun', 'الأحد'], ['Mon', 'الإثنين'], ['Tue', 'الثلاثاء'], ['Wed', 'الأربعاء'], ['Thu', 'الخميس'], ['Fri', 'الجمعة'], ['Sat', 'السبت']];
export default function Hours() { const s = useStore(); const { L } = useL(); const m = useSetHours(db); const [ram, setRam] = useState<'regular' | 'ramadan'>('regular'); const [rows, setRows] = useState(DAYS.map(() => ({ open: true, o1: '08:00', c1: '14:00', split: true, o2: '17:00', c2: '23:00' }))); const [ok, setOk] = useState(false);
  const upd = (i: number, p: Partial<(typeof rows)[number]>) => setRows(rows.map((r, k) => (k === i ? { ...r, ...p } : r)));
  return <View style={{ flex: 1 }}><AppBar title={L('Opening hours', 'ساعات العمل')} sub={s.storeName} onBack={() => router.back()} /><View style={{ paddingHorizontal: 14, paddingTop: 10 }}><SegmentedControl value={ram} onChange={setRam} options={[{ value: 'regular', label: L('Regular', 'عادي') }, { value: 'ramadan', label: L('Ramadan', 'رمضان') }]} /></View>
    <Screen top={false} gap={10}>{rows.map((r, i) => <Card key={i}><View style={{ gap: 8 }}><View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><T weight={600}>{L(DAYS[i]![0], DAYS[i]![1])}</T><Switch checked={r.open} onChange={(v) => upd(i, { open: v })} label={L('Open', 'مفتوح')} /></View>
      {r.open ? <><View style={{ flexDirection: 'row', gap: 8 }}><Input containerStyle={{ flex: 1 }} label={L('Opens', 'يفتح')} value={r.o1} onChangeText={(v) => upd(i, { o1: v })} /><Input containerStyle={{ flex: 1 }} label={L('Closes', 'يغلق')} value={r.c1} onChangeText={(v) => upd(i, { c1: v })} /></View>
        <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><T role="label" color="#6B6579">{L('Second shift', 'وردية ثانية')}</T><Switch checked={r.split} onChange={(v) => upd(i, { split: v })} label={L('Split shift', 'وردية مقسمة')} /></View>
        {r.split ? <View style={{ flexDirection: 'row', gap: 8 }}><Input containerStyle={{ flex: 1 }} label={L('Opens', 'يفتح')} value={r.o2} onChangeText={(v) => upd(i, { o2: v })} /><Input containerStyle={{ flex: 1 }} label={L('Closes', 'يغلق')} value={r.c2} onChangeText={(v) => upd(i, { c2: v })} /></View> : null}</> : null}</View></Card>)}
    {ok ? <Banner tone="fresh" title={L('Saved', 'تم الحفظ')} /> : null}</Screen>
    <Foot><Button size="lg" fullWidth loading={m.isPending} onPress={() => m.mutateAsync({ storeId: s.storeId, ramadan: ram === 'ramadan', rows: rows.flatMap((r, i) => r.open ? [{ weekday: i, opens: r.o1, closes: r.c1, shift_index: 0 }, ...(r.split ? [{ weekday: i, opens: r.o2, closes: r.c2, shift_index: 1 }] : [])] : []) }).then(() => setOk(true))}>{L('Save hours', 'حفظ الساعات')}</Button></Foot></View>; }
