// §2.2 Setup checklist — documents, contract, store, hours, first listing.
import { router } from 'expo-router'; import { View } from 'react-native';
import { useDocuments, usePartner } from '@bugsha/api'; import { AppBar, Badge, Banner, Caption, ListRow, Screen, T } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useStore } from '../../src/lib/store'; import { useL } from '../../src/lib/ui';
export default function Setup() { const s = useStore(); const { L } = useL(); const p = usePartner(db, s.partnerId) as any; const docs = useDocuments(db, s.partnerId); const d = p.data; const missing = ((docs.data ?? []) as any[]).filter((x) => x.status !== 'approved').length;
  const st: Record<string, string> = { applied: L('Applied', 'مقدَّم'), documents_pending: L('Documents pending', 'الوثائق مطلوبة'), under_review: L('Under review', 'قيد المراجعة'), contract_signed: L('Contract signed', 'العقد موقّع'), store_setup: L('Store setup', 'إعداد المتجر'), active: L('Active', 'نشط'), rejected: L('Rejected', 'مرفوض'), suspended: L('Suspended', 'موقوف') };
  return <View style={{ flex: 1 }}><AppBar title={L('Setup', 'الإعداد')} sub={d?.trading_name} onBack={() => router.back()} /><Screen top={false} gap={10}>
    {d ? <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><T weight={600}>{L('Status', 'الحالة')}</T><Badge tone={d.onboarding_status === 'active' ? 'fresh' : d.onboarding_status === 'rejected' ? 'error' : 'time'}>{st[d.onboarding_status] ?? d.onboarding_status}</Badge></View> : null}
    {d?.onboarding_status === 'rejected' ? <Banner tone="error" title={L('Application not accepted', 'لم يُقبل الطلب')}>{L('Support has the reason on file. Reapplying is possible after 90 days.', 'لدى الدعم سبب الرفض. يمكن إعادة التقديم بعد 90 يوماً.')}</Banner> : null}
    <ListRow icon="file-text" label={L('Documents', 'الوثائق')} sub={missing ? L(`${missing} to upload or renew`, `${missing} للرفع أو التجديد`) : L('All approved', 'كلها معتمدة')} chevron onPress={() => router.push('/onboarding/documents')} />
    <ListRow icon="file-text" label={L('Contract', 'العقد')} sub={d?.contract?.accepted_at ? L(`Accepted · ${d.contract.commission_bp / 100}% commission`, `مقبول · عمولة ${d.contract.commission_bp / 100}%`) : L('Read and accept', 'اقرأ ووافق')} chevron onPress={() => router.push('/onboarding/contract')} />
    <ListRow icon="store" label={L('Store & pickup point', 'المتجر ونقطة الاستلام')} sub={(d?.stores ?? []).length ? L(`${d.stores.length} branch`, `${d.stores.length} فرع`) : L('Add your first branch', 'أضف فرعك الأول')} chevron onPress={() => router.push('/onboarding/store')} />
    <ListRow icon="clock" label={L('Opening hours', 'ساعات العمل')} chevron onPress={() => router.push('/onboarding/hours')} />
    <ListRow icon="package" label={L('First listing', 'أول عرض')} sub={L('Publish once documents are approved', 'انشر بعد اعتماد الوثائق')} chevron onPress={() => router.push('/listing/publish')} />
    <Caption>{L('Listings stop the day a required document lapses. Existing orders are always honoured.', 'يتوقف النشر يوم انتهاء وثيقة مطلوبة. الطلبات الحالية تُنفّذ دائماً.')}</Caption></Screen></View>; }
