// P-010 Status hub — one card per onboarding_status, the seven steps, and the single next action.
// lead → applied → documents_pending → under_review → approved → contract_pending → contract_signed → store_setup → first_listing_pending → active | rejected | suspended
import { router } from 'expo-router'; import { View } from 'react-native';
import { useDocuments, usePartner } from '@bugsha/api'; import { AppBar, Badge, Banner, Button, Caption, Card, Icon, ListRow, Num, Screen, T, color } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useStore } from '../../src/lib/store'; import { useL } from '../../src/lib/ui';
const STEPS: Array<[string, string]> = [['Applied', 'تقديم الطلب'], ['Documents', 'الوثائق'], ['Review', 'المراجعة'], ['Contract', 'العقد'], ['Branch & hours', 'الفرع والساعات'], ['First listing', 'أول عرض'], ['Live', 'نشط']];
const STEP_OF: Record<string, number> = { lead: 0, applied: 1, documents_pending: 1, under_review: 2, approved: 3, contract_pending: 3, contract_signed: 4, store_setup: 4, first_listing_pending: 5, active: 6 };
export default function Setup() { const s = useStore(); const { L, ar } = useL(); const p = usePartner(db, s.partnerId) as any; const docs = useDocuments(db, s.partnerId); const d = p.data;
  const docRows = (docs.data ?? []) as any[]; const missing = docRows.filter((x) => x.status !== 'approved').length; const rejected = docRows.filter((x) => x.status === 'rejected').length;
  const status: string = d?.onboarding_status ?? 'applied'; const step = STEP_OF[status] ?? 0; const stores = (d?.stores ?? []) as any[]; const contract = d?.contract;
  const label: Record<string, string> = { lead: L('Lead', 'مبدئي'), applied: L('Applied', 'مقدَّم'), documents_pending: L('Documents pending', 'الوثائق مطلوبة'), under_review: L('Under review', 'قيد المراجعة'), approved: L('Approved', 'معتمد'), contract_pending: L('Contract to accept', 'عقد بانتظار القبول'), contract_signed: L('Contract signed', 'العقد موقّع'), store_setup: L('Store setup', 'إعداد المتجر'), first_listing_pending: L('Ready to list', 'جاهز للعرض'), active: L('Active', 'نشط'), rejected: L('Not accepted', 'غير مقبول'), suspended: L('Suspended', 'موقوف') };
  // The one thing to do next, per status.
  const next: null | { title: string; body: string; cta: string; go: () => void; tone: 'info' | 'time' | 'fresh' | 'error' } =
    status === 'rejected' ? { tone: 'error', title: L('Application not accepted', 'لم يُقبل الطلب'), body: (d?.history ?? []).find((h: any) => h.to === 'rejected')?.reason_text || L('Support has the reason on file. Reapplying is possible after 90 days.', 'لدى الدعم سبب الرفض. يمكن إعادة التقديم بعد 90 يوماً.'), cta: L('Contact support', 'تواصل مع الدعم'), go: () => router.push('/support') }
    : status === 'suspended' ? { tone: 'error', title: d?.suspended_until ? L(`Suspended until ${String(d.suspended_until).slice(0, 10)}`, `موقوف حتى ${String(d.suspended_until).slice(0, 10)}`) : L('Suspended', 'موقوف'), body: L(`Reason: ${String(d?.suspend_reason_code ?? '').replace(/_/g, ' ') || '—'}. Existing orders are honoured; new listings are blocked until the date.`, `السبب: ${String(d?.suspend_reason_code ?? '').replace(/_/g, ' ') || '—'}. الطلبات الحالية تُنفّذ؛ النشر متوقف حتى التاريخ.`), cta: L('Contact support', 'تواصل مع الدعم'), go: () => router.push('/support') }
    : status === 'active' ? { tone: 'fresh', title: L('You are live', 'أنت على الهواء'), body: L('Customers can see your bags. Keep documents current — listings stop the day one lapses.', 'العملاء يرون بقشك. أبقِ الوثائق سارية — يتوقف النشر يوم انتهاء إحداها.'), cta: L('List a bag', 'أضف بقشة'), go: () => router.push('/listing/publish') }
    : status === 'first_listing_pending' ? { tone: 'fresh', title: L('One step left', 'خطوة واحدة متبقية'), body: L('Publish your first bag. Your account activates on its own the moment it is live.', 'انشر أول بقشة. يُفعّل حسابك تلقائياً فور نشرها.'), cta: L('List your first bag', 'أضف أول بقشة'), go: () => router.push('/listing/publish') }
    : status === 'contract_signed' || status === 'store_setup' ? { tone: 'info', title: stores.length ? L('Set opening hours', 'حدد ساعات العمل') : L('Add your first branch', 'أضف فرعك الأول'), body: stores.length ? L('Hours tell us when a pickup window can be. Split shifts and Ramadan hours are separate.', 'الساعات تحدد متى يمكن أن يكون وقت الاستلام. الورديات المقسمة وساعات رمضان منفصلة.') : L('The pin and the pickup note are what customers see.', 'الدبوس وملاحظة الاستلام هما ما يراه العملاء.'), cta: stores.length ? L('Set hours', 'حدد الساعات') : L('Add branch', 'أضف فرعاً'), go: () => router.push(stores.length ? '/onboarding/hours' : '/onboarding/store') }
    : status === 'approved' || status === 'contract_pending' ? { tone: 'info', title: L('Read and accept the contract', 'اقرأ العقد ووافق عليه'), body: contract ? L(`${contract.commission_bp / 100}% commission, ${contract.payout_cadence} payouts. Acceptance is recorded with time and device.`, `عمولة ${contract.commission_bp / 100}%، دفعات ${contract.payout_cadence}. يُسجّل القبول مع الوقت والجهاز.`) : L('Ops is issuing it now.', 'يصدره فريق العمليات الآن.'), cta: L('Open contract', 'افتح العقد'), go: () => router.push('/onboarding/contract') }
    : status === 'under_review' ? { tone: 'time', title: rejected ? L(`${rejected} document needs a new copy`, `${rejected} وثيقة تحتاج نسخة جديدة`) : L('Ops is checking your documents', 'يراجع الفريق وثائقك'), body: rejected ? L('The reason is on each document. Re-upload and the review continues.', 'السبب على كل وثيقة. أعد الرفع وتستمر المراجعة.') : L('Usually within one working day. You get an email either way.', 'عادة خلال يوم عمل. يصلك بريد في الحالتين.'), cta: rejected ? L('Fix documents', 'صحّح الوثائق') : L('See documents', 'اعرض الوثائق'), go: () => router.push('/onboarding/documents') }
    : { tone: 'info', title: L(`Upload ${missing || 'your'} documents`, `ارفع ${missing || ''} الوثائق`), body: L('Licence, ID of the signatory, bank details. PDF or photo; reviewed within one working day.', 'الرخصة، هوية المفوّض، بيانات البنك. PDF أو صورة؛ تُراجع خلال يوم عمل.'), cta: L('Upload documents', 'ارفع الوثائق'), go: () => router.push('/onboarding/documents') };
  return <View style={{ flex: 1 }}><AppBar title={L('Setup', 'الإعداد')} sub={d?.trading_name} back={false} action={<Button variant="ghost" size="sm" onPress={() => db.auth.signOut()}>{L('Sign out', 'خروج')}</Button>} /><Screen top={false} gap={12}>
    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><T weight={600}>{L('Status', 'الحالة')}</T><Badge tone={status === 'active' ? 'fresh' : status === 'rejected' || status === 'suspended' ? 'error' : 'time'}>{label[status] ?? status}</Badge>{d?.activated_at ? <Caption>{L(`since ${String(d.activated_at).slice(0, 10)}`, `منذ ${String(d.activated_at).slice(0, 10)}`)}</Caption> : null}</View>
    {status !== 'rejected' && status !== 'suspended' ? <View style={{ flexDirection: 'row', alignItems: 'center', gap: 4 }}>{STEPS.map(([en, a], i) => <View key={en} style={{ flex: 1, gap: 4, alignItems: 'center' }}><View style={{ height: 6, alignSelf: 'stretch', borderRadius: 99, backgroundColor: i < step ? color.brand : i === step ? color.brandTint : color.sunken, borderWidth: i === step ? 1.5 : 0, borderColor: color.brand }} /><Caption style={{ fontSize: 9, textAlign: 'center' }} numberOfLines={1}>{ar ? a : en}</Caption></View>)}</View> : null}
    {next ? <Banner tone={next.tone} title={next.title} action={next.cta} onAction={next.go}>{next.body}</Banner> : null}
    <ListRow icon="file-text" label={L('Documents', 'الوثائق')} sub={docRows.length === 0 ? L('Nothing uploaded yet', 'لم يُرفع شيء بعد') : missing ? L(`${missing} to upload or renew`, `${missing} للرفع أو التجديد`) : L('All approved', 'كلها معتمدة')} value={rejected ? <Badge tone="error">{String(rejected)}</Badge> : undefined} chevron onPress={() => router.push('/onboarding/documents')} />
    <ListRow icon="file-text" label={L('Contract', 'العقد')} sub={contract?.accepted_at ? L(`Accepted · ${contract.commission_bp / 100}% commission`, `مقبول · عمولة ${contract.commission_bp / 100}%`) : contract ? L('Read and accept', 'اقرأ ووافق') : L('Issued after review', 'يصدر بعد المراجعة')} chevron onPress={() => router.push('/onboarding/contract')} />
    <ListRow icon="store" label={L('Branches & pickup points', 'الفروع ونقاط الاستلام')} sub={stores.length ? L(`${stores.length} branch`, `${stores.length} فرع`) : L('Add your first branch', 'أضف فرعك الأول')} chevron onPress={() => router.push(stores.length ? '/org/branch' : '/onboarding/store')} />
    <ListRow icon="clock" label={L('Opening hours', 'ساعات العمل')} sub={stores.length ? undefined : L('After the first branch', 'بعد الفرع الأول')} chevron onPress={() => (stores.length ? router.push('/onboarding/hours') : router.push('/onboarding/store'))} />
    <ListRow icon="package" label={L('First listing', 'أول عرض')} sub={status === 'first_listing_pending' || status === 'active' ? L('Ready', 'جاهز') : L('Unlocks when documents, contract and hours are done', 'يُفتح بعد الوثائق والعقد والساعات')} chevron onPress={() => router.push('/listing/publish')} />
    {(d?.history ?? []).length ? <Card><View style={{ gap: 6 }}><T weight={600}>{L('History', 'السجل')}</T>{(d.history as any[]).slice(0, 6).map((h, i) => <View key={i} style={{ flexDirection: 'row', gap: 8, alignItems: 'center' }}><Icon name="chevron-right" size={12} color={color.textTertiary} mirror /><T role="caption" style={{ flex: 1 }}>{`${label[h.to] ?? h.to}${h.reason_text ? ' · ' + h.reason_text : ''}`}</T><Num role="caption" color={color.textTertiary}>{String(h.at).slice(0, 10)}</Num></View>)}</View></Card> : null}
    <Caption>{L('Listings stop the day a required document lapses. Existing orders are always honoured.', 'يتوقف النشر يوم انتهاء وثيقة مطلوبة. الطلبات الحالية تُنفّذ دائماً.')}</Caption></Screen></View>; }
