// §2.6 Store setup — the dragged pin is authoritative; the pickup point is required in both languages.
import { useState } from 'react'; import { router } from 'expo-router'; import { View } from 'react-native'; import MapView, { Marker } from 'react-native-maps';
import { useCities, useUpsertStore, RpcError } from '@bugsha/api'; import { errorMessage } from '@bugsha/i18n';
import { AppBar, Banner, Button, Chip, Chips, Eyebrow, Foot, Input, Pp, Screen } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useSession } from '../../src/lib/session'; import { useStore } from '../../src/lib/store'; import { useL } from '../../src/lib/ui';
export default function StoreSetup() { const s = useStore(); const { locale } = useSession(); const { L, ar } = useL(); const cities = useCities(db, s.market) as any; const m = useUpsertStore(db); const kw = s.market === 'KW';
  const [f, setF] = useState({ name: '', city: '', gov: '', area: '', block: '', street: '', building: '', pen: '', par: '', phone: kw ? '+965' : '+20' }); const [pin, setPin] = useState(kw ? { latitude: 29.34, longitude: 48.03 } : { latitude: 30.06, longitude: 31.22 }); const [err, setErr] = useState<string | null>(null);
  const valid = f.name && f.city && f.gov && (kw ? f.area && f.block : f.area) && f.street && f.building && f.pen && f.par;
  return <View style={{ flex: 1 }}><AppBar title={L('Store & pickup point', 'المتجر ونقطة الاستلام')} onBack={() => router.back()} /><Screen top={false} gap={12}>
    <Input label={L('Branch name (as customers see it)', 'اسم الفرع (كما يراه العملاء)')} value={f.name} onChangeText={(v) => setF({ ...f, name: v })} />
    <Eyebrow>{L('City', 'المدينة')}</Eyebrow><Chips>{((cities.data ?? []) as any[]).filter((c) => c.stage === 'live').map((c) => <Chip key={c.id} selected={f.city === c.id} onPress={() => setF({ ...f, city: c.id, gov: c.name_en })}>{ar ? c.name_ar : c.name_en}</Chip>)}</Chips>
    <View style={{ flexDirection: 'row', gap: 8 }}><Input containerStyle={{ flex: 1 }} label={kw ? L('Area', 'المنطقة') : L('District', 'الحي')} value={f.area} onChangeText={(v) => setF({ ...f, area: v })} />{kw ? <Input containerStyle={{ width: 90 }} label={L('Block', 'قطعة')} value={f.block} onChangeText={(v) => setF({ ...f, block: v })} /> : null}</View>
    <View style={{ flexDirection: 'row', gap: 8 }}><Input containerStyle={{ flex: 1 }} label={L('Street', 'الشارع')} value={f.street} onChangeText={(v) => setF({ ...f, street: v })} /><Input containerStyle={{ width: 100 }} label={L('Building', 'المبنى')} value={f.building} onChangeText={(v) => setF({ ...f, building: v })} /></View>
    <Eyebrow>{L('Drag the pin to the door customers use', 'اسحب الدبوس إلى الباب الذي يستخدمه العملاء')}</Eyebrow><View style={{ height: 200, borderRadius: 10, overflow: 'hidden' }}><MapView style={{ flex: 1 }} initialRegion={{ ...pin, latitudeDelta: 0.02, longitudeDelta: 0.02 }} onPress={(e) => setPin(e.nativeEvent.coordinate)}><Marker coordinate={pin} draggable onDragEnd={(e) => setPin(e.nativeEvent.coordinate)} /></MapView></View>
    <Input label={L('Pickup point — English', 'نقطة الاستلام — إنجليزي')} value={f.pen} onChangeText={(v) => setF({ ...f, pen: v })} placeholder="Side door after 21:00, tell the cashier your code" /><Input label={L('Pickup point — Arabic', 'نقطة الاستلام — عربي')} value={f.par} onChangeText={(v) => setF({ ...f, par: v })} placeholder="الباب الجانبي بعد 21:00" />
    <Input label={L('Store phone', 'هاتف المتجر')} value={f.phone} onChangeText={(v) => setF({ ...f, phone: v })} keyboardType="phone-pad" />
    {err ? <Banner tone="error" title={err} /> : null}<Pp>{L('Customers see the pin and the pickup note, not the full address.', 'يرى العملاء الدبوس وملاحظة الاستلام، لا العنوان الكامل.')}</Pp></Screen>
    <Foot><Button size="lg" fullWidth disabled={!valid} loading={m.isPending} onPress={() => m.mutateAsync({ p_partner: s.partnerId, p_display_name: f.name, p_city_id: f.city, p_address: kw ? { governorate: f.gov, area: f.area, block: f.block, street: f.street, building: f.building } : { governorate: f.gov, district: f.area, street: f.street, building: f.building }, p_lat: pin.latitude, p_lng: pin.longitude, p_pickup_point_en: f.pen, p_pickup_point_ar: f.par, p_contact_phone: f.phone }).then((r: any) => { s.set({ storeId: r.store_id, storeName: r.display_name }); router.back(); }).catch((e: RpcError) => setErr(errorMessage(e.code, locale)))}>{L('Save branch', 'حفظ الفرع')}</Button></Foot></View>; }
