// §3.4.2/3 Edit listing — quantity floor = sold; price frozen after first sale; cancel with consequences before confirm.
import { useState } from 'react'; import { router, useLocalSearchParams } from 'expo-router'; import { View } from 'react-native';
import { useCancelListing, useListings, useUpdateListing, RpcError } from '@bugsha/api'; import { errorMessage } from '@bugsha/i18n';
import { AppBar, Banner, Button, Card, Chip, Chips, Dialog, Foot, Icon, Line, Num, Pp, Rule, Screen, Stepper, T, color } from '@bugsha/ui';
import { db } from '../../src/lib/supabase'; import { useSession } from '../../src/lib/session'; import { useStore } from '../../src/lib/store'; import { hhmm, money, useL } from '../../src/lib/ui';
const later = (t: string, m: number) => { const [h, mm] = t.split(':').map(Number); const d = new Date(2000, 0, 1, h!, mm! + m); return `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`; };
export default function EditListing() {
  const { id } = useLocalSearchParams<{ id: string }>(); const s = useStore(); const { locale } = useSession(); const { L } = useL(); const ls = useListings(db, s.storeId) as any; const upd = useUpdateListing(db); const cancel = useCancelListing(db);
  const l = ((ls.data ?? []) as any[]).find((x) => x.listing_id === id); const [qty, setQty] = useState<number | null>(null); const [end, setEnd] = useState<string | null>(null); const [err, setErr] = useState<string | null>(null); const [confirm, setConfirm] = useState(false); const [reason, setReason] = useState('sold_elsewhere');
  if (!l) return <Screen><Pp>…</Pp></Screen>; const sold = l.quantity_total - l.quantity_remaining; const q = qty ?? l.quantity_total; const e = end ?? hhmm(l.local_end);
  return <View style={{ flex: 1 }}><AppBar title={l.title_snapshot} sub={`${hhmm(l.local_start)}–${hhmm(l.local_end)}`} onBack={() => router.back()} /><Screen top={false} gap={12}>
    <Card><View style={{ gap: 10 }}><Line k={L('Sold so far', 'المباع حتى الآن')} v={<Num weight={700}>{String(sold)}</Num>} /><Rule /><View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><T role="label" weight={600}>{L('Total quantity', 'إجمالي الكمية')}</T><Stepper value={q} min={Math.max(1, sold)} max={60} onChange={setQty} /></View>
      {q <= sold && sold > 0 ? <Banner tone="error" title={L(`You can't go below ${sold}`, `لا يمكن النزول تحت ${sold}`)}>{L(`${sold} customers have already paid. Cancel the listing if you genuinely cannot supply them — they'll be refunded in full.`, `${sold} عملاء دفعوا بالفعل. ألغِ العرض إن كنت لا تستطيع توفيرها — سيُسترد لهم المبلغ كاملاً.`)}</Banner> : null}</View></Card>
    <Card><View style={{ gap: 8 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><Icon name="lock" size={16} color={color.textTertiary} /><T role="label" weight={600} style={{ flex: 1 }}>{L('Price', 'السعر')}</T><Num weight={700}>{money(l.price_minor, s.market)}</Num></View><Pp style={{ fontSize: 12.5 }}>{sold > 0 ? L("Frozen since the first sale. Price changes after a sale are the top cause of customer complaints, so they're blocked — create a new listing instead.", 'مُجمّد منذ أول عملية بيع. تغيير السعر بعد البيع أكبر سبب لشكاوى العملاء، لذا هو محظور — أنشئ عرضاً جديداً بدلاً من ذلك.') : L('Price comes from the template. Edit the template to change it.', 'السعر من القالب. عدّل القالب لتغييره.')}</Pp></View></Card>
    <Card><View style={{ gap: 8 }}><T role="label" weight={600}>{L('Extend the window', 'تمديد الوقت')}</T><Chips>{[0, 30, 60].map((m) => { const v = later(hhmm(l.local_end), m); return <Chip key={m} selected={e === v} onPress={() => setEnd(v)}>{v}</Chip>; })}</Chips>{sold > 0 ? <Pp style={{ fontSize: 12.5 }}>{L(`The ${sold} customers holding orders are notified of the later end time.`, `سيُبلَّغ العملاء الـ${sold} بالوقت الجديد.`)}</Pp> : null}</View></Card>
    {err ? <Banner tone="error" title={err} /> : null}
    <Button variant="ghost" fullWidth onPress={() => setConfirm(true)}>{L('Cancel this listing', 'إلغاء هذا العرض')}</Button></Screen>
    <Foot><Button size="lg" fullWidth loading={upd.isPending} onPress={() => upd.mutateAsync({ listingId: id!, quantity: q !== l.quantity_total ? q : undefined, localEnd: e !== hhmm(l.local_end) ? e : undefined }).then(() => router.back()).catch((ex: RpcError) => setErr(errorMessage(ex.code, locale, { sold })))}>{L('Save changes', 'حفظ التغييرات')}</Button></Foot>
    <Dialog open={confirm} title={L('Cancel the listing?', 'إلغاء العرض؟')} body={sold > 0 ? L(`${sold} paid customers are refunded in full and notified. This counts against your reliability score.`, `يُسترد المبلغ كاملاً لـ${sold} عملاء ويُبلَّغون. يؤثر هذا على درجة موثوقيتك.`) : L('Nothing has sold yet. The listing is removed.', 'لم يُبع شيء بعد. سيُزال العرض.')} confirmLabel={L('Cancel listing', 'إلغاء العرض')} cancelLabel={L('Keep it', 'الإبقاء عليه')} tone="danger" onCancel={() => setConfirm(false)} onConfirm={() => { setConfirm(false); cancel.mutateAsync({ listingId: id!, reasonCode: reason }).then(() => router.back()).catch((ex: RpcError) => setErr(errorMessage(ex.code, locale))); }} /></View>;
}
