// §3.4.1 Fast publish — three steps, no price field. The most recent template is pre-selected.
import { useMemo, useState } from 'react'; import { router } from 'expo-router'; import { View } from 'react-native';
import { usePublish, useTemplates, RpcError } from '@bugsha/api'; import { errorMessage } from '@bugsha/i18n';
import { AppBar, Banner, Button, Card, Caption, Chip, Chips, Foot, Icon, Line, ListingStep, Num, PickupWindow, Pp, PriceTag, Screen, Stepper, T, color } from '@bugsha/ui';
import { db } from '../../src/lib/supabase'; import { useSession } from '../../src/lib/session'; import { useStore } from '../../src/lib/store'; import { hhmm, major, money, useL, CUR } from '../../src/lib/ui';
const shift = (t: string, mins: number) => { const [h, m] = t.split(':').map(Number); const d = new Date(2000, 0, 1, h!, m!); d.setMinutes(d.getMinutes() + mins); return `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`; };
export default function Publish() {
  const s = useStore(); const { locale } = useSession(); const { L, ar } = useL(); const tpl = useTemplates(db, s.partnerId) as any; const publish = usePublish(db);
  const list = ((tpl.data ?? []) as any[]).filter((t) => !t.store_id || t.store_id === s.storeId); const [step, setStep] = useState(1); const [tid, setTid] = useState<string | null>(null); const [qty, setQty] = useState(6); const [win, setWin] = useState(0); const [err, setErr] = useState<string | null>(null); const [done, setDone] = useState<any>(null);
  const t = useMemo(() => list.find((x) => x.id === (tid ?? list[0]?.id)), [list, tid]); const cur = CUR[s.market]; const today = new Date().toISOString().slice(0, 10);
  const windows = t ? [[hhmm(t.default_window_start), hhmm(t.default_window_end)], [shift(hhmm(t.default_window_start), 30), shift(hhmm(t.default_window_end), 30)], [shift(hhmm(t.default_window_start), 60), shift(hhmm(t.default_window_end), 60)]] : [];
  const w = windows[win] ?? windows[0]; const net = t ? major(t.price_minor, s.market) * qty * 0.78 : 0;
  if (done) return <View style={{ flex: 1 }}><Screen scroll={false} style={{ alignItems: 'center', justifyContent: 'center', gap: 14, padding: 18 }}><View style={{ width: 52, height: 52, borderRadius: 99, backgroundColor: color.brandTint, alignItems: 'center', justifyContent: 'center' }}><Icon name="check" size={26} color={color.brand} /></View>
    <T role="titleLg" weight={700} align="center">{L(`Live — ${qty} bags`, `منشورة — ${qty} بقش`)}</T><Pp style={{ textAlign: 'center' }}>{L('Customers within 5 km can see it now. Saved customers get a notification.', 'العملاء ضمن 5 كم يرونها الآن. المتابعون سيصلهم إشعار.')}</Pp>
    <Card style={{ alignSelf: 'stretch' }}><View style={{ gap: 6 }}><Line k={L('Window', 'الوقت')} v={<Num role="label">{`${w?.[0]}–${w?.[1]}`}</Num>} /><Line k={L('Price', 'السعر')} v={<Num role="label">{money(t.price_minor, s.market)}</Num>} /></View></Card></Screen>
    <Foot><Button size="lg" fullWidth iconStart="plus" onPress={() => { setDone(null); setStep(1); }}>{L('List another bag', 'أضف بقشة أخرى')}</Button><Button variant="ghost" fullWidth onPress={() => router.replace('/(tabs)')}>{L('Back to today', 'العودة لليوم')}</Button></Foot></View>;
  return <View style={{ flex: 1 }}><AppBar title={L('List a bag', 'أضف بقشة')} sub={s.storeName} onBack={() => router.back()} /><Screen top={false} gap={12}>
    <ListingStep index={1} total={3} title={step > 1 && t ? `${ar ? t.title_ar : t.title_en} · ${qty}` : L('Which bag?', 'أي بقشة؟')} hint={step === 1 && list[0] ? L(`Last time you listed ${ar ? list[0].title_ar : list[0].title_en}`, `آخر مرة عرضت ${list[0].title_ar}`) : undefined} done={step > 1}>
      {step === 1 ? <View style={{ gap: 8 }}>{list.map((x) => <Card key={x.id} onPress={() => setTid(x.id)} style={{ borderColor: (t?.id === x.id) ? color.brand : color.borderSubtle, borderWidth: t?.id === x.id ? 1.5 : 1 }}><View style={{ flexDirection: 'row', gap: 10, alignItems: 'center' }}><View style={{ flex: 1 }}><T weight={700}>{ar ? x.title_ar : x.title_en}</T><View style={{ flexDirection: 'row', gap: 4 }}><Num role="caption" color={color.textSecondary}>{money(x.price_minor, s.market)}</Num><Caption>·</Caption><Num role="caption" color={color.textSecondary}>{`${hhmm(x.default_window_start)}–${hhmm(x.default_window_end)}`}</Num></View></View>{t?.id === x.id ? <Icon name="circle-check" size={20} color={color.brand} /> : null}</View></Card>)}
        {list.length === 0 ? <Banner tone="info" title={L('No templates yet', 'لا قوالب بعد')}>{L('Create one first — it takes a minute.', 'أنشئ واحداً أولاً — يستغرق دقيقة.')}</Banner> : null}<Button variant="ghost" size="sm" iconStart="plus" onPress={() => router.push('/templates/edit')}>{L('Create a new template', 'إنشاء قالب جديد')}</Button></View> : null}</ListingStep>
    <ListingStep index={2} total={3} title={step === 2 ? L('How many tonight?', 'كم بقشة الليلة؟') : step > 2 ? L('Quantity confirmed', 'تم تأكيد الكمية') : L('How many?', 'كم العدد؟')} hint={step === 2 && t ? L(`Template default is ${t.default_quantity}`, `الافتراضي ${t.default_quantity}`) : undefined} done={step > 2}>
      {step === 2 ? <View style={{ gap: 10 }}><View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><Num weight={700} style={{ fontSize: 40, lineHeight: 46 }}>{String(qty)}</Num><Stepper value={qty} min={1} max={40} onChange={setQty} /></View><Card style={{ backgroundColor: color.sunken, borderColor: 'transparent' }}><Line k={L(`If all ${qty} sell`, `إذا بيعت الـ${qty}`)} v={<Num weight={700}>{`${cur.code} ${net.toFixed(cur.dp)}`}</Num>} /><Caption>{L('after 22% commission', 'بعد عمولة 22%')}</Caption></Card></View> : null}</ListingStep>
    <ListingStep index={3} total={3} title={step === 3 ? L('When can they collect?', 'متى يمكنهم الاستلام؟') : L('Collection window', 'وقت الاستلام')}>
      {step === 3 ? <View style={{ gap: 8 }}><Chips>{windows.map((x, i) => <Chip key={i} selected={win === i} onPress={() => setWin(i)}>{`${x[0]}–${x[1]}`}</Chip>)}</Chips><Caption>{L('Today', 'اليوم')}</Caption>
        <Card><View style={{ gap: 6 }}><T weight={700}>{s.storeName}</T><PickupWindow day={L('Today', 'اليوم')} from={w![0]!} to={w![1]!} /><PriceTag now={major(t.price_minor, s.market)} was={t.value_min_minor ? major(t.value_min_minor, s.market) : null} currency={cur.code} decimals={cur.dp} /></View></Card></View> : null}</ListingStep>
    {err ? <Banner tone="error" title={err} /> : null}</Screen>
    <Foot>{step < 3 ? <Button size="lg" fullWidth iconEnd="arrow-right" disabled={!t} onPress={() => { if (step === 1 && t) setQty(t.default_quantity ?? 6); setStep(step + 1); }}>{L('Next', 'التالي')}</Button>
      : <Button size="lg" fullWidth loading={publish.isPending} onPress={() => publish.mutateAsync({ templateId: t.id, quantity: qty, localDate: today, localStart: w![0]!, localEnd: w![1]! }).then((r) => setDone(r)).catch((e: RpcError) => setErr(errorMessage(e.code, locale)))}>{L(`Publish ${qty} bags`, `نشر ${qty} بقش`)}</Button>}</Foot></View>;
}
