// S-C-027 — saved stores with availability and per-store notify toggles.
import { router } from 'expo-router'; import { View } from 'react-native';
import { useSavedStores, useSetSavedNotify } from '@bugsha/api';
import { AppBar, BagCard, Caption, Card, EmptyState, Screen, Switch, T } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useSession } from '../../src/lib/session'; import { bagTitle, cdFmt, major, minutesLeft, useL, CUR } from '../../src/lib/ui';
export default function Saved() { const { market } = useSession(); const { L, ar } = useL(); const q = useSavedStores(db); const setN = useSetSavedNotify(db); const rows = (q.data ?? []) as any[]; const cur = CUR[market];
  const hm = (iso: string) => new Date(iso).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });
  return <View style={{ flex: 1 }}><AppBar title={L('Saved stores', 'المتاجر المحفوظة')} back={false} /><Screen top={false} gap={10}>
    {rows.length === 0 ? <EmptyState icon="heart" title={L('Save the stores you like', 'احفظ متاجرك المفضلة')} body={L('Good bags go in minutes. Saved stores can ping you the second they list, before the feed fills up.', 'البقش الجيدة تنفد خلال دقائق. المتاجر المحفوظة تنبّهك فور عرضها قبل امتلاء القائمة.')} actionLabel={L("Browse tonight's bags", 'تصفّح بقش الليلة')} onAction={() => router.navigate('/(tabs)')} />
      : rows.map((r) => r.live_listing_id ? <BagCard key={r.store_id} layout="row" partner={r.display_name} title={bagTitle(r.category, ar)} category={r.category} priceNow={major(r.price_minor, market)} currency={cur.code} decimals={cur.dp} from={hm(r.next_window_start)} to={hm(r.next_window_end)} bagsLeft={r.quantity_remaining} minutesLeft={minutesLeft(r.next_window_end) <= 60 ? minutesLeft(r.next_window_end) : null} countdownFormat={cdFmt(ar)} onPress={() => router.push(`/listing/${r.live_listing_id}`)} />
        : <Card key={r.store_id} onPress={() => router.push(`/store/${r.store_id}`)}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}><View style={{ flex: 1 }}><T weight={600}>{r.display_name}</T><Caption>{L('Nothing listed tonight', 'لا شيء معروض الليلة')}</Caption></View><Switch checked={r.notify} onChange={(v) => setN.mutateAsync({ storeId: r.store_id, notify: v }).then(() => q.refetch())} label={L('Notify me', 'نبّهني')} /></View></Card>)}</Screen></View>; }
