// S-C-026 — category landing with "what's usually inside".
import { router, useLocalSearchParams } from 'expo-router'; import { View } from 'react-native';
import { useBrowse } from '@bugsha/api'; import { AppBar, BagCard, Card, Pp, Screen, T, color } from '@bugsha/ui';
import { db } from '../../src/lib/supabase'; import { useSession } from '../../src/lib/session'; import { bagTitle, cdFmt, hhmm, leftFmt, major, minutesLeft, useL, CUR } from '../../src/lib/ui';
const BLURB: Record<string, [string, string]> = { bakery: ["Breads, viennoiserie and pastries baked this morning that the counter didn't sell. Best eaten within a day, and they freeze well.", 'خبز ومعجنات ومخبوزات صُنعت هذا الصباح ولم تُبع. الأفضل تناولها خلال يوم، وتتحمل التجميد جيداً.'], meals: ['Two to three hot mains from the day\'s menu, portioned for two.', 'من وجبتين إلى ثلاث وجبات ساخنة من قائمة اليوم، تكفي شخصين.'], cafe: ['Sandwiches, cakes and whatever the counter had at close.', 'ساندويتشات وكيك وما تبقى عند الإغلاق.'], grocery: ['Fruit, veg and short-dated packaged goods.', 'فواكه وخضار ومنتجات قريبة من تاريخها.'], sweets: ['Pastries and desserts made today.', 'حلويات ومعجنات اليوم.'] };
export default function Category() { const { cat } = useLocalSearchParams<{ cat: string }>(); const { market, cityId } = useSession(); const { L, ar } = useL(); const q = useBrowse(db, market, cityId); const rows = ((q.data ?? []) as any[]).filter((r) => r.category === cat); const b = BLURB[cat!] ?? BLURB.bakery!;
  return <View style={{ flex: 1 }}><AppBar title={bagTitle(cat, ar).replace(' bag', ' bags')} onBack={() => router.back()} /><Screen top={false} gap={12}>
    <Card style={{ backgroundColor: color.brandTint, borderColor: 'transparent' }}><View style={{ gap: 6 }}><T weight={700}>{L("What's usually inside", 'ما بداخلها عادة')}</T><Pp style={{ color: color.text }}>{L(b[0], b[1])}</Pp></View></Card>
    {rows.map((r) => <BagCard key={r.listing_id} layout="row" partner={r.display_name} title={bagTitle(r.category, ar)} category={r.category} priceNow={major(r.price_minor, market)} priceWas={r.value_min_minor ? major(r.value_min_minor, market) : null} currency={CUR[market].code} decimals={CUR[market].dp} from={hhmm(r.local_start)} to={hhmm(r.local_end)} bagsLeft={r.quantity_remaining} leftFormat={leftFmt(ar)} rating={Number(r.rating) || null} minutesLeft={minutesLeft(r.window_end_utc) <= 60 ? minutesLeft(r.window_end_utc) : null} countdownFormat={cdFmt(ar)} onPress={() => router.push(`/listing/${r.listing_id}`)} />)}</Screen></View>; }
