// S-C-020 — one screen, every order state. Held: pay inside the hold, live countdown, Fawry reference.
// Reserved: the code legible at arm's length, running late, cancel with a refund destination.
// Redeemed: stars, then tags and a line. No-show: the count that leads to a restriction. Cancelled by
// the store: refund plus goodwill. Refunded: destination and timing per method.
import { useEffect, useState } from 'react'; import { router, useLocalSearchParams } from 'expo-router'; import { View } from 'react-native';
import { useCancelOrder, useOrder, useProfile, useReleaseHold, useSubmitReview, useWallet } from '@bugsha/api'; import { refundTimingMessage } from '@bugsha/i18n';
import { AppBar, Banner, BottomSheet, Button, Caption, Card, Chip, Chips, CountdownPill, Foot, Icon, IconButton, Input, Line, Num, PickupWindow, RatingStars, QrCode, RedemptionCode, Rule, Screen, T, color, redeemDeepLink } from '@bugsha/ui';
import { db } from '../../src/lib/supabase'; import { useSession } from '../../src/lib/session'; import { cdFmt, minutesLeft, money, useL } from '../../src/lib/ui';
const TAGS: Array<[string, string, string]> = [['generous', 'Generous', 'سخية'], ['fresh', 'Fresh', 'طازجة'], ['as_described', 'As described', 'كما وُصفت'], ['friendly_staff', 'Friendly staff', 'طاقم ودود'], ['smaller_than_expected', 'Smaller than expected', 'أصغر من المتوقع'], ['slow_handover', 'Slow handover', 'تسليم بطيء']];
export default function Order() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { market, locale, userId } = useSession(); const { L, ar } = useL();
  const q = useOrder(db, id!); const release = useReleaseHold(db); const cancel = useCancelOrder(db); const review = useSubmitReview(db); const profile = useProfile(db, !!userId) as any; const wallet = useWallet(db) as any;
  const [cancelOpen, setCancelOpen] = useState(false); const [dest, setDest] = useState<'source' | 'wallet'>('source'); const [tick, setTick] = useState(0);
  const [rating, setRating] = useState(0); const [tags, setTags] = useState<string[]>([]); const [body, setBody] = useState(''); const [reviewDone, setReviewDone] = useState(false);
  useEffect(() => { const t = setInterval(() => setTick((n) => n + 1), 1000); return () => clearInterval(t); }, []);
  const d = q.data as any; if (!d) return <Screen><Caption>…</Caption></Screen>;
  const o = d.order, st = d.store; const hm = (iso: string) => new Date(iso).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit', timeZone: st.timezone });
  const win = `${hm(o.window_start_utc)}–${hm(o.window_end_utc)}`; const mins = minutesLeft(o.window_end_utc); void tick;
  const canCancel = o.status === 'reserved' && new Date() < new Date(d.cancellation_cutoff_at);
  const refundDest = String(d.refund_timing_key ?? '').split('.')[1] ?? o.method;
  const pickupCard = <Card><View style={{ gap: 10 }}><PickupWindow day={L('Tonight', 'الليلة')} from={hm(o.window_start_utc)} to={hm(o.window_end_utc)} size="lg" />
    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><Icon name="navigation" size={15} color={color.textSecondary} /><T role="label" color={color.textSecondary} style={{ flex: 1 }}>{ar ? st.pickup_point_ar : st.pickup_point_en}</T></View></View></Card>;
  // ── held ────────────────────────────────────────────────────────────────
  if (o.status === 'held') {
    const left = o.hold_expires_at ? Math.max(0, Math.round((new Date(o.hold_expires_at).getTime() - Date.now()) / 1000)) : null; const fawry = d.payment?.fawry_reference ?? d.payment?.provider_ref;
    return <View style={{ flex: 1 }}><AppBar title={L('Complete your reservation', 'أكمل حجزك')} onBack={() => router.back()} />
      <Screen top={false} pad={16}>
        <Banner tone={left != null && left < 120 ? 'error' : 'time'} title={left == null ? L('Held for 10 minutes', 'محجوزة لعشر دقائق') : left === 0 ? L('The hold has expired', 'انتهى وقت الحجز') : L(`Held for ${Math.floor(left / 60)}:${String(left % 60).padStart(2, '0')} more`, `محجوزة لـ ${Math.floor(left / 60)}:${String(left % 60).padStart(2, '0')} أخرى`)}>{left === 0 ? L('The bag went back on the shelf. Reserve it again if it is still there.', 'عادت البقشة للعرض. احجزها مجدداً إن كانت متاحة.') : L('Pay to confirm. The bag goes back on the shelf if the hold expires.', 'ادفع للتأكيد. تعود البقشة للعرض إذا انتهى وقت الحجز.')}</Banner>
        {fawry && o.method === 'fawry' ? <Card style={{ backgroundColor: color.brandTint, borderColor: 'transparent' }}><View style={{ gap: 4, alignItems: 'center' }}><Caption>{L('Fawry reference — pay at any Fawry point', 'رقم فوري — ادفع في أي منفذ فوري')}</Caption><Num weight={700} tracking={2} style={{ fontSize: 26, lineHeight: 32 }}>{String(fawry)}</Num><Caption>{L('The bag is yours the moment Fawry confirms.', 'تصبح البقشة لك فور تأكيد فوري.')}</Caption></View></Card> : null}
        <Card><View style={{ gap: 6 }}><T weight={600}>{o.title_snapshot}</T><Caption>{st.display_name}</Caption><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><T role="label" color={color.textSecondary}>{L('Total', 'الإجمالي')}</T><Num weight={700}>{money(o.total_minor, market)}</Num></View></View></Card>{pickupCard}</Screen>
      <Foot>{left !== 0 ? <Button size="lg" fullWidth onPress={() => router.push({ pathname: '/pay', params: { order: id } })}>{L(`Pay ${money(o.total_minor, market)}`, `ادفع ${money(o.total_minor, market)}`)}</Button> : <Button size="lg" fullWidth onPress={() => router.replace(`/listing/${o.listing_id}`)}>{L('Back to the bag', 'العودة إلى البقشة')}</Button>}<Button variant="ghost" fullWidth onPress={() => release.mutateAsync(id!).then(() => router.back())}>{L('Release the bag', 'إلغاء الحجز')}</Button></Foot></View>;
  }
  const reserved = o.status === 'reserved', redeemed = o.status === 'redeemed'; const noShows = Number(profile.data?.no_show_count_90d ?? 0);
  const title = redeemed ? L('Collected', 'تم الاستلام') : reserved ? L('Reserved', 'محجوزة') : o.status === 'no_show' ? L('Not collected', 'لم تُستلم') : o.status === 'cancelled_partner' ? L('Cancelled by the store', 'ألغاها المتجر') : o.status === 'refunded' ? L('Refunded', 'مستردة') : L('Cancelled', 'ملغاة');
  const sendReview = () => review.mutateAsync({ orderId: id!, rating, tags, body: body.trim() || undefined }).then(() => { setReviewDone(true); q.refetch(); });
  return <View style={{ flex: 1 }}><AppBar title={title} onBack={() => router.back()} action={<IconButton icon="info" label={L('Help', 'مساعدة')} onPress={() => router.push('/account/help')} />} />
    <Screen top={false} pad={16} gap={14}>
      {reserved || redeemed ? <>
        <T align="center" color={color.textSecondary}>{redeemed ? L('Enjoy it.', 'بالعافية.') : L('Show this at the counter', 'أظهر هذا عند الكاشير')}</T>
        <RedemptionCode code={o.code} partner={st.display_name} window={win} quantity={o.quantity} state={redeemed ? 'redeemed' : 'ready'} bagLabel={o.quantity > 1 ? L('bags', 'بقش') : L('bag', 'بقشة')} slideLabel={L('Staff confirms on their device', 'الموظف يؤكد من جهازه')} doneLabel={L('Collected', 'تم الاستلام')} />
        {reserved ? <QrCode value={redeemDeepLink(o.code)} size={150} /> : null}
        {reserved ? <View style={{ alignItems: 'center' }}><CountdownPill state="reserved" minutesLeft={mins} format={cdFmt(ar)} /></View> : null}
        {reserved && o.method === 'cash' ? <Banner tone="info" title={L(`Bring ${money(o.total_minor, market)} in cash`, `أحضر ${money(o.total_minor, market)} نقداً`)}>{L('Exact amount helps. Not collecting counts as a no-show.', 'المبلغ المضبوط يساعد. عدم الاستلام يُحسب غياباً.')}</Banner> : null}
        {pickupCard}
        {reserved ? <Card style={{ backgroundColor: color.brandTint, borderColor: 'transparent' }}><View style={{ flexDirection: 'row', gap: 12, alignItems: 'center' }}><Icon name="clock" size={22} color={color.brand} /><View style={{ flex: 1 }}><T weight={600}>{L('Running late?', 'متأخر؟')}</T><Caption>{L(`Call the store on ${st.contact_phone} — they can hold your bag up to 15 minutes after the window.`, `اتصل بالمتجر على ${st.contact_phone} — يمكنهم الاحتفاظ ببقشتك حتى 15 دقيقة بعد الوقت.`)}</Caption></View></View></Card> : null}
        {redeemed && d.impact ? <Card><View style={{ flexDirection: 'row', gap: 12 }}><View style={{ flex: 1 }}><Caption>{L('You saved', 'وفّرت')}</Caption><Num weight={700}>{money(d.impact.saved_minor ?? 0, market)}</Num></View><View style={{ flex: 1 }}><Caption>{L('Kept out of the bin', 'أُنقذ من النفايات')}</Caption><Num weight={700}>{`${d.impact.estimated_kg ?? 0} kg`}</Num></View></View></Card> : null}
        {redeemed && !d.review && !reviewDone ? <Card><View style={{ gap: 10, alignItems: 'center' }}><T weight={600}>{L('How was the bag?', 'كيف كانت البقشة؟')}</T><RatingStars value={rating} size={30} onRate={setRating} />
          {rating > 0 ? <View style={{ alignSelf: 'stretch', gap: 10 }}><Chips>{TAGS.map(([k, en, a]) => <Chip key={k} selected={tags.includes(k)} onPress={() => setTags(tags.includes(k) ? tags.filter((t) => t !== k) : [...tags, k])}>{L(en, a)}</Chip>)}</Chips>
            <Input value={body} onChangeText={setBody} multiline placeholder={L('A line for the kitchen (optional)', 'سطر للمطبخ (اختياري)')} style={{ minHeight: 64 }} />
            <Button fullWidth loading={review.isPending} onPress={sendReview}>{L('Send review', 'إرسال التقييم')}</Button><Caption align="center">{L('The store sees the stars and your words, never your name.', 'يرى المتجر النجوم وكلماتك، لا اسمك.')}</Caption></View> : null}</View></Card> : null}
        {redeemed && (d.review || reviewDone) ? <Banner tone="fresh" title={L('Thanks for the review', 'شكراً على تقييمك')} /> : null}
      </> : null}
      {o.status === 'no_show' ? <>
        <Banner tone="info" title={L('The window closed before pickup', 'انتهى الوقت قبل الاستلام')}>{o.method === 'cash' ? L('Nothing was charged. The store kept the bag.', 'لم يُخصم شيء. احتفظ المتجر بالبقشة.') : L('No refund is due for a missed bag — the store prepared and held it for you.', 'لا يُسترد مبلغ البقشة الفائتة — المتجر جهّزها واحتفظ بها لك.')}</Banner>
        {noShows >= 2 ? <Banner tone="error" title={L(`${noShows} missed bags in 90 days`, `${noShows} بقش فائتة خلال 90 يوماً`)}>{L('A third pauses reservations for 30 days. Cancel before the cutoff if plans change.', 'الثالثة توقف الحجز 30 يوماً. ألغِ قبل الموعد النهائي إذا تغيّرت خططك.')}</Banner> : noShows === 1 ? <Caption>{L('One missed bag so far. Three in 90 days pauses reservations.', 'بقشة فائتة واحدة حتى الآن. ثلاث خلال 90 يوماً توقف الحجز.')}</Caption> : null}
        {pickupCard}</> : null}
      {o.status === 'cancelled_partner' ? <>
        <Banner tone="info" title={L('The store had to cancel', 'اضطر المتجر للإلغاء')}>{L(`Sorry — that should not happen. ${o.method === 'cash' ? 'Nothing was charged.' : 'Your payment is refunded in full.'}`, `نعتذر — ما كان ينبغي أن يحدث. ${o.method === 'cash' ? 'لم يُخصم شيء.' : 'يُسترد مبلغك كاملاً.'}`)}</Banner>
        {o.method !== 'cash' ? <Card><View style={{ gap: 6 }}><Line k={L('Refund', 'الاسترداد')} v={<Num weight={700}>{money(o.total_minor, market)}</Num>} strong /><Caption>{refundTimingMessage(market, refundDest, locale)}</Caption></View></Card> : null}
        {Number(wallet.data?.balance_minor) > 0 ? <Banner tone="fresh" title={L('Goodwill credit added to your wallet', 'أُضيف رصيد تعويضي إلى محفظتك')} action={L('Wallet', 'المحفظة')} onAction={() => router.push('/account/wallet')} /> : null}</> : null}
      {o.status === 'cancelled_consumer' || o.status === 'refunded' ? <>
        <Banner tone="info" title={o.status === 'refunded' ? L('Refunded', 'تم الاسترداد') : L('You cancelled this bag', 'ألغيت هذه البقشة')}>{o.method === 'cash' ? L('Nothing was charged.', 'لم يُخصم شيء.') : refundTimingMessage(market, refundDest, locale)}</Banner>
        <Card><View style={{ gap: 6 }}><T weight={600}>{o.title_snapshot}</T><Caption>{`${st.display_name} · ${hm(o.window_start_utc)}–${hm(o.window_end_utc)}`}</Caption><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><T role="label" color={color.textSecondary}>{L('Total', 'الإجمالي')}</T><Num weight={700}>{money(o.total_minor, market)}</Num></View></View></Card>
        {(d.refunds ?? []).map((r: any, i: number) => <Card key={i}><View style={{ gap: 4 }}><Line k={r.destination === 'wallet' ? L('To your wallet', 'إلى محفظتك') : L('To your card', 'إلى بطاقتك')} v={<Num weight={700}>{money(r.amount_minor, market)}</Num>} strong /><Caption>{String(r.status)}</Caption></View></Card>)}</> : null}
      <View style={{ gap: 8 }}><Button variant="secondary" fullWidth iconStart="receipt" onPress={() => router.push({ pathname: '/order/receipt', params: { id } })}>{L('Receipt', 'الإيصال')}</Button><Button variant="secondary" fullWidth iconStart="triangle-alert" onPress={() => router.push({ pathname: '/order/report', params: { id } })}>{L('Report a problem', 'إبلاغ عن مشكلة')}</Button></View>
      {canCancel ? <Button variant="ghost" fullWidth onPress={() => setCancelOpen(true)}>{L('Cancel bag', 'إلغاء البقشة')}</Button> : reserved ? <Caption align="center">{L(`Cancelling closed at ${hm(d.cancellation_cutoff_at)} — two hours before the window.`, `أُغلق الإلغاء ${hm(d.cancellation_cutoff_at)} — قبل الوقت بساعتين.`)}</Caption> : null}
    </Screen>
    <BottomSheet open={cancelOpen} title={L('Cancel this bag?', 'إلغاء هذه البقشة؟')} onClose={() => setCancelOpen(false)} footer={<View style={{ gap: 8 }}><Button variant="danger" fullWidth loading={cancel.isPending} onPress={() => cancel.mutateAsync({ orderId: id!, reasonCode: 'consumer_request', destination: o.method === 'cash' ? 'source' : dest }).then(() => { setCancelOpen(false); q.refetch(); })}>{L('Cancel bag', 'إلغاء البقشة')}</Button><Button variant="ghost" fullWidth onPress={() => setCancelOpen(false)}>{L('Keep it', 'الإبقاء عليها')}</Button></View>}>
      <T role="label" color={color.textSecondary}>{L('The bag goes back on sale.', 'تعود البقشة للبيع.')}</T>
      {o.method !== 'cash' ? <><Rule /><T weight={600}>{L('Where should the refund go?', 'إلى أين يُسترد المبلغ؟')}</T>
        {([['source', L('Back to how you paid', 'إلى وسيلة الدفع'), refundTimingMessage(market, refundDest, locale)], ['wallet', L('Bugsha wallet — instant', 'محفظة بقشة — فوراً'), L('Applied to your next bag. Refund credit never expires.', 'يُطبّق على بقشتك التالية. رصيد الاسترداد لا ينتهي.')]] as const).map(([k, t, sub]) => <Card key={k} onPress={() => setDest(k)} style={{ borderColor: dest === k ? color.brand : color.borderSubtle, borderWidth: dest === k ? 1.5 : 1 }}><View style={{ flexDirection: 'row', gap: 10, alignItems: 'center' }}><View style={{ flex: 1 }}><T weight={600}>{t}</T><Caption>{sub}</Caption></View>{dest === k ? <Icon name="circle-check" size={20} color={color.brand} /> : null}</View></Card>)}</> : <Caption>{L('Nothing was charged, so nothing is refunded.', 'لم يُخصم شيء، فلا يوجد ما يُسترد.')}</Caption>}
    </BottomSheet></View>;
}
