// S-C-047 — report a problem. Illness goes straight to Compliance; the partner is informed, never asked to triage.
import { useState } from 'react'; import { router, useLocalSearchParams } from 'expo-router'; import { View } from 'react-native';
import { useOpenDispute, RpcError } from '@bugsha/api'; import { errorMessage } from '@bugsha/i18n';
import { AppBar, Banner, Button, Chip, Chips, Eyebrow, Foot, Input, Pp, Screen } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useSession } from '../../src/lib/session'; import { useL } from '../../src/lib/ui';
const CATS: Array<[string, string, string]> = [['missing_items', 'Less than expected', 'أقل من المتوقع'], ['quality', 'Quality problem', 'مشكلة جودة'], ['store_closed', 'Store was closed', 'المتجر كان مغلقاً'], ['wrong_charge', 'Charged wrongly', 'خصم خاطئ'], ['suspected_foodborne_illness', 'I felt unwell after eating', 'شعرت بتوعّك بعد الأكل'], ['other', 'Something else', 'شيء آخر']];
export default function Report() { const { id } = useLocalSearchParams<{ id: string }>(); const { locale } = useSession(); const { L } = useL(); const m = useOpenDispute(db); const [cat, setCat] = useState('missing_items'); const [txt, setTxt] = useState(''); const [err, setErr] = useState<string | null>(null); const [ok, setOk] = useState<any>(null);
  return <View style={{ flex: 1 }}><AppBar title={L('Report a problem', 'الإبلاغ عن مشكلة')} onBack={() => router.back()} /><Screen top={false} pad={16} gap={12}>
    <Eyebrow>{L('What happened?', 'ماذا حدث؟')}</Eyebrow><Chips>{CATS.map(([k, en, a]) => <Chip key={k} selected={cat === k} onPress={() => setCat(k)}>{L(en, a)}</Chip>)}</Chips>
    {cat === 'suspected_foodborne_illness' ? <Banner tone="error" title={L('This goes to our safety team now', 'يصل هذا إلى فريق السلامة فوراً')}>{L('If you feel seriously unwell, seek medical care first. We log every report for the regulator.', 'إن كنت تشعر بتوعّك شديد، اطلب الرعاية الطبية أولاً. نسجّل كل بلاغ للجهة الرقابية.')}</Banner> : null}
    <Input label={L('Tell us in your words', 'اشرح بكلماتك')} value={txt} onChangeText={setTxt} multiline hint={L('Photos can be added from the order page.', 'يمكن إضافة الصور من صفحة الطلب.')} style={{ minHeight: 90 }} />
    {err ? <Banner tone="error" title={err} /> : null}{ok ? <Banner tone="fresh" title={L(`Received — case ${ok.case_ref ?? ''}`, `تم الاستلام — الحالة ${ok.case_ref ?? ''}`)}>{L('We reply within the hour for safety issues, within a day otherwise.', 'نرد خلال ساعة لمسائل السلامة، وخلال يوم لغيرها.')}</Banner> : null}</Screen>
    <Foot><Button size="lg" fullWidth disabled={txt.trim().length < 5 || !!ok} loading={m.isPending} onPress={() => m.mutateAsync({ orderId: id!, category: cat, statement: txt.trim(), illness: cat === 'suspected_foodborne_illness' ? { symptoms: [] } : undefined }).then(setOk).catch((e: RpcError) => setErr(errorMessage(e.code, locale)))}>{L('Send report', 'إرسال البلاغ')}</Button></Foot></View>; }
