// S-O-070..072 Config per market: propose a change (a second admin approves), feature flags and kill switches, cities and their stage.
import { useState } from 'react'; import { View } from 'react-native'; import { useOps, useOpsMutation } from '@bugsha/api';
import { Badge, Banner, Button, Caption, Eyebrow, Input, ListRow, SegmentedControl, Switch, T } from '@bugsha/ui'; import { db } from '../../src/lib/supabase';
import { Choice, Field, FormBox, MarketToggle, Panel, Empty, Row, useAct, when, type Market } from '../../src/lib/console';
const KEYS: Array<[string, string, 'int' | 'bool' | 'text' | 'date']> = [['default_commission_bp', 'Default commission (bp)', 'int'], ['cash_enabled', 'Cash on pickup', 'bool'], ['vat_applies', 'VAT applies', 'bool'], ['vat_bp', 'VAT (bp)', 'int'], ['vat_base', 'VAT base', 'text'], ['vat_effective_from', 'VAT effective from', 'date'], ['invoicing_mode', 'Invoicing mode', 'text'],
  ['price_min_minor', 'Min price (minor)', 'int'], ['price_max_minor', 'Max price (minor)', 'int'], ['max_price_fraction', 'Max price fraction of value', 'text'], ['reservation_cap_default', 'Reservation cap', 'int'], ['reservation_cap_new_user', 'Cap · new users', 'int'], ['reservation_cap_cash', 'Cap · cash', 'int'],
  ['hold_duration_minutes', 'Hold (minutes)', 'int'], ['cancel_cutoff_hours', 'Cancel cutoff (hours)', 'int'], ['late_redeem_grace_minutes', 'Late redeem grace (min)', 'int'], ['undo_redeem_seconds', 'Undo redeem (seconds)', 'int'], ['payout_cadence', 'Payout cadence', 'text'], ['payout_day', 'Payout day', 'int'], ['payout_min_minor', 'Payout minimum (minor)', 'int'],
  ['refund_cap_support_minor', 'Support refund cap (minor)', 'int'], ['adjustment_four_eyes_minor', 'Four-eyes above (minor)', 'int'], ['cash_variance_threshold_minor', 'Cash variance threshold', 'int'], ['cash_liability_escalate_minor', 'Cash liability escalate (minor)', 'int'], ['cash_liability_escalate_days', 'Cash liability escalate (days)', 'int']];
const STAGES: Array<[string, string]> = [['waitlist', 'Waitlist'], ['soft_launch', 'Soft launch'], ['live', 'Live']];
export default function C() {
  const [m, setM] = useState<Market>('KW'); const [tab, setTab] = useState<'config' | 'flags' | 'cities'>('config'); const [key, setKey] = useState<string | null>(null); const [val, setVal] = useState(''); const [city, setCity] = useState<any | null>(null);
  const cfg = useOps<any>(db, 'ops_market_config', { p_market: m }); const flags = useOps<any[]>(db, 'ops_feature_flags', { p_market: m }); const cities = useOps<any[]>(db, 'ops_cities', { p_market: m });
  const propose = useOpsMutation(db, 'ops_propose_config'); const setFlag = useOpsMutation(db, 'ops_set_flag'); const upsertCity = useOpsMutation(db, 'ops_upsert_city'); const { msg, tone, act } = useAct(); const c = cfg.data ?? {};
  const k = KEYS.find(([x]) => x === key); const parsed = k?.[2] === 'int' ? Number(val) : k?.[2] === 'bool' ? val === 'true' : val;
  return <>
    <Row style={{ justifyContent: 'space-between' }}><T role="titleLg" weight={700}>Config</T><Row><MarketToggle value={m} onChange={(v) => { setM(v ?? 'KW'); setKey(null); setCity(null); }} /><SegmentedControl fullWidth={false} value={tab} onChange={setTab} options={[{ value: 'config', label: 'Market config' }, { value: 'flags', label: `Flags · ${(flags.data ?? []).length}` }, { value: 'cities', label: `Cities · ${(cities.data ?? []).length}` }]} /></Row></Row>
    {msg ? <Banner tone={tone} title={msg} /> : null}
    {tab === 'config' ? <>
      <Caption>{`${m} · config v${c.version ?? '—'} · ${c.currency ?? ''} · ${c.timezone ?? ''}${c.pending_approval ? ' · a change is awaiting a second admin' : ''}. Every change is proposed, then approved by a different admin, then versioned.`}</Caption>
      <View style={{ flexDirection: 'row', gap: 14, alignItems: 'flex-start' }}>
        <Panel style={{ flex: 1 }}>{KEYS.map(([kk, label]) => <ListRow key={kk} onPress={() => { setKey(kk); setVal(String(c[kk] ?? '')); }} label={label} sub={kk} value={<Row><T role="label" weight={600}>{c[kk] == null ? '—' : String(c[kk])}</T>{key === kk ? <Badge tone="info">editing</Badge> : null}</Row>} />)}</Panel>
        {k ? <Panel style={{ width: 380, padding: 14, gap: 10 }}><T role="title" weight={700}>{k[1]}</T><Field k="Current" v={String(c[k[0]] ?? '—')} />
          {k[2] === 'bool' ? <Choice options={[['true', 'On'], ['false', 'Off']]} value={val} onChange={setVal} /> : <Input label="New value" value={val} onChangeText={setVal} keyboardType={k[2] === 'int' ? 'number-pad' : 'default'} placeholder={k[2] === 'date' ? 'YYYY-MM-DD' : undefined} />}
          <Caption>Takes effect only after a second admin approves the same change within the four-eyes window.</Caption>
          <Row><Button disabled={val === '' || String(c[k[0]]) === val} onPress={() => act(propose, { p_market: m, p_patch: { [k[0]]: parsed } }, `Proposed ${k[1]} = ${val}`, () => cfg.refetch())}>Propose</Button><Button variant="ghost" onPress={() => setKey(null)}>Cancel</Button></Row></Panel> : null}</View></> : null}
    {tab === 'flags' ? <>
      <Caption>Kill switches stop a whole flow (payments, publishing) for the market at once. Ordinary flags gate features by market or cohort.</Caption>
      <Panel>{(flags.data ?? []).length === 0 ? <Empty>No flags for this market.</Empty> : (flags.data ?? []).map((f) => <ListRow key={f.id} icon={f.is_kill_switch ? 'triangle-alert' : 'settings'} label={<Row><T role="label" weight={600}>{f.key}</T>{f.is_kill_switch ? <Badge tone="error">kill switch</Badge> : null}</Row>} sub={`${f.cohort ? 'cohort ' + f.cohort + ' · ' : ''}updated ${when(f.updated_at)}`} value={<Switch label={f.key} checked={!!f.enabled} onChange={(v) => act(setFlag, { p_key: f.key, p_market: m, p_enabled: v }, `${f.key} ${v ? 'on' : 'off'}`, () => flags.refetch())} />} />)}</Panel></> : null}
    {tab === 'cities' ? <>
      <Row style={{ justifyContent: 'space-between' }}><Caption>Waitlist cities collect sign-ups on the site; soft-launch cities show listings to invited users; live cities are open.</Caption><Button size="sm" onPress={() => setCity({ market: m, name_en: '', name_ar: '', governorate: '', stage: 'waitlist', default_radius_m: 5000 })}>Add city</Button></Row>
      <View style={{ flexDirection: 'row', gap: 14, alignItems: 'flex-start' }}>
        <Panel style={{ flex: 1 }}>{(cities.data ?? []).length === 0 ? <Empty>No cities yet.</Empty> : (cities.data ?? []).map((x) => <ListRow key={x.id} icon="map-pin" chevron onPress={() => setCity({ ...x })} label={<T role="label" weight={600}>{`${x.name_en} · ${x.name_ar}`}</T>} sub={`${x.governorate ?? ''} · radius ${x.default_radius_m} m`} value={<Badge tone={x.stage === 'live' ? 'fresh' : x.stage === 'soft_launch' ? 'time' : 'neutral'}>{String(x.stage).replace('_', ' ')}</Badge>} />)}</Panel>
        {city ? <Panel style={{ width: 380, padding: 14, gap: 10 }}><T role="title" weight={700}>{city.id ? 'Edit city' : 'New city'}</T>
          <Input label="Name (English)" value={city.name_en} onChangeText={(v) => setCity({ ...city, name_en: v })} /><Input label="Name (Arabic)" value={city.name_ar} onChangeText={(v) => setCity({ ...city, name_ar: v })} /><Input label="Governorate" value={city.governorate ?? ''} onChangeText={(v) => setCity({ ...city, governorate: v })} /><Input label="Default radius (m)" value={String(city.default_radius_m ?? 5000)} onChangeText={(v) => setCity({ ...city, default_radius_m: Number(v) || 0 })} keyboardType="number-pad" />
          <Choice label="Stage" options={STAGES} value={city.stage} onChange={(v) => setCity({ ...city, stage: v })} />
          <Row><Button disabled={!city.name_en.trim() || !city.name_ar.trim()} onPress={() => act(upsertCity, { p_payload: { id: city.id, market: m, name_en: city.name_en.trim(), name_ar: city.name_ar.trim(), governorate: city.governorate || null, stage: city.stage, default_radius_m: city.default_radius_m } }, `${city.name_en} saved as ${city.stage}`, () => { cities.refetch(); setCity(null); })}>Save</Button><Button variant="ghost" onPress={() => setCity(null)}>Cancel</Button></Row></Panel> : null}</View></> : null}
  </>; }
