// S-O-040 / S-O-041 Disputes with severity and SLA: assign, resolve with goodwill / refund (destination, cost bearer)
// or no money; critical (illness) cases go to Compliance and can open an incident, place and release a quality hold,
// and be closed with a signed-off resolution.
import { useState } from 'react'; import { View } from 'react-native'; import { useOps, useOpsMutation } from '@bugsha/api';
import { Badge, Banner, Button, Caption, Eyebrow, Input, ListRow, Num, SegmentedControl, Switch, T } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useSession } from '../../src/lib/session';
import { Choice, Field, FormBox, MarketToggle, Panel, Empty, Row, money, toMinor, useAct, when, short, type Market } from '../../src/lib/console';
const SEV: Array<[string, string]> = [['', 'All'], ['critical', 'Critical'], ['high', 'High'], ['standard', 'Standard']];
const REFUND_REASONS: Array<[string, string]> = [['quality_issue', 'Quality issue'], ['never_received', 'Never received'], ['goodwill', 'Goodwill'], ['partner_cancelled', 'Partner cancelled'], ['consumer_request', 'Consumer request']];
const CATS: Array<[string, string]> = [['food_safety', 'Food safety'], ['allergen', 'Allergen'], ['hygiene', 'Hygiene'], ['quantity', 'Quantity'], ['conduct', 'Conduct']];
const sevTone = (s: string) => s === 'critical' ? 'error' : s === 'high' ? 'urgent' : 'neutral';
const slaLeft = (iso: string) => { const h = (Date.parse(iso) - Date.now()) / 36e5; return h < 0 ? `SLA breached ${Math.round(-h)}h ago` : h < 24 ? `${Math.round(h)}h to SLA` : `${Math.round(h / 24)}d to SLA`; };
export default function D() {
  const { userId } = useSession(); const [tab, setTab] = useState<'disputes' | 'incidents'>('disputes'); const [m, setM] = useState<Market | null>(null); const [sev, setSev] = useState(''); const [openOnly, setOpenOnly] = useState(true); const [sel, setSel] = useState<string | null>(null);
  const [mode, setMode] = useState<'view' | 'resolve' | 'incident' | 'hold' | 'close'>('view'); const [kind, setKind] = useState<'goodwill' | 'refund' | 'none'>('goodwill'); const [amount, setAmount] = useState(''); const [dest, setDest] = useState<'source' | 'wallet'>('source'); const [bearer, setBearer] = useState<'platform' | 'partner'>('partner'); const [reason, setReason] = useState(REFUND_REASONS[0]![0]); const [text, setText] = useState('');
  const [cats, setCats] = useState<string[]>(['food_safety']); const [holdReason, setHoldReason] = useState(''); const [holdDur, setHoldDur] = useState('until inspection'); const [cancelExisting, setCancelExisting] = useState(true); const [holds, setHolds] = useState<Record<string, string>>({});
  const q = useOps<any[]>(db, 'ops_disputes', { p_market: m, p_severity: sev || null, p_open_only: openOnly }); const inc = useOps<any[]>(db, 'ops_incidents', { p_market: m }); const order = useOps<any>(db, 'ops_order_detail', { p_order: (q.data ?? []).find((x) => x.id === sel)?.order_id ?? null }, tab === 'disputes' && !!sel);
  const assign = useOpsMutation(db, 'ops_assign_dispute'); const resolve = useOpsMutation(db, 'ops_resolve_dispute'); const openInc = useOpsMutation(db, 'ops_open_incident'); const hold = useOpsMutation(db, 'ops_place_quality_hold'); const release = useOpsMutation(db, 'ops_release_quality_hold'); const close = useOpsMutation(db, 'ops_close_incident');
  const { msg, tone, act } = useAct(); const rows = q.data ?? []; const d = rows.find((x) => x.id === sel); const incs = inc.data ?? []; const i = incs.find((x) => x.id === sel); const mk = (d?.market ?? i?.market ?? 'KW') as Market; const st = order.data?.store;
  const refetch = () => { q.refetch(); inc.refetch(); setMode('view'); setText(''); };
  return <>
    <Row style={{ justifyContent: 'space-between' }}><T role="titleLg" weight={700}>Disputes &amp; incidents</T><Row><MarketToggle all value={m} onChange={setM} /><SegmentedControl fullWidth={false} value={tab} onChange={(v) => { setTab(v); setSel(null); setMode('view'); }} options={[{ value: 'disputes', label: `Disputes · ${rows.length}` }, { value: 'incidents', label: `Incidents · ${incs.filter((x) => !x.closed_at).length} open` }]} /></Row></Row>
    {msg ? <Banner tone={tone} title={msg} /> : null}
    {tab === 'disputes' ? <>
      <Row><Choice options={SEV} value={sev} onChange={setSev} /><Switch label="Open only" checked={openOnly} onChange={setOpenOnly} /></Row>
      <View style={{ flexDirection: 'row', gap: 14, alignItems: 'flex-start' }}>
        <Panel style={{ flex: 1 }}>{rows.length === 0 ? <Empty>{q.isLoading ? 'Loading…' : 'No disputes match.'}</Empty> : rows.map((x) => <ListRow key={x.id} chevron onPress={() => { setSel(x.id); setMode('view'); }} label={<Row><Num weight={700}>{x.case_ref}</Num><T role="label">{String(x.category).replace(/_/g, ' ')}</T></Row>} sub={`${x.market} · opened ${when(x.opened_at)} · ${x.resolved_at ? 'resolved ' + when(x.resolved_at) : slaLeft(x.sla_due_at)}${x.owner_ops_user ? (x.owner_ops_user === userId ? ' · mine' : ' · assigned') : ' · unassigned'}${x.illness_detail ? ' · ILLNESS — Compliance' : ''}`} value={<Badge tone={sevTone(x.severity) as any} uppercase>{x.severity}</Badge>} />)}</Panel>
        {d ? <Panel style={{ width: 460, padding: 14, gap: 8 }}>
          <Row style={{ justifyContent: 'space-between' }}><Row><Num role="title" weight={700}>{d.case_ref}</Num><Badge tone={sevTone(d.severity) as any} uppercase>{d.severity}</Badge></Row><Button size="sm" variant="ghost" onPress={() => setSel(null)}>Close</Button></Row>
          <Field k="Category" v={String(d.category).replace(/_/g, ' ')} /><Field k="Order" v={`${order.data?.order?.code ?? short(d.order_id)} · ${st?.display_name ?? ''} · ${order.data?.order ? money(order.data.order.total_minor, mk) : ''}`} /><Field k="Consumer says" v={d.consumer_statement ?? '—'} /><Field k="Partner says" v={d.partner_statement ?? (d.partner_deadline ? `awaiting reply by ${when(d.partner_deadline)}` : '—')} />
          {d.illness_detail ? <Banner tone="error" title="Illness reported">{typeof d.illness_detail === 'object' ? Object.entries(d.illness_detail).map(([k, v]) => `${k}: ${v}`).join(' · ') : String(d.illness_detail)}</Banner> : null}
          {(d.photos ?? []).length ? <Field k="Photos" v={(d.photos ?? []).join('\n')} /> : null}
          <Field k="Owner" v={d.owner_ops_user ? (d.owner_ops_user === userId ? 'you' : short(d.owner_ops_user)) : 'unassigned'} /><Field k="SLA" v={slaLeft(d.sla_due_at)} />
          {d.resolved_at ? <Banner tone="fresh" title={`Resolved ${when(d.resolved_at)}`}>{`${d.resolution ?? ''}${d.financial_outcome ? ' · ' + JSON.stringify(d.financial_outcome) : ''}`}</Banner> : mode === 'view' ? <Row>
            {d.owner_ops_user !== userId ? <Button size="sm" variant="secondary" onPress={() => act(assign, { p_dispute: d.id, p_ops_user: userId }, 'Assigned to you', refetch)}>Assign to me</Button> : null}
            <Button size="sm" onPress={() => setMode('resolve')}>Resolve…</Button>
            {d.severity === 'critical' ? <Button size="sm" variant="danger" onPress={() => setMode('incident')}>Open incident…</Button> : null}</Row> : null}
          {mode === 'resolve' ? <FormBox title="Resolve"><Choice label="Outcome" options={[['goodwill', 'Wallet goodwill'], ['refund', 'Refund'], ['none', 'No money']]} value={kind} onChange={setKind} />
            {kind !== 'none' ? <Row><View style={{ width: 160 }}><Input label={`Amount (${mk === 'KW' ? 'KWD' : 'EGP'})`} value={amount} onChangeText={setAmount} keyboardType="decimal-pad" /></View>{kind === 'refund' ? <><Choice label="Destination" options={[['source', 'Original method'], ['wallet', 'Wallet']]} value={dest} onChange={setDest} /><Choice label="Cost bearer" options={[['partner', 'Partner'], ['platform', 'Platform']]} value={bearer} onChange={setBearer} /></> : null}</Row> : null}
            <Choice label="Reason code" options={REFUND_REASONS} value={reason} onChange={setReason} /><Input label="Resolution (customer sees this)" value={text} onChangeText={setText} multiline />
            <Row><Button disabled={!text.trim() || (kind !== 'none' && !amount)} onPress={() => act(resolve, { p_dispute: d.id, p_resolution: text.trim(), p_outcome: kind === 'none' ? { kind: 'none', reason_code: reason } : { kind, amount_minor: toMinor(amount, mk), reason_code: reason, destination: dest, cost_bearer: bearer } }, 'Resolved — customer notified', refetch)}>Resolve</Button><Button variant="ghost" onPress={() => setMode('view')}>Back</Button></Row></FormBox> : null}
          {mode === 'incident' ? <FormBox title="Open a safety incident"><Caption>Creates a Compliance case for {st?.display_name ?? 'the store'} linked to this order. You can then place a quality hold from the Incidents tab.</Caption><Choice label="Categories" options={CATS} value={cats[0] ?? null} onChange={(c) => setCats(cats.includes(c) ? cats.filter((x) => x !== c) : [...cats, c])} /><Caption>Selected: {cats.join(', ') || 'none'}</Caption><Input label="Platform action taken so far" value={text} onChangeText={setText} />
            <Row><Button variant="danger" disabled={!cats.length || !order.data?.order} onPress={() => act(openInc, { p_payload: { market: d.market, partner_id: order.data.order.partner_id ?? st?.partner_id, store_id: order.data.order.store_id ?? st?.store_id, categories: cats, order_refs: [order.data.order.code], consumer_reports: [{ dispute: d.case_ref, statement: d.consumer_statement, illness: d.illness_detail }], platform_action: { note: text.trim() } } }, 'Incident opened — see the Incidents tab', () => { refetch(); setTab('incidents'); })}>Open incident</Button><Button variant="ghost" onPress={() => setMode('view')}>Back</Button></Row></FormBox> : null}
        </Panel> : null}</View></>
    : <View style={{ flexDirection: 'row', gap: 14, alignItems: 'flex-start' }}>
      <Panel style={{ flex: 1 }}>{incs.length === 0 ? <Empty>{inc.isLoading ? 'Loading…' : 'No incidents.'}</Empty> : incs.map((x) => <ListRow key={x.id} icon="triangle-alert" chevron onPress={() => { setSel(x.id); setMode('view'); }} label={<Row><Num weight={700}>{x.ref}</Num><T role="label">{(x.categories ?? []).join(', ')}</T></Row>} sub={`${x.market} · opened ${when(x.opened_at)} · orders ${(x.order_refs ?? []).join(', ') || '—'}${x.closed_at ? ' · closed ' + when(x.closed_at) : ''}`} value={<Badge tone={x.closed_at ? 'fresh' : 'error'}>{x.closed_at ? 'closed' : 'open'}</Badge>} />)}</Panel>
      {i ? <Panel style={{ width: 460, padding: 14, gap: 8 }}>
        <Row style={{ justifyContent: 'space-between' }}><Num role="title" weight={700}>{i.ref}</Num><Button size="sm" variant="ghost" onPress={() => setSel(null)}>Close</Button></Row>
        <Field k="Store" v={short(i.store_id)} /><Field k="Categories" v={(i.categories ?? []).join(', ')} /><Field k="Orders" v={(i.order_refs ?? []).join(', ') || '—'} /><Field k="Reports" v={i.consumer_reports ? JSON.stringify(i.consumer_reports) : '—'} /><Field k="Partner response" v={i.partner_response ?? '—'} /><Field k="Platform action" v={i.platform_action ? JSON.stringify(i.platform_action) : '—'} />
        {holds[i.id] ? <Banner tone="urgent" title="Quality hold in place" action="Release" onAction={() => act(release, { p_hold: holds[i.id] }, 'Hold released — store can publish again', () => { setHolds({ ...holds, [i.id]: '' }); refetch(); })}>Store paused; listings withdrawn.</Banner> : null}
        {i.closed_at ? <Banner tone="fresh" title={`Closed ${when(i.closed_at)}`}>{i.resolution ?? ''}</Banner> : mode === 'view' ? <Row><Button size="sm" variant="danger" onPress={() => setMode('hold')}>Place quality hold…</Button><Button size="sm" variant="secondary" onPress={() => setMode('close')}>Close incident…</Button></Row> : null}
        {mode === 'hold' ? <FormBox title="Quality hold on the store"><Caption>Pauses the store, withdraws live listings, notifies the partner. Compliance releases it after inspection.</Caption><Input label="Reason (partner sees this)" value={holdReason} onChangeText={setHoldReason} /><Choice label="Expected duration" options={[['until inspection', 'Until inspection'], ['24h', '24 hours'], ['72h', '72 hours'], ['7d', '7 days']]} value={holdDur} onChange={setHoldDur} /><Switch label="Cancel existing reservations (customers refunded, platform bears)" checked={cancelExisting} onChange={setCancelExisting} />
          <Row><Button variant="danger" disabled={!holdReason.trim()} onPress={() => act(hold, { p_store: i.store_id, p_reason: holdReason.trim(), p_duration: holdDur, p_cancel_existing: cancelExisting, p_incident: i.id }, 'Quality hold placed — store paused', refetch).then((h: any) => { if (h?.id) setHolds({ ...holds, [i.id]: h.id }); })}>Place hold</Button><Button variant="ghost" onPress={() => setMode('view')}>Back</Button></Row></FormBox> : null}
        {mode === 'close' ? <FormBox title="Close with a resolution (Compliance signs off)"><Input label="Resolution" value={text} onChangeText={setText} multiline /><Row><Button disabled={!text.trim()} onPress={() => act(close, { p_incident: i.id, p_resolution: text.trim() }, 'Incident closed', refetch)}>Close incident</Button><Button variant="ghost" onPress={() => setMode('view')}>Back</Button></Row></FormBox> : null}
      </Panel> : null}</View>}</>; }
