// S-O-050..052 Money per market: balance check, revenue, payout runs (create → approve ×2 → execute → confirm),
// reconciliation exceptions, tax report and ledger.
import { useState } from 'react'; import { View } from 'react-native'; import { useOps, useOpsMutation } from '@bugsha/api';
import { Badge, Banner, Button, Caption, Eyebrow, Input, ListRow, Num, PartnerStat, SegmentedControl, T, color } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { useSession } from '../../src/lib/session';
import { Choice, Field, FormBox, MarketToggle, Panel, Empty, Row, daysAgo, exportCsv, isoDate, money, useAct, when, short, type Market } from '../../src/lib/console';
const ADJ: Array<[string, string]> = [['psp_reconciliation', 'PSP reconciliation'], ['manual_correction', 'Manual correction'], ['cash_variance', 'Cash variance']];
const runTone = (s: string) => s === 'paid' || s === 'executed' ? 'fresh' : s === 'approved' ? 'time' : s === 'failed' ? 'error' : 'neutral';
export default function M() {
  const { userId } = useSession(); const [m, setM] = useState<Market>('KW'); const [tab, setTab] = useState<'payouts' | 'reconciliation' | 'reports' | 'ledger'>('payouts'); const [sel, setSel] = useState<string | null>(null); const [from, setFrom] = useState(isoDate(daysAgo(30))); const [to, setTo] = useState(isoDate(new Date())); const [kind, setKind] = useState<'psp' | 'cash'>('psp'); const [exc, setExc] = useState<string | null>(null); const [adj, setAdj] = useState(ADJ[0]![0]); const [text, setText] = useState(''); const [ref, setRef] = useState(''); const [fail, setFail] = useState<string | null>(null);
  const bal = useOps<any>(db, 'ops_balance_check', { p_market: m }); const runs = useOps<any[]>(db, 'ops_payout_runs', { p_market: m }); const run = useOps<any>(db, 'ops_payout_run_detail', { p_run: sel }, !!sel); const rev = useOps<any>(db, 'ops_revenue', { p_market: m, p_from: from, p_to: to }); const tax = useOps<any>(db, 'ops_tax_report', { p_market: m, p_from: from, p_to: to }, tab === 'reports'); const rec = useOps<any[]>(db, 'ops_reconciliation', { p_kind: kind, p_market: m, p_from: from, p_to: to }, tab === 'reconciliation'); const ledger = useOps<any[]>(db, 'ops_ledger', { p_market: m, p_from: from, p_to: to }, tab === 'ledger');
  const create = useOpsMutation(db, 'ops_create_payout_run'); const approve = useOpsMutation(db, 'ops_approve_payout_run'); const execute = useOpsMutation(db, 'ops_execute_payout_run'); const confirm = useOpsMutation(db, 'ops_confirm_payout'); const resolveExc = useOpsMutation(db, 'ops_resolve_exception'); const { msg, tone, act } = useAct();
  const refetch = () => { runs.refetch(); run.refetch(); bal.refetch(); rec.refetch(); setText(''); setFail(null); }; const r = run.data?.run; const suspense = bal.data?.suspense_minor ?? (bal.data?.balances ?? []).find((b: any) => b.account === 'unreconciled_suspense')?.balance_minor ?? 0;
  return <>
    <Row style={{ justifyContent: 'space-between' }}><T role="titleLg" weight={700}>Money</T><Row><MarketToggle value={m} onChange={(v) => { setM(v ?? 'KW'); setSel(null); }} /><SegmentedControl fullWidth={false} value={tab} onChange={setTab} options={[{ value: 'payouts', label: 'Payouts' }, { value: 'reconciliation', label: 'Reconciliation' }, { value: 'reports', label: 'Revenue & tax' }, { value: 'ledger', label: 'Ledger' }]} /></Row></Row>
    {msg ? <Banner tone={tone} title={msg} /> : null}
    <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 10 }}>
      <PartnerStat label="Unreconciled suspense" value={money(suspense, m)} tone={Number(suspense) !== 0 ? 'urgent' : 'fresh'} style={{ minWidth: 200 }} />
      <PartnerStat label={`GMV · ${from} → ${to}`} value={money(rev.data?.gmv_minor, m)} sub={`${rev.data?.orders ?? 0} orders`} style={{ minWidth: 200 }} />
      <PartnerStat label="Commission recognised" value={money(rev.data?.commission_recognised_minor, m)} sub={rev.data?.take_rate != null ? `take rate ${(Number(rev.data.take_rate) * 100).toFixed(1)}%` : undefined} style={{ minWidth: 200 }} />
      <PartnerStat label="No-show fees retained" value={money(rev.data?.no_show_retained_minor, m)} style={{ minWidth: 200 }} />
      <PartnerStat label="VAT" value={money(rev.data?.vat_minor, m)} style={{ minWidth: 160 }} /></View>
    <Row><View style={{ width: 150 }}><Input label="From" value={from} onChangeText={setFrom} placeholder="YYYY-MM-DD" /></View><View style={{ width: 150 }}><Input label="To" value={to} onChangeText={setTo} placeholder="YYYY-MM-DD" /></View></Row>
    {tab === 'payouts' ? <>
      <Row style={{ justifyContent: 'space-between' }}><Eyebrow>Payout runs</Eyebrow><Button size="sm" onPress={() => act(create, { p_market: m, p_period_start: isoDate(daysAgo(7)), p_period_end: isoDate(new Date()) }, 'Run created for the last 7 days', refetch)}>Create run · last 7 days</Button></Row>
      <Caption>A run needs two different approvers, both re-authenticated within 5 minutes, before Finance executes it. Failed payouts are confirmed by hand from the provider record.</Caption>
      <View style={{ flexDirection: 'row', gap: 14, alignItems: 'flex-start' }}>
        <Panel style={{ flex: 1 }}>{(runs.data ?? []).length === 0 ? <Empty>No runs yet.</Empty> : (runs.data ?? []).map((x) => <ListRow key={x.id} chevron onPress={() => setSel(x.id)} label={<Num weight={600}>{`${x.period_start} → ${x.period_end}`}</Num>} sub={`created ${when(x.created_at)}${x.approved_by_1 ? ' · approver 1 ✓' : ''}${x.approved_by_2 ? ' · approver 2 ✓' : ''}${x.executed_at ? ' · executed ' + when(x.executed_at) : ''}`} value={<Badge tone={runTone(x.status) as any}>{x.status}</Badge>} />)}</Panel>
        {sel && r ? <Panel style={{ width: 460, padding: 14, gap: 8 }}>
          <Row style={{ justifyContent: 'space-between' }}><Row><Num role="title" weight={700}>{`${r.period_start} → ${r.period_end}`}</Num><Badge tone={runTone(r.status) as any}>{r.status}</Badge></Row><Button size="sm" variant="ghost" onPress={() => setSel(null)}>Close</Button></Row>
          <Field k="Approvals" v={`${r.approved_by_1 ? '1 ✓ ' + when(r.approved_by_1_at) : '1 —'} · ${r.approved_by_2 ? '2 ✓ ' + when(r.approved_by_2_at) : '2 —'}`} /><Field k="Payouts" v={`${(run.data.payouts ?? []).length} · total ${money((run.data.payouts ?? []).reduce((s: number, p: any) => s + Number(p.net_minor ?? 0), 0), m)}`} />
          {(run.data.exceptions ?? []).length ? <Banner tone="time" title={`${run.data.exceptions.length} held`}>{run.data.exceptions.map((e: any) => `${short(e.partner_id)}: ${e.reason}`).join(' · ')}</Banner> : null}
          <Row>
            {['pending', 'ready', 'frozen'].includes(r.status) || (r.status === 'approved' && !r.approved_by_2) ? <Button size="sm" disabled={r.approved_by_1 === userId} onPress={() => act(approve, { p_run: r.id }, r.approved_by_1 ? 'Second approval recorded — ready to execute' : 'First approval recorded — a different admin approves next', refetch)}>{r.approved_by_1 ? 'Approve (2 of 2)' : 'Approve (1 of 2)'}</Button> : null}
            {r.status === 'approved' && r.approved_by_2 ? <Button size="sm" variant="danger" onPress={() => act(execute, { p_run: r.id }, 'Executing — confirm each payout from the provider record', refetch)}>Execute</Button> : null}
            <Button size="sm" variant="ghost" onPress={() => exportCsv(`payout-run-${r.period_start}`, run.data.payouts ?? [])}>Export CSV</Button></Row>
          <Eyebrow>Payouts</Eyebrow>
          {(run.data.payouts ?? []).map((p: any) => <View key={p.payout_id} style={{ gap: 6, paddingVertical: 6, borderTopWidth: 1, borderTopColor: color.borderSubtle }}>
            <Row style={{ justifyContent: 'space-between' }}><Row><Num weight={600}>{money(p.net_minor, m)}</Num><Caption>{`partner ${short(p.partner_id)} · gross ${money(p.gross_minor, m)} · netted ${money(p.netted_minor, m)}${p.carry_in_minor ? ' · carry in ' + money(p.carry_in_minor, m) : ''}${p.hold_reason ? ' · ' + p.hold_reason : ''}${p.provider_ref ? ' · ' + p.provider_ref : ''}`}</Caption></Row><Badge tone={p.status === 'paid' ? 'fresh' : p.status === 'failed' ? 'error' : p.status === 'held' ? 'urgent' : 'neutral'}>{p.status}</Badge></Row>
            {p.status === 'executing' ? <Row><View style={{ width: 200 }}><Input placeholder="Provider reference" value={fail === p.payout_id ? ref : ref} onChangeText={setRef} /></View><Button size="sm" disabled={!ref.trim()} onPress={() => act(confirm, { p_payout: p.payout_id, p_provider_ref: ref.trim(), p_success: true }, 'Payout confirmed paid', refetch)}>Confirm paid</Button><Button size="sm" variant="ghost" onPress={() => setFail(fail === p.payout_id ? null : p.payout_id)}>Failed…</Button></Row> : null}
            {fail === p.payout_id ? <Row><View style={{ flex: 1 }}><Input placeholder="Failure reason from the bank / provider" value={text} onChangeText={setText} /></View><Button size="sm" variant="danger" disabled={!text.trim()} onPress={() => act(confirm, { p_payout: p.payout_id, p_provider_ref: ref.trim() || 'n/a', p_success: false, p_failure_reason: text.trim() }, 'Marked failed — carried to the next run', refetch)}>Mark failed</Button></Row> : null}</View>)}
        </Panel> : null}</View></> : null}
    {tab === 'reconciliation' ? <>
      <Row><Choice options={[['psp', 'Card / PSP'], ['cash', 'Cash']]} value={kind} onChange={setKind} /><Button size="sm" variant="ghost" onPress={() => exportCsv(`reconciliation-${kind}`, rec.data ?? [])}>Export CSV</Button></Row>
      <Panel>{(rec.data ?? []).length === 0 ? <Empty>{rec.isLoading ? 'Loading…' : 'No exceptions in the window.'}</Empty> : (rec.data ?? []).map((x) => <View key={x.id}><ListRow icon="triangle-alert" onPress={() => setExc(exc === x.id ? null : x.id)} label={<T role="label" weight={600}>{String(x.exception_type).replace(/_/g, ' ')}</T>} sub={`${when(x.created_at)} · expected ${money(x.expected_minor, m)} · actual ${money(x.actual_minor, m)}${x.provider_ref ? ' · ' + x.provider_ref : ''}${x.store_id ? ' · store ' + short(x.store_id) : ''}${x.resolution ? ' · ' + x.resolution : ''}`} value={<Badge tone={x.status === 'open' ? 'urgent' : 'fresh'}>{x.status}</Badge>} />
        {exc === x.id && x.status === 'open' ? <View style={{ margin: 12 }}><FormBox title="Resolve with an adjustment"><Choice options={ADJ} value={adj} onChange={setAdj} /><Input label="Resolution note" value={text} onChangeText={setText} /><Row><Button disabled={!text.trim()} onPress={() => act(resolveExc, { p_id: x.id, p_resolution: text.trim(), p_reason_code: adj }, 'Exception resolved', () => { refetch(); setExc(null); })}>Resolve</Button><Button variant="ghost" onPress={() => setExc(null)}>Cancel</Button></Row></FormBox></View> : null}</View>)}</Panel></> : null}
    {tab === 'reports' ? <View style={{ flexDirection: 'row', gap: 14, alignItems: 'flex-start', flexWrap: 'wrap' }}>
      <Panel style={{ flex: 1, minWidth: 320, padding: 14, gap: 6 }}><Eyebrow>Revenue</Eyebrow>{rev.data ? Object.entries(rev.data).filter(([k]) => k !== 'market').map(([k, v]) => <Field key={k} k={k.replace(/_/g, ' ')} v={k.endsWith('_minor') ? money(v as number, m) : k === 'take_rate' ? `${(Number(v) * 100).toFixed(2)}%` : String(v)} w={200} />) : <Caption>Loading…</Caption>}</Panel>
      <Panel style={{ flex: 1, minWidth: 320, padding: 14, gap: 6 }}><Row style={{ justifyContent: 'space-between' }}><Eyebrow>Tax report</Eyebrow><Button size="sm" variant="ghost" onPress={() => tax.data && exportCsv(`tax-${m}-${from}`, [tax.data])}>Export</Button></Row>{tax.data ? Object.entries(tax.data).filter(([k]) => k !== 'market').map(([k, v]) => <Field key={k} k={k.replace(/_/g, ' ')} v={k.endsWith('_minor') ? money(v as number, m) : String(v)} w={200} />) : <Caption>{tax.isLoading ? 'Loading…' : 'VAT does not apply in this market.'}</Caption>}</Panel>
      <Panel style={{ flex: 1, minWidth: 320, padding: 14, gap: 6 }}><Eyebrow>Account balances</Eyebrow>{(bal.data?.balances ?? []).map((b: any) => <Field key={b.account} k={String(b.account).replace(/_/g, ' ')} v={money(b.balance_minor, m)} w={200} />)}</Panel></View> : null}
    {tab === 'ledger' ? <><Row style={{ justifyContent: 'space-between' }}><Eyebrow>Financial entries · {(ledger.data ?? []).length}</Eyebrow><Button size="sm" variant="ghost" onPress={() => exportCsv(`ledger-${m}-${from}`, ledger.data ?? [])}>Export CSV</Button></Row>
      <Panel>{(ledger.data ?? []).length === 0 ? <Empty>{ledger.isLoading ? 'Loading…' : 'No entries in the window.'}</Empty> : (ledger.data ?? []).slice(0, 300).map((e: any) => <ListRow key={e.id} label={<Row><Badge tone={e.entry_type === 'credit' ? 'fresh' : 'neutral'}>{e.entry_type}</Badge><T role="label">{String(e.account).replace(/_/g, ' ')}</T></Row>} sub={`${when(e.recorded_at)} · ${e.reference_type ?? ''} ${short(e.order_id ?? e.reference_id)}${e.partner_id ? ' · partner ' + short(e.partner_id) : ''}`} value={<Num weight={600}>{money(e.amount_minor, m)}</Num>} />)}</Panel></> : null}
  </>; }
