// S-O-030 Orders: filter by market/status/code; detail with timeline, payment, refunds, ledger; force cancel
// (cost bearer), force redeem, extend window, reissue code, reverse redemption, resend a notification.
import { useState } from 'react'; import { View } from 'react-native'; import { useOps, useOpsMutation } from '@bugsha/api';
import { Badge, Banner, Button, Caption, Eyebrow, Input, ListRow, Num, T, color } from '@bugsha/ui'; import { db } from '../../src/lib/supabase';
import { Choice, Field, FormBox, MarketToggle, Panel, Empty, Row, money, useAct, when, short, type Market } from '../../src/lib/console';
const STATUSES: Array<[string, string]> = [['', 'All'], ['held', 'Held'], ['reserved', 'Reserved'], ['redeemed', 'Redeemed'], ['cancelled_consumer', 'Cancelled (consumer)'], ['cancelled_partner', 'Cancelled (partner)'], ['no_show', 'No-show'], ['refunded', 'Refunded']];
const CANCEL_REASONS: Array<[string, string]> = [['consumer_request', 'Consumer asked'], ['partner_cancelled', 'Partner cannot fulfil'], ['quality_issue', 'Quality issue'], ['duplicate_capture', 'Duplicate charge'], ['never_received', 'Never received']];
const BEARERS: Array<[string, string]> = [['platform', 'Platform'], ['partner', 'Partner']];
const tone = (s: string) => s === 'redeemed' ? 'fresh' : s === 'reserved' || s === 'held' ? 'time' : s === 'no_show' ? 'urgent' : 'neutral';
export default function O() {
  const [m, setM] = useState<Market | null>(null); const [st, setSt] = useState(''); const [code, setCode] = useState(''); const [sel, setSel] = useState<string | null>(null); const [modal, setModal] = useState<'cancel' | 'redeem' | 'extend' | 'reissue' | 'reverse' | null>(null);
  const [reason, setReason] = useState(CANCEL_REASONS[0]![0]); const [bearer, setBearer] = useState('platform'); const [just, setJust] = useState(''); const [mins, setMins] = useState('30');
  const list = useOps<any[]>(db, 'ops_orders', { p_market: m, p_status: st || null, p_code: code.trim() ? code.trim().toUpperCase() : null }); const det = useOps<any>(db, 'ops_order_detail', { p_order: sel }, !!sel); const notes = useOps<any[]>(db, 'ops_notifications', { p_user: det.data?.order?.consumer_id ?? null, p_limit: 20 }, !!det.data?.order?.consumer_id);
  const cancel = useOpsMutation(db, 'ops_force_cancel'); const redeem = useOpsMutation(db, 'ops_force_redeem'); const extend = useOpsMutation(db, 'ops_extend_window'); const reissue = useOpsMutation(db, 'ops_reissue_code'); const reverse = useOpsMutation(db, 'ops_reverse_redemption'); const resend = useOpsMutation(db, 'ops_resend_notification');
  const { msg, tone: bt, act } = useAct(); const refetch = () => { list.refetch(); det.refetch(); setModal(null); setJust(''); };
  const d = det.data; const o = d?.order; const mk = (o?.market ?? m ?? 'KW') as Market;
  return <>
    <Row style={{ justifyContent: 'space-between' }}><T role="titleLg" weight={700}>Orders</T><MarketToggle all value={m} onChange={setM} /></Row>
    <Row><View style={{ width: 200 }}><Input icon="search" placeholder="Code (R3D-9F)" value={code} onChangeText={setCode} autoCapitalize="characters" /></View><Choice options={STATUSES} value={st} onChange={setSt} /></Row>
    {msg ? <Banner tone={bt} title={msg} /> : null}
    <View style={{ flexDirection: 'row', gap: 14, alignItems: 'flex-start' }}>
      <Panel style={{ flex: 1 }}>{(list.data ?? []).length === 0 ? <Empty>{list.isLoading ? 'Loading…' : 'No orders match.'}</Empty> : (list.data ?? []).map((x) => <ListRow key={x.order_id} chevron onPress={() => { setSel(x.order_id); setModal(null); }} label={<Row><Num weight={700}>{x.code}</Num><Caption>{x.customer_first_name ?? ''}</Caption></Row>} sub={`${x.market} · ${money(x.total_minor, x.market)} · ${x.method ?? ''} · ${x.quantity} bag · ${when(x.window_start_utc)}–${when(x.window_end_utc).slice(-5)}`} value={<Badge tone={tone(x.status) as any}>{String(x.status).replace(/_/g, ' ')}</Badge>} />)}</Panel>
      {sel ? <View style={{ width: 440, gap: 10 }}>
        <Panel style={{ padding: 14, gap: 8 }}>
          <Row style={{ justifyContent: 'space-between' }}><Row><Num role="title" weight={700}>{o?.code ?? '…'}</Num>{o ? <Badge tone={tone(o.status) as any}>{String(o.status).replace(/_/g, ' ')}</Badge> : null}</Row><Button size="sm" variant="ghost" onPress={() => setSel(null)}>Close</Button></Row>
          {o ? <>
            <Field k="Store" v={`${d.store?.display_name ?? ''} · ${o.market}`} /><Field k="Consumer" v={o.consumer_id ? short(o.consumer_id) : '—'} /><Field k="Window" v={`${when(o.window_start_utc)} → ${when(o.window_end_utc)}`} />
            <Field k="Total" v={`${money(o.total_minor, mk)} · ${o.method ?? ''}${o.tax_minor ? ` · VAT ${money(o.tax_minor, mk)}` : ''}${o.service_fee_minor ? ` · fee ${money(o.service_fee_minor, mk)}` : ''}`} />
            <Field k="Payment" v={d.payment ? `${d.payment.status} · ${d.payment.provider ?? ''} ${d.payment.provider_ref ?? ''}` : '—'} />
            <Field k="Redemption" v={d.redemption ? `${d.redemption.mechanism ?? ''} · ${when(d.redemption.redeemed_at ?? d.redemption.created_at)}${d.redemption.late ? ' · late' : ''}` : '—'} />
            {(d.refunds ?? []).length ? <Field k="Refunds" v={(d.refunds ?? []).map((r: any) => `${money(r.amount_minor, mk)} → ${r.destination} · ${r.status} · ${r.reason_code}`).join('\n')} /> : null}
            <Eyebrow>Actions</Eyebrow>
            <Row>
              {['held', 'reserved'].includes(o.status) ? <Button size="sm" variant="danger" onPress={() => setModal(modal === 'cancel' ? null : 'cancel')}>Force cancel</Button> : null}
              {o.status === 'reserved' ? <><Button size="sm" variant="secondary" onPress={() => setModal(modal === 'redeem' ? null : 'redeem')}>Force redeem</Button><Button size="sm" variant="secondary" onPress={() => setModal(modal === 'extend' ? null : 'extend')}>Extend window</Button><Button size="sm" variant="ghost" onPress={() => setModal(modal === 'reissue' ? null : 'reissue')}>Reissue code</Button></> : null}
              {o.status === 'redeemed' ? <Button size="sm" variant="danger" onPress={() => setModal(modal === 'reverse' ? null : 'reverse')}>Reverse redemption</Button> : null}</Row>
            {modal === 'cancel' ? <FormBox title="Force cancel"><Caption>Refund goes back to the original method. Above the support cap this needs a second approver.</Caption><Choice label="Reason" options={CANCEL_REASONS} value={reason} onChange={setReason} /><Choice label="Who bears the cost" options={BEARERS} value={bearer} onChange={setBearer} /><Input label="Justification (audited)" value={just} onChangeText={setJust} /><Row><Button variant="danger" disabled={!just.trim()} onPress={() => act(cancel, { p_order: o.order_id, p_reason_code: reason, p_cost_bearer: bearer, p_justification: just.trim() }, 'Cancelled and refunded', refetch)}>Cancel order</Button><Button variant="ghost" onPress={() => setModal(null)}>Back</Button></Row></FormBox> : null}
            {modal === 'redeem' ? <FormBox title="Force redeem"><Caption>Use when the partner confirms hand-over but could not record it (device down). Counts as collected for both sides.</Caption><Input label="Justification" value={just} onChangeText={setJust} /><Row><Button disabled={!just.trim()} onPress={() => act(redeem, { p_order: o.order_id, p_reason_code: 'manual_correction', p_justification: just.trim() }, 'Marked redeemed', refetch)}>Mark redeemed</Button><Button variant="ghost" onPress={() => setModal(null)}>Back</Button></Row></FormBox> : null}
            {modal === 'extend' ? <FormBox title="Extend the pickup window"><Choice options={[['15', '+15 min'], ['30', '+30 min'], ['60', '+1 hour'], ['120', '+2 hours']]} value={mins} onChange={setMins} /><Caption>New end {when(new Date(Date.parse(o.window_end_utc) + Number(mins) * 60_000).toISOString())}. The customer is notified.</Caption><Row><Button onPress={() => act(extend, { p_order: o.order_id, p_new_end: new Date(Date.parse(o.window_end_utc) + Number(mins) * 60_000).toISOString(), p_reason_code: 'consumer_request' }, `Window extended by ${mins} min`, refetch)}>Extend</Button><Button variant="ghost" onPress={() => setModal(null)}>Back</Button></Row></FormBox> : null}
            {modal === 'reissue' ? <FormBox title="Reissue the pickup code"><Caption>The old code stops working; the customer sees the new one in the app.</Caption><Row><Button onPress={() => act(reissue, { p_order: o.order_id, p_reason_code: 'consumer_request' }, 'New code issued', refetch)}>Reissue</Button><Button variant="ghost" onPress={() => setModal(null)}>Back</Button></Row></FormBox> : null}
            {modal === 'reverse' ? <FormBox title="Reverse the redemption"><Caption>Puts the order back to reserved and reverses the ledger. Only for a hand-over recorded by mistake.</Caption><Input label="Justification" value={just} onChangeText={setJust} /><Row><Button variant="danger" disabled={!just.trim()} onPress={() => act(reverse, { p_order: o.order_id, p_reason_code: 'manual_correction', p_justification: just.trim() }, 'Redemption reversed', refetch)}>Reverse</Button><Button variant="ghost" onPress={() => setModal(null)}>Back</Button></Row></FormBox> : null}
            <Eyebrow>Timeline</Eyebrow>
            {(d.audit ?? []).length === 0 ? <Caption>No ops actions on this order.</Caption> : (d.audit ?? []).map((a: any) => <Field key={a.id} k={when(a.at)} v={`${a.operation} · ${a.actor_role ?? ''} ${a.reason_code ?? ''} ${a.justification ?? ''}`} w={110} />)}
            {(d.ledger ?? []).length ? <><Eyebrow>Ledger</Eyebrow>{(d.ledger ?? []).map((e: any) => <Field key={e.id} k={when(e.recorded_at)} v={`${e.account} ${e.entry_type} ${money(e.amount_minor, mk)}`} w={110} />)}</> : null}
            <Eyebrow>Notifications to this customer</Eyebrow>
            {(notes.data ?? []).length === 0 ? <Caption>None logged.</Caption> : (notes.data ?? []).slice(0, 8).map((n: any) => <Row key={n.id} style={{ justifyContent: 'space-between' }}><Caption style={{ flex: 1 }}>{`${n.template_key} · ${(n.channels ?? []).join('/')} · ${when(n.sent_at)}${n.suppressed_reason ? ' · suppressed: ' + n.suppressed_reason : ''}`}</Caption><Button size="sm" variant="ghost" onPress={() => act(resend, { p_log: n.id }, 'Notification re-sent', () => notes.refetch())}>Resend</Button></Row>)}
          </> : <Caption>Loading…</Caption>}</Panel></View> : null}</View></>; }
