// S-O-020 Partners by onboarding stage and market. Decisions live on the detail page.
import { useState } from 'react'; import { View } from 'react-native'; import { router } from 'expo-router'; import { useOps } from '@bugsha/api';
import { Badge, Caption, Input, ListRow, T } from '@bugsha/ui'; import { db } from '../../src/lib/supabase'; import { Choice, MarketToggle, Panel, Empty, Row, day, type Market } from '../../src/lib/console';
const STAGES: Array<[string, string]> = [['lead', 'Lead'], ['applied', 'Applied'], ['documents_pending', 'Documents'], ['under_review', 'Under review'], ['approved', 'Approved'], ['contract_pending', 'Contract pending'], ['contract_signed', 'Contract signed'], ['store_setup', 'Store setup'], ['first_listing_pending', 'First listing'], ['active', 'Active'], ['suspended', 'Suspended'], ['rejected', 'Rejected']];
export const stageTone = (s: string) => s === 'active' ? 'fresh' : s === 'rejected' ? 'error' : s === 'suspended' ? 'urgent' : 'time';
export default function P() {
  const [m, setM] = useState<Market | null>(null); const [st, setSt] = useState<string | null>(null); const [q, setQ] = useState(''); const list = useOps<any[]>(db, 'ops_partners', { p_status: st, p_market: m });
  const rows = (list.data ?? []).filter((p) => !q || `${p.trading_name} ${p.legal_name ?? ''}`.toLowerCase().includes(q.toLowerCase()));
  return <>
    <Row style={{ justifyContent: 'space-between' }}><T role="titleLg" weight={700}>Partners</T><MarketToggle all value={m} onChange={setM} /></Row>
    <Row><View style={{ width: 300 }}><Input icon="search" placeholder="Trading name" value={q} onChangeText={setQ} /></View><Choice options={[['', 'All stages'] as [string, string], ...STAGES]} value={st ?? ''} onChange={(v) => setSt(v || null)} /></Row>
    <Caption>{rows.length} partners{st ? ` · ${st.replace(/_/g, ' ')}` : ''}. Approve, activate, suspend or change commission from a partner’s page.</Caption>
    <Panel>{rows.length === 0 ? <Empty>{list.isLoading ? 'Loading…' : 'No partners match.'}</Empty> : rows.map((p) => <ListRow key={p.partner_id} icon="store" chevron onPress={() => router.push(`/(console)/partner/${p.partner_id}`)} label={<T role="label" weight={600}>{p.trading_name}</T>} sub={`${p.market}${p.legal_name ? ' · ' + p.legal_name : ''} · reliability ${p.reliability_override ?? p.reliability_score ?? '—'} · since ${day(p.created_at)}`} value={<Row>{p.suspended_until && new Date(p.suspended_until) > new Date() ? <Badge tone="urgent">suspended</Badge> : null}<Badge tone={stageTone(p.onboarding_status) as any}>{String(p.onboarding_status).replace(/_/g, ' ')}</Badge></Row>} />)}</Panel></>; }
