// S-O-060 Users: search by phone; profile, orders, wallet, disputes; restrict / lift, issue credit,
// impersonate (consent captured, 30 minutes, read-only), resend a notification.
import { useState } from 'react'; import { View } from 'react-native'; import { useOps, useOpsMutation } from '@bugsha/api';
import { Badge, Banner, Button, Caption, Eyebrow, Input, ListRow, Num, T } from '@bugsha/ui'; import { db } from '../../src/lib/supabase';
import { Choice, Field, FormBox, MarketToggle, Panel, Empty, Row, money, toMinor, useAct, when, short, type Market } from '../../src/lib/console';
const RESTRICT: Array<[string, string]> = [['repeat_no_show', 'Repeat no-show'], ['suspected_abuse', 'Suspected abuse']];
export default function U() {
  const [m, setM] = useState<Market | null>(null); const [phone, setPhone] = useState(''); const [sel, setSel] = useState<string | null>(null); const [mode, setMode] = useState<'view' | 'restrict' | 'credit' | 'impersonate'>('view'); const [reason, setReason] = useState(RESTRICT[0]![0]); const [days, setDays] = useState('30'); const [amount, setAmount] = useState(''); const [text, setText] = useState(''); const [consent, setConsent] = useState('');
  const list = useOps<any[]>(db, 'ops_users', { p_market: m, p_phone: phone.trim() || null }); const det = useOps<any>(db, 'ops_user_detail', { p_user: sel }, !!sel); const notes = useOps<any[]>(db, 'ops_notifications', { p_user: sel, p_limit: 10 }, !!sel);
  const restrict = useOpsMutation(db, 'ops_restrict_user'); const credit = useOpsMutation(db, 'ops_issue_credit'); const imp = useOpsMutation(db, 'ops_start_impersonation'); const endImp = useOpsMutation(db, 'ops_end_impersonation'); const resend = useOpsMutation(db, 'ops_resend_notification'); const { msg, tone, act } = useAct(); const [session, setSession] = useState<any>(null);
  const d = det.data; const p = d?.profile; const mk = (p?.market ?? 'KW') as Market; const restricted = p?.restricted_until && new Date(p.restricted_until) > new Date(); const refetch = () => { list.refetch(); det.refetch(); setMode('view'); setText(''); };
  return <>
    <Row style={{ justifyContent: 'space-between' }}><T role="titleLg" weight={700}>Users</T><MarketToggle all value={m} onChange={setM} /></Row>
    <Row><View style={{ width: 260 }}><Input icon="search" placeholder="Phone (+965…)" value={phone} onChangeText={setPhone} keyboardType="phone-pad" /></View><Caption>Search by phone. Email search is not exposed to ops.</Caption></Row>
    {msg ? <Banner tone={tone} title={msg} /> : null}
    <View style={{ flexDirection: 'row', gap: 14, alignItems: 'flex-start' }}>
      <Panel style={{ flex: 1 }}>{(list.data ?? []).length === 0 ? <Empty>{list.isLoading ? 'Loading…' : 'No users match.'}</Empty> : (list.data ?? []).map((u) => <ListRow key={u.user_id} icon="user" chevron onPress={() => { setSel(u.user_id); setMode('view'); }} label={<T role="label" weight={600}>{u.first_name ?? short(u.user_id)}</T>} sub={`${u.market} · ${u.phone ?? '—'} · joined ${when(u.created_at)} · ${u.no_show_count_90d ?? 0} no-shows / 90d`} value={u.restricted_until && new Date(u.restricted_until) > new Date() ? <Badge tone="urgent">restricted</Badge> : undefined} />)}</Panel>
      {sel ? <Panel style={{ width: 460, padding: 14, gap: 8 }}>
        <Row style={{ justifyContent: 'space-between' }}><Row><T role="title" weight={700}>{p?.first_name ?? '…'} {p?.last_name ?? ''}</T>{restricted ? <Badge tone="urgent">restricted until {when(p.restricted_until)}</Badge> : null}</Row><Button size="sm" variant="ghost" onPress={() => setSel(null)}>Close</Button></Row>
        {p ? <>
          <Field k="Phone / email" v={`${p.phone ?? '—'} · ${p.email ?? '—'}`} /><Field k="Market" v={`${p.market}${p.city_id ? ' · ' + short(p.city_id) : ''}`} /><Field k="Wallet" v={money(d.wallet, mk)} /><Field k="Reliability" v={String(p.reliability_score ?? '—')} /><Field k="Dietary" v={(p.dietary_flags ?? []).join(', ') || '—'} />{p.deletion_requested_at ? <Field k="Deletion" v={`requested ${when(p.deletion_requested_at)}`} /> : null}{restricted ? <Field k="Restriction" v={`${p.restriction_reason_code} until ${when(p.restricted_until)}`} /> : null}
          {session ? <Banner tone="time" title={`Impersonating (read-only) until ${when(session.hard_expires_at)}`} action="End" onAction={() => act(endImp, { p_session: session.id }, 'Impersonation ended', () => setSession(null))}>Session {short(session.id)} is audited.</Banner> : null}
          {mode === 'view' ? <Row>
            {restricted ? <Button size="sm" variant="secondary" onPress={() => act(restrict, { p_user: sel, p_reason_code: p.restriction_reason_code ?? 'repeat_no_show', p_until: new Date().toISOString() }, 'Restriction lifted', refetch)}>Lift restriction</Button> : <Button size="sm" variant="danger" onPress={() => setMode('restrict')}>Restrict…</Button>}
            <Button size="sm" variant="secondary" onPress={() => setMode('credit')}>Issue credit…</Button>
            {!session ? <Button size="sm" variant="ghost" onPress={() => setMode('impersonate')}>Impersonate…</Button> : null}</Row> : null}
          {mode === 'restrict' ? <FormBox title="Restrict reservations"><Choice options={RESTRICT} value={reason} onChange={setReason} /><Choice label="For" options={[['7', '7 days'], ['30', '30 days'], ['90', '90 days']]} value={days} onChange={setDays} /><Caption>The customer sees the reason and the end date in the app; existing orders are kept.</Caption><Row><Button variant="danger" onPress={() => act(restrict, { p_user: sel, p_reason_code: reason, p_until: new Date(Date.now() + Number(days) * 864e5).toISOString() }, `Restricted for ${days} days`, refetch)}>Restrict</Button><Button variant="ghost" onPress={() => setMode('view')}>Back</Button></Row></FormBox> : null}
          {mode === 'credit' ? <FormBox title="Issue wallet credit (goodwill)"><Row><View style={{ width: 160 }}><Input label={`Amount (${mk === 'KW' ? 'KWD' : 'EGP'})`} value={amount} onChangeText={setAmount} keyboardType="decimal-pad" /></View></Row><Caption>Posted as goodwill expense; above the support cap it needs a second approver.</Caption><Row><Button disabled={!amount} onPress={() => act(credit, { p_user: sel, p_amount_minor: toMinor(amount, mk), p_reason_code: 'goodwill' }, `${amount} credited to the wallet`, refetch)}>Issue credit</Button><Button variant="ghost" onPress={() => setMode('view')}>Back</Button></Row></FormBox> : null}
          {mode === 'impersonate' ? <FormBox title="Impersonate (read-only, 30 minutes)"><Input label="Reason (audited)" value={text} onChangeText={setText} /><Input label="Consent — how and when the customer agreed" value={consent} onChangeText={setConsent} placeholder="e.g. phone call 14 Sep 10:20, agreed" /><Row><Button disabled={!text.trim() || !consent.trim()} onPress={() => act(imp, { p_target: sel, p_reason: text.trim(), p_consent: consent.trim() }, 'Impersonation started — read-only for 30 minutes').then((s: any) => { if (s) { setSession(s); setMode('view'); } })}>Start</Button><Button variant="ghost" onPress={() => setMode('view')}>Back</Button></Row></FormBox> : null}
          <Eyebrow>Orders · {(d.orders ?? []).length}</Eyebrow>
          {(d.orders ?? []).slice(0, 10).map((o: any) => <Field key={o.order_id} k={when(o.created_at)} v={`${o.code} · ${String(o.status).replace(/_/g, ' ')} · ${money(o.total_minor, mk)} · ${o.method ?? ''}`} w={110} />)}
          {(d.disputes ?? []).length ? <><Eyebrow>Disputes</Eyebrow>{(d.disputes ?? []).map((x: any) => <Field key={x.id} k={x.case_ref} v={`${x.category} · ${x.severity} · ${x.resolved_at ? 'resolved' : 'open'}`} w={110} />)}</> : null}
          <Eyebrow>Notifications</Eyebrow>
          {(notes.data ?? []).length === 0 ? <Caption>None logged.</Caption> : (notes.data ?? []).map((n: any) => <Row key={n.id} style={{ justifyContent: 'space-between' }}><Caption style={{ flex: 1 }}>{`${n.template_key} · ${(n.channels ?? []).join('/')} · ${when(n.sent_at)}${n.suppressed_reason ? ' · suppressed: ' + n.suppressed_reason : ''}`}</Caption><Button size="sm" variant="ghost" onPress={() => act(resend, { p_log: n.id }, 'Re-sent', () => notes.refetch())}>Resend</Button></Row>)}
        </> : <Caption>Loading…</Caption>}</Panel> : null}</View></>; }
